### ISSUE TITLE
Flaky `test_e2e_with_entity_evaluation` test

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8395] opened 2021-04-08 12:31 UTC
**Rasa version**: 2.4.2

**Python version**: 3.7 & 3.8

**Operating system** (windows, osx, ...): Windows 

**Issue**:
`test_e2e_with_entity_evaluation` can sometimes fail when running on Windows machines.

```
_______________________ test_e2e_with_entity_evaluation _______________________
[gw1] win32 -- Python 3.6.8 d:\a\rasa\rasa\.venv\scripts\python.exe

e2e_bot_agent = <rasa.core.agent.Agent object at 0x0000012CC10B1F28>
tmp_path = WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw1/test_e2e_with_entity_evaluatio0')

    @pytest.mark.timeout(240)
    async def test_e2e_with_entity_evaluation(e2e_bot_agent: Agent, tmp_path: Path):
        test_file = "data/test_e2ebot/tests/test_stories.yml"
    
        await evaluate_stories(
            stories=test_file,
            agent=e2e_bot_agent,
            out_directory=str(tmp_path),
            max_stories=None,
            e2e=True,
        )
    
        report = rasa.shared.utils.io.read_json_file(tmp_path / "TEDPolicy_report.json")
>       assert report["name"] == {
            "precision": 1.0,
            "recall": 1.0,
            "f1-score": 1.0,
            "support": 1,
            "confused_with": {},
        }
E       AssertionError: assert {'confused_wi...ll': 1.0, ...} == {'confused_wi...ll': 1.0, ...}
E         Omitting 3 identical items, use -vv to show
E         Differing items:
E         {'precision': 0.5} != {'precision': 1.0}
E         {'f1-score': 0.6666666666666666} != {'f1-score': 1.0}
E         Use -v to get the full diff
```

Examples:
- https://github.com/RasaHQ/rasa/pull/8346/checks?check_run_id=2277076543
- https://github.com/RasaHQ/rasa/runs/2220145266?check_suite_focus=true

**Comment by joejuzl** [comment] 2021-04-08 14:07
Duplicate of https://github.com/RasaHQ/rasa/issues/8256

**Closed by joejuzl** 2021-04-08 14:07 UTC
Labels: area:rasa-oss :ferris_wheel:, area:rasa-oss/model-testing, type:bug :bug:
