### ISSUE TITLE
Set up integration tests and identify problems with integrations

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#7746] opened 2021-01-17 16:45 UTC
**Description of Problem**:
We currently don't have integration tests in Rasa, and that means some of the very important components of Rasa that are used by customers (like brokers or channels) are not covered by tests at all. 

**Overview of the Solution**:
1. Talk to `Infrastructure` what their timeline is for setting up the job to run integration tests
2. Go through our issues & Sentry to identify problems with integrations (e.g. `TrackerStore`, `PikaBroker`, `RedisLockStore `, etc)
3. Create separate issues for problems identified in step 2

**Definition of Done**:
Separate issues for the identified problems, etc depending on the outcome of the investigation.

**Comment by TyDunn** [comment] 2021-02-08 10:26
@m-vdb Duplicate?

**Comment by m-vdb** [comment] 2021-02-08 10:41
Closing this one as duplicate of https://github.com/RasaHQ/rasa/issues/7680 ; given Enable prios for Q1, not the focus. We might do other iterations later.

**Closed by m-vdb** 2021-02-08 10:41 UTC
Labels: area:rasa-oss :ferris_wheel:, effort:enable-squad/2, type:maintenance :wrench:
