### ISSUE TITLE
Remote storage not working because of initial model validation

### ISSUE THREAD

**Issue by ypk46** [RasaHQ/rasa#3926] opened 2019-07-03 17:05 UTC
**Rasa version**: 1.1.4

**Rasa X version** (if used & relevant): Not installed

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows

**Issue**: Remote storage is not working on rasa cli. It seems like a model validation done on the `run` command is breaking the further validation which triggers both model server and remote storage. The method `_validate_model_path` creates the default directory (`models`) and set the `model_path` to the default value. This breaks the further validation in `agent.py` which defines how the model will be loaded, because by setting the default value and creating the directory the validation will always trigger **local mode**.

**Error (including full traceback)**:
```
2019-07-03 12:14:56 DEBUG    rasa.cli.run  - '20190703-152013' not found. Using default location 'models' instead.
2019-07-03 12:14:56 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2019-07-03 12:14:57 DEBUG    rasa.core.utils  - Available web server routes:

/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version

2019-07-03 12:14:57 INFO     root  - Starting Rasa Core server on http://localhost:5005
2019-07-03 12:14:57 INFO     root  - Enabling coroutine debugging. Loop id 140736552933768.
2019-07-03 12:14:57 DEBUG    root  - Could not load interpreter from 'models'   
2019-07-03 12:14:57 WARNING  rasa.core.agent  - Could not load local model in 'models'
```

**Command or request that led to error**:
```
rasa run --m 20190703-152013 --endpoints talk-endpoints.yml --enable-api --debug --remote-storage aws
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sdu-2044** [comment] 2019-07-04 09:42
same as my @3931

**Comment by akelad** [comment] 2019-07-05 12:21
Closing this because it seems to be a duplicate of #3931, let me know if that's not the case

**Closed by akelad** 2019-07-05 12:21 UTC
Labels: bug
