### ISSUE TITLE
cannot import name 'CompositionView' from 'sanic.views'

### ISSUE THREAD

**Issue by EgyptianM** [RasaHQ/rasa#10603] opened 2021-12-28 19:22 UTC
### Rasa Open Source version

3.0.4

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

ImportError: cannot import name 'CompositionView' from 'sanic.views' (d:\venv\lib\site-packages\sanic\views.py)

### Command / Request

```shell
rasa --version
```

### Relevant log output

```shell
(venv) D:\>rasa --version
Traceback (most recent call last):
  File "C:\Users\Original\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Original\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\venv\Scripts\rasa.exe\__main__.py", line 4, in <module>
  File "d:\venv\lib\site-packages\rasa\__main__.py", line 14, in <module>
    from rasa.cli import (
  File "d:\venv\lib\site-packages\rasa\cli\export.py", line 9, in <module>
    import rasa.core.utils
  File "d:\venv\lib\site-packages\rasa\core\utils.py", line 25, in <module>
    from sanic.views import CompositionView
ImportError: cannot import name 'CompositionView' from 'sanic.views' (d:\venv\lib\site-packages\sanic\views.py)
```

**Comment by sara-tagger** [comment] 2021-12-29 07:00
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment] 2021-12-29 10:20
This is a duplicate of https://github.com/RasaHQ/rasa/issues/10585. We're certainly well aware of the issue though. 

The fix, for now, is to update Sanic: 

```
pip install sanic==21.9.3
```

**Closed by koaning** 2021-12-29 10:20 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:

**Comment by KirtiGupta3101** [comment] 2022-04-21 09:02
Error: ImportError: cannot import name 'CompositionView' from 'sanic.views' (E:\Users\KIRTI\anaconda3\envs\rasa_en\lib\site-packages\sanic\views.py)
When I tried above solution i.e. :(rasa_en) E:\Users\rasa>pip install sanic==21.9.3
other Error that are comming is : ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sanic-plugins-framework 0.9.5 requires sanic<21,>=18.12.0, but you have sanic 21.9.3 which is incompatible.
rasa 2.8.13 requires sanic<20.12.0,>=19.12.2, but you have sanic 21.9.3 which is incompatible.
rasa 2.8.13 requires sanic-jwt<1.7.0,>=1.6.0, but you have sanic-jwt 1.7.0 which is incompatible.
rasa-sdk 2.8.4 requires sanic<21.0.0,>=19.12.2, but you have sanic 21.9.3 which is incompatible.
This version of sanic is incompatible and cause lot of of problem while running the assistant.
So what should I do now?
