### ISSUE TITLE
Rasa X model not properly working

### ISSUE THREAD

**Issue by aminekechaou** [RasaHQ/rasa#7873] opened 2021-02-02 17:47 UTC
**Rasa version**: 2.2.8

**Rasa SDK version** : 2.0.0

**Rasa X version**: 0.0.35

**Python version**: 3.8

**Issue**: Hi,

I deployed Rasa X using Helm Chart following the docs and connected it to the Git repo. It seems however that the chatbot doesn't work, whether using an uploaded model or training one after activating it. When I test it in Rasa X, it says that the predicted intent is equal to the message (e.g. if the message is "Hello" then the intent is "Hello" as well, although it doesn't exist as an intent). When querying via `/api/projects/default/logs` I would get something like this:

 {
 "id": 3,
 "time": 1612287061.5495345592,
 "model": "unavailable",
 "hash": "5d41402abc4b2a76b9719d911017c592",
 "conversation_id": null,
 "event_id": null,
 "user_input": {
 "text": "hello",
 "intent": 

 { "name": null, "confidence": 0 } 

,
 "intent_ranking": [],
 "entities": []
 },
 "tags": []
 }

I enabled debug mode (`debugMode: true` in values.yml) and I can see this being outputted frequently when looking at the logs using`kubectl logs -f rasa-x-1612275971-rasa-x-7947479b66-gshln --namespace rasa `

 GET [http://rasa-x-1612275971-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production?token=MY_TOKEN](http://rasa-x-1612275971-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production?token=MY_TOKEN) 404 160
 DEBUG:rasax.community.services.model_service:Model discovery not completed.

A similar thing is outputted on rasa-production:

 2021-02-02 17:35:48 DEBUG rasa.core.agent - Model server could not find a model at the requested endpoint 'http://rasa-x-1612275971-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production'. It's possible that no model has been trained, or that the requested tag hasn't been assigned.
 2021-02-02 17:35:48 DEBUG rasa.core.agent - No new model found at URL [http://rasa-x-1612275971-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production](http://rasa-x-1612275971-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production)

It seems as though the model is not active, although it clearly shows up in the UI as active.

Using Rasa X locally seems to work just fine with the same config and model. The model also trains fine using Rasa Open Source train command and Rasa X locally. Interestingly, when I train the model on Rasa X on server, the training only goes for a couple of epochs then fails.

**Comment by sara-tagger** [comment] 2021-02-03 07:00
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by desmarchris** [comment] 2021-02-03 18:49
hey @aminekechaou , can you post the response for hitting the `/projects/default/models` endpoint? I'm wondering if the tagging is not working appropriately. Also, what errors are you seeing when training fails?

**Comment by aminekechaou** [comment] 2021-02-03 23:00
I trained a model for 1 epoch and then called `/projects/default/models` Here's the same response before and after activating it. It's also the response I get after uploading a model (and activating it or not):
```
{
    "version": "0.35.0",
    "status": "failure",
    "message": "Could not save model.\nNo `model` file found.",
    "reason": "ModelSaveError",
    "details": {},
    "help": null,
    "code": 400
}
```

I then explicitly called `http://<address>/api/projects/default/models/<modelname>/tags/production` on the model I uploaded as noted here https://github.com/RasaHQ/rasa/issues/5819 and I get this response now when hitting `/projects/default/models`:

```
[
    {
        "hash": "d7c3ea58b66131a2a3c692b98230ea32",
        "model": "20210203-215432",
        "path": "/mnt/blob/models/20210203-215432.tar.gz",
        "project": "default",
        "trained_at": 1612389272.8615899086,
        "version": "2.2.8",
        "tags": [],
        "is_compatible": true
    },
    {
        "hash": "a540808fdd529e7756f038047b63d5c5",
        "model": "nlu-20210128-230311",
        "path": "/mnt/blob/models/nlu-20210128-230311.tar.gz",
        "project": "default",
        "trained_at": 1611874991.5235300064,
        "version": "2.2.8",
        "tags": [
            "production"
        ],
        "is_compatible": true
    }
]
```

But it still doesn't work as expected when testing the bot in the UI or calling /logs: 
```
{
    "id": 3,
    "time": 1612390065.029512167,
    "model": "unavailable",
    "hash": "5d41402abc4b2a76b9719d911017c592",
    "conversation_id": null,
    "event_id": null,
    "user_input": {
        "text": "hello",
        "intent": {
            "name": null,
            "confidence": 0
        },
        "intent_ranking": [],
        "entities": []
    },
    "tags": []
}
```

Here's what I get when calling ` /projects/default/models/tags/production`:

```
{
    "version": "0.35.0",
    "status": "failure",
    "message": "Tag 'production' not found for project 'default'.",
    "reason": "TagNotFound",
    "details": {},
    "help": null,
    "code": 404
}
```

It looked from the logs that that call was failing: 
`No new model found at URL http://rasa-x-1612344470-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production`


As to the training failing, I noticed that the training actually continues in the background but the UI shows "Training failed" when the computer goes to sleep. It would be helpful to create a placeholder each time training is triggered under the models tab and show a progress bar of the training that would persist even if the session is closed, along with giving the option to cancel it.

**Comment by desmarchris** [comment] 2021-02-03 23:22
thanks for the extra info! I'll get back to you after reviewing

**Comment by aminekechaou** [comment] 2021-02-15 09:59
It came to my attention that long complex passwords may cause issues in Rasa X. I changed to the passwords / tokens to only contain 8 characters and it seems to be working fine now. 

The issue with the UI saying that training the model failed when the computer goes to sleep still remains however.

**Comment by aminekechaou** [comment] 2021-02-22 20:07
Hi, it looks like it wasn't really related to the password's length, at least not directly. I'm having the same issue now with the same short passwords. 
Here's a further insight: 
```
curl --location --request GET 'http://rasa-x-1614022462-rasa-x.rasax.svc:5002/api/projects/default/models/tags/production' --header 'Authorization: Bearer RASA_X_TOKEN'
```
from within the production container returns `{"reasons":["Auth required."],"exception":"Unauthorized"} ` And the logs are always showing 
```

2021-02-22 19:49:21 DEBUG    rasa.core.agent  - Model server could not find a model at the requested endpoint 'http://rasa-x-1614022462-rasa-x.rasax.svc:5002/api/projects/default/models/tags/production'. It's possible that no model has been trained, or that the requested tag hasn't been assigned.
2021-02-22 19:49:21 DEBUG    rasa.core.agent  - No new model found at URL http://rasa-x-1614022462-rasa-x.rasax.svc:5002/api/projects/default/models/tags/production


```


@desmarchris is there any update on the issue?

**Comment by federicotdn** [comment] 2021-02-23 10:18
I have been unable to reproduce this problem for now.

What is the `GET /api/projects/default/models` endpoint returning?

Have you tried using the endpoint you mentioned using an API token? You can get your user's API token by contacting `GET /api/user` and looking for the `api_token` key.

**Comment by aminekechaou** [comment] 2021-02-23 10:39
`GET /api/projects/default/models` is returning the correct result

```
[
    {
        "hash": "774f8f45d0179da4d0e49f7ffa68d22b",
        "model": "20210223-095848",
        "path": "/app/models/20210223-095848.tar.gz",
        "project": "default",
        "trained_at": 1614074328.0844299793,
        "version": "2.3.0",
        "tags": [],
        "is_compatible": true
    },
    {
        "hash": "5d35f7b241b90634e9bdc0c30b08a502",
        "model": "20210223-095512",
        "path": "/app/models/20210223-095512.tar.gz",
        "project": "default",
        "trained_at": 1614074112.1912999153,
        "version": "2.3.0",
        "tags": [
            "production"
        ],
        "is_compatible": true
    }
]

```
`GET /api/projects/default/models/tags/production` is returning gibberish in this case (as if the response is not correctly encoded). In another case the call is failing.


`curl --request GET 'http://rasa-x-1614073869-rasa-x.rasax.svc:5002/api/user'` from within the prod container returns `{"reasons":["Authorization header not present."],"exception":"Unauthorized"}` and `curl --request GET 'http://rasa-x-1614073869-rasa-x.rasax.svc:5002/api/user' --header 'Authorization: Bearer RASAX_TOKEN'` returns `{"reasons":["Auth required."],"exception":"Unauthorized"}`

**Comment by federicotdn** [comment] 2021-03-01 13:45
Thanks for the additional information. Unfortunately so far I haven't been able to reproduce the problem.  I am transferring the issue to another team that follows model lifecycles more closely.

**Comment by Smirl** [comment] 2021-03-19 15:28
Hello. Any update or workaround for this? I am using rasa `1.10.8` and rasa-x `0.31.0`. I get the same as @aminekechaou where the API returns the models with the tags from `GET /api/projects/default/models` but not from `GET /api/projects/default/models/tags/production`.

**Comment by josesolis2201** [comment] 2021-08-18 00:06
I am facing this issue in rasa 2.8.1, rasa-x 0.42.0. It started happening randomly and now I can't get it to work. Nothing has changed from when it worked to now. 
When hitting the endpoint api/projects/default/models I get this:
```
[{"hash":"cdda3350bde594061531191f10f5590a",
"model":"20210817-233608",
"path":"\/app\/models\/20210817-233608.tar.gz",
"project":"default",
"trained_at":1629243368.0236799717,
"version":"2.8.1",
"tags":["production"],
"is_compatible":true}]
```
but when hitting /api/projects/default/models/tags/production I get:
```
{"version":"0.42.0",
"status":"failure",
"message":"Tag 'production' not found for project 'default'.",
"reason":"TagNotFound",
"details":{},
"help":null,"code":404}
```
The logs show the same as comments above:
```
2021-08-18 00:05:12 DEBUG    rasa.core.agent  - Model server could not find a model at the requested endpoint 'http://k8s-rasa-rasa-x-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production'. It's possible that no model has been trained, or that the requested tag hasn't been assigned.

2021-08-18 00:05:12 DEBUG    rasa.core.agent  - No new model found at URL http://k8s-rasa-rasa-x-rasa-x.rasa.svc:5002/api/projects/default/models/tags/production
```

**Comment by provwilliamnagy** [comment] 2021-08-24 14:55
I'm experiencing the same issue.  Interesting, when I try to retrieve my model directly via `/api/projects/default/models/20210823-181338`, I get 

`{
    "version": "0.42.0",
    "status": "failure",
    "message": "Model 'None' not found for project 'default'.",
    "reason": "ModelNotFound",
    "details": {},
    "help": null,
    "code": 404
}` even though I see the model there when I do a `/api/projects/default/models`

**Comment by fbskp** [comment] 2021-11-09 09:21
I've experienced the same issue on a single-node k8s cluster. Redeploying the rasa-x pod helps temporarily as mentioned by @provwilliamnagy. 
I noticed this issue first when the cluster was under some load (running other deployments as well), causing the pods to take more time to start. So maybe that points indeed to a timing issue. 

Versions: rasa: 2.8.12 / rasa-x: 0.42.4

**Comment by juanmav** [comment] 2022-03-08 18:34
Hi,

Is there any update on this? I configured Rasa Core to pull models from Rasa X and this doesn't work as well. It seems Rasa Core doesn't use the token value.

endpoints.yml (from docker-compose installation manual)
`
 models:
   url: ${RASA_MODEL_SERVER}
   token: ${RASA_X_TOKEN}
   wait_time_between_pulls: ${RASA_MODEL_PULL_INTERVAL}
`

I checked the code and the headers of the request are not being created.

https://github.com/RasaHQ/rasa/blob/2.8.12/rasa/core/agent.py#L189

**Comment by alexweidauer** [comment] 2022-06-08 12:15
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.

**Closed by alexweidauer** 2022-06-08 12:15 UTC
Labels: area:rasa-x/backend :tophat:, priority:high
