### ISSUE TITLE
ComponentNotFoundException: Failed to load the component 'EntityExtractor'. Cannot find class 'EntityExtractor' in global namespace. Please check that there is no typo in the class name and that you have imported the class into the global namespace. Either your pipeline configuration contains an error or the module you are trying to import is broken

### ISSUE THREAD

**Issue by Gourav-infobiz** [RasaHQ/rasa#8384] opened 2021-04-07 13:54 UTC
**Rasa version**: 2.4.0

**Rasa SDK version** (if used & relevant):2.4.1

**Python version**: 3.7.0

**Operating system** (windows, osx, ...):windows

**Issue**: ComponentNotFoundException: Failed to load the component 'EntityExtractor'. Cannot find class 'EntityExtractor' in global namespace. Please check that there is no typo in the class name and that you have imported the class into the global namespace. Either your pipeline configuration contains an error or the module you are trying to import is broken (e.g. the module is trying to import a package that is not installed). Traceback (most recent call last):
  
ImportError: Cannot retrieve class from path EntityExtractor.

**Error (including full traceback)**:

**Content of configuration file (config.yml)** (if relevant):
```# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: EntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: TEDPolicy
    max_history: 3
    epochs: 200
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.4
    fallback_action_name : "action_Custom_fallback"


```

![image](https://user-images.githubusercontent.com/70999585/113877993-d490ff80-97d6-11eb-8c24-3eb71a065ea0.png)

**Comment by Gourav-infobiz** [comment] 2021-04-07 13:55
@Sara-tagger @tjpalmer @sheldon @fungiboletus

**Comment by sara-tagger** [comment] 2021-04-08 06:00
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by amn41** [comment] 2021-04-08 19:09
hi @Gourav-infobiz  - this looks like a typo on your config file. There is no component called `EntityExtractor` - you have to specify one of the existing entity extractors, see [here](https://rasa.com/docs/rasa/components#entity-extractors) . I'm going to close this issue because it's not a bug or feature request, but if you still have trouble do please post on our forum: forum.rasa.com

**Closed by amn41** 2021-04-08 19:09 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
