### ISSUE TITLE
Forms with Dynamic `required_slots` and slot Mappings in RC02

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10261] opened 2021-11-17 10:47 UTC
I wonder if the form described in [this youtube tutorial](https://www.youtube.com/watch?v=md97kXT27Y0&list=PL75e0qA87dlHogEVKnBJLhqyaZKDg2f0W&index=10) is no longer compatible in Rasa 3.0. 

I had this form that would add a slot if a name appeared that we believe is spelled incorrectly. 

```python
import yaml 
import pathlib 
from typing import Text, List, Any, Dict, Optional

from rasa_sdk import Tracker, FormValidationAction
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.types import DomainDict

names = pathlib.Path("data/names.txt").read_text().split("\n")


class ValidateNameForm(FormValidationAction):
    def name(self) -> Text:
        return "validate_name_form"
    
    async def required_slots(
        self,
        slots_mapped_in_domain: List[Text],
        dispatcher: "CollectingDispatcher",
        tracker: "Tracker",
        domain: "DomainDict",
    ) -> Optional[List[Text]]:
        first_name = tracker.slots.get("first_name")
        if first_name is not None:
            if first_name not in names:
                return ["name_spelled_correctly"] + slots_mapped_in_domain
        return slots_mapped_in_domain

    async def extract_name_spelled_correctly(
        self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
    ) -> Dict[Text, Any]:
        intent = tracker.get_intent_of_latest_message()
        return {"name_spelled_correctly": intent == "affirm"}
```

The reasoning here is that I would *only* ask about the spelling of the name if there was a reason to ask for it. That's why the user isn't bothered with extra questions. That's why the slot was dynamically added here. Is such a pattern possible now that we have predefined slot mappings? It feels like I cannot use this dynamic trick anymore.

**Comment by ancalita** [comment] 2021-11-17 13:26
@koaning There's one change in `FormValidationAction.required_slots()` method: the `slots_mapped_in_domain` argument was removed and replaced with `domain_slots`, could you please edit your `actions.py`, retry and post any errors you're seeing. Dynamic form behaviour should work in rc2 🤞🏼 after fixing this issue in this PR: https://github.com/RasaHQ/rasa/pull/10175

**Comment by koaning** [comment] 2021-11-17 15:36
Mostly a check: is this change documented in the migration guide? I could be wrong, but I don't recall reading about it.

**Comment by ancalita** [comment] 2021-11-17 15:47
Yup, I've added in the PR for slot mappings update (right at the bottom of the migration guide), not yet merged: https://github.com/RasaHQ/rasa/pull/10011/files

**Comment by m-vdb** [comment] 2021-11-18 08:41
@koaning do you think you could have a try at checking this issue this morning? It'd be great to know if there is an issue or not before the next RC, which is scheduled today mid-day :)

**Comment by koaning** [comment] 2021-11-18 09:40
Sure. I'll check it from `main` right away.

**Comment by koaning** [comment] 2021-11-18 10:01
I fear the bug still persists. I'm available for a call if need be.

**Comment by ancalita** [comment] 2021-11-19 09:41
@koaning @m-vdb To document my findings from exploring this issue yesterday:

1. The slot `name_spelled_correctly` gets set to either `True` or `False` immediately after the user utterance to the `first_name` slot request (while the form is active), because this user utterance gets classified as either `affirm` or `deny`. And the default action `action_extract_slots` reads the mappings of `name_spelled_correctly` as valid for slot setting because these mappings are not restricted to any form conditions.
2. The quick fix I implemented in the `validate_first_name` method of `FormValidationAction` was to reset `name_spelled_correctly` back to `None` so that this slot `name_spelled_correctly` can get asked correctly by the form as intended:
```
    def validate_first_name(
        self,
        slot_value: Any,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: DomainDict,
    ) -> Dict[Text, Any]:
        """Validate `first_name` value."""
        # If the name is super short, it might be wrong.
        print(f"First name given = {slot_value} length = {len(slot_value)}")
        if len(slot_value) <= 1:
            dispatcher.utter_message(text=f"That's a very short name. I'm assuming you mis-spelled.")
            return {"first_name": None, "name_spelled_correctly": None}
        else:
            return {"first_name": slot_value, "name_spelled_correctly": None}
```
To also add that in this solution the repo was slightly modified, meaning the `name_spelled_correctly` has predefined slot mappings instead of custom, and the `extract` method from the issue description was modified into a `validate_name_spelled_correctly` method.

@koaning let me know if i can close this issue?
The dynamically requested slot is no longer a problem with the fix described above.

**Comment by m-vdb** [comment] 2021-11-19 09:44
> because this user utterance gets classified as either affirm or deny.

as far as I understand the problem, this seems like the root cause and like we wouldn't want this to happen? Is this intent misclassification due to wrong training data / wrong config and has nothing to do with slot mappings?

**Comment by koaning** [comment] 2021-11-19 10:50
I'm satisfied with the solution, my only remaining concern is that this still seems like behavior that's different than in Rasa 2.x. This suggests we may want to warn folks in the migration guide if they use the `required_slots` feature that they may need to double-check the behavior.

**Comment by ancalita** [comment] 2021-11-19 11:40
> Is this intent misclassification due to wrong training data / wrong config and has nothing to do with slot mappings?

The nlu training data in the repo indeed doesn't have an intent defined + examples for when a name is given in an user utterance, so yes that could be a problem, however I haven't followed that route especially that I remembered Akela saying that not all utterances containing information given to the bot have their own intents which is why `from_text` mapping gets used most often.

> this still seems like behavior that's different than in Rasa 2.x
Yes, `action_extract_slots` does not have the same extraction behaviour as forms in 2.x, because there's no `asking` of slots in the default action, it runs through all slots and their mappings to check if any mapping is applicable with information gathered from latest `UserUttered`. 

> we may want to warn folks in the migration guide
I'll have a think of how I'll phrase this, maybe as a caution note to double-check behaviour when `FormValidationAction` is used and then link it to the default action page, I'll see if that section may also need improving?
Could you please submit a tiny docs issue for this @koaning ?

**Closed** 2021-11-19 13:01 UTC
Labels: priority:normal, area:rasa-oss/forms, feature:3.0/slot-mappings, 3.0.0rc-QA-issue
