### ISSUE TITLE
Rasa X: Long conversations make Conversations tab unusable

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#4768] opened 2019-11-13 18:30 UTC
## Description of Problem

Rasa X shows the entire conversation history with a user, which makes the Conversations tab so slow that it is unusable.

Filters do not help because they filter based on the conversation start date rather than on recent activity within a conversation.

## Overview of the Solution

Don't load the data until it's needed.

1.  Load only the most recent 20-50 turns in the conversation
2.  Load additional turns as user scrolls up

Filter based on recent activity. For example, "Today" should mean conversations that had activity today, not conversations that started today.

## Examples

See screencast of problem in action: [https://www.dropbox.com/s/p7bm6ya258npxet/screen%20recording%202019-11-13%20at%2010.18.23%20am.mov?dl=0](https://www.dropbox.com/s/p7bm6ya258npxet/screen%20recording%202019-11-13%20at%2010.18.23%20am.mov?dl=0)

## Definition of Done

1.  When I click to view a conversation in the "Conversations" tab: 
      1.  It appears almost instantly
    2.  It is already scrolled to the bottom, showing the last thing that happened in the conversation
    3.  I scroll up to view the history, and it scrolls and renders instantly

This isn't as important, but I'd also suggest:

1.  Conversations are sorted and timestamped by recent activity.
2.  Filters filter by recent activity

**Comment by sara-tagger** [comment] 2019-11-14 07:00
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by kapoorh** [comment] 2019-12-19 10:06
Hi,

Same issue I am facing this. If the filter works properly on conversation page then it will very easy to train bot for unanswered questions.

Any idea when will we get the resolution of this issue?

Thanks and Regards
Harsh

**Comment by eibhleag** [comment] 2019-12-19 11:14
Hi folks 🙂

We've looked at a number of ways to improve performance on the Conversations screen. A couple of them are ready to ship in the New Year with Rasa X 0.24, and we're keeping a close eye on whether there's still more that we can do to improve on that.

**Comment by kapoorh** [comment] 2019-12-19 14:26
That's cool @eibhleag !! Thanks for an update.

**Comment by kapoorh** [comment] 2020-02-04 06:54
Hi @eibhleag ,

Any update on this? Has this issue been resolved?

Thanks and Regards
Harsh

**Comment by eibhleag** [comment] 2020-02-04 09:37
Hi @kapoorh 

As of 0.24 (2020/01/07) long conversations should be smoother to interact with (quicker initial layout, smoother scrolling, etc) due to a couple of rendering changes.

In 0.25 (landing shortly) the initial load time of those conversations (and collections of conversations containing them) should also be reduced - this will include the load time when filters are applied.

Hope those updates help - if not, it'd be great to know what behaviour you're seeing in the application, when any slowness appears, etc.

Thanks!

**Comment by kapoorh** [comment] 2020-02-04 11:26
Thanks @eibhleag 

I will update you once you release 0.25 version which should be compatible with rasa 1.7.

Thanks and Regards
Harsh

**Comment by eibhleag** [comment] 2020-02-05 17:49
@kapoorh 0.25 was just released - per #5163 it's compatible with Rasa 1.7 as well 🙂

**Comment by tangochris** [comment] 2020-04-22 23:20
@eibhleag Just an update — as of 0.26.0 and 1.8.0, the Conversations tab is still unusable for us. The scrolling/navigating continues to be very slow, but the larger problem is that new conversations do not record. Although the bot is in production and being used constantly, the last recorded conversation was March 4.

**Comment by wochinge** [comment] 2021-01-29 10:33
We are currently addressing this. Related to https://github.com/RasaHQ/rasa-x/issues/3921

**Comment by yennycheung** [comment] 2021-04-28 15:08
@TyDunn, a bunch of PRs linked here are close, is this still an issue?

**Comment by TyDunn** [comment] 2021-04-28 15:55
@yennycheung We have improved this over time, but we should ensure we are measuring it consistently and know what the limits are

**Comment by yennycheung** [comment] 2021-04-28 16:01
@TyDunn , thank you. Got it, so it's probably a duplicate of https://www.notion.so/rasa/Conversation-inbox-scalability-1398f4e85a6d4b52b549ecb219a73394

**Comment by TyDunn** [comment] 2021-04-29 09:48
Yeah, it's community reported examples of this problem

**Comment by alexweidauer** [comment] 2022-06-08 12:11
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.

**Closed by alexweidauer** 2022-06-08 12:11 UTC
Labels: type:enhancement :sparkles:, area:rasa-x/backend :tophat:, area:rasa-x/ui :sparkles:
