### ISSUE TITLE
rasa train - model not saved

### ISSUE THREAD

**Issue by tomgrassmann** [RasaHQ/rasa#3405] opened 2019-05-08 13:45 UTC
**Rasa version**:

rasa                    1.0.0a5   /usr/src/rasa/rasa_nlu
rasa-core               0.14.2
rasa-core-sdk           1.0.0a1   /usr/src/rasa/rasa_core_sdk
rasa-nlu                0.15.0

**Python version**: 
Python 3.6.5

**Operating system** (windows, osx, ...):
Ubuntu 16.04 LTS

**Issue**:
After training with command "rasa train", following exception occurs and the model
won't get saved

``` Epoch 148/150
    5622/5622 [==============================] - 3s 588us/sample - loss: 0.0154 - acc: 0.9913
    Epoch 149/150
    5622/5622 [==============================] - 3s 589us/sample - loss: 0.0160 - acc: 0.9913
    Epoch 150/150
    5622/5622 [==============================] - 3s 616us/sample - loss: 0.0140 - acc: 0.9920
    2019-05-08 15:35:59 INFO     rasa.core.policies.keras_policy  - Done fitting keras policy model
    Processed trackers: 100%|███████| 52/52 [00:00<00:00, 205.09it/s, # actions=585]
    Processed actions: 0it [00:00, ?it/s, # examples=212]Traceback (most recent call last):
      File "/usr/local/bin/rasa", line 11, in <module>
        load_entry_point('rasa', 'console_scripts', 'rasa')()
      File "/usr/src/rasa/rasa_nlu/rasa/__main__.py", line 68, in main
        cmdline_arguments.func(cmdline_arguments)
      File "/usr/src/rasa/rasa_nlu/rasa/cli/train.py", line 124, in train
        extract_additional_arguments(args),
      File "/usr/src/rasa/rasa_nlu/rasa/train.py", line 37, in train
        train_async(domain, config, training_files, output, force_training, kwargs)
      File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
      File "/usr/src/rasa/rasa_nlu/rasa/train.py", line 111, in train_async
        domain, config, story_directory, output, train_path, kwargs
      File "/usr/src/rasa/rasa_nlu/rasa/train.py", line 200, in train_core_async
        kwargs=kwargs,
      File "/usr/src/rasa/rasa_nlu/rasa/core/train.py", line 97, in train
        agent.train(training_data, **kwargs)
      File "/usr/src/rasa/rasa_nlu/rasa/core/agent.py", line 657, in train
        self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
      File "/usr/src/rasa/rasa_nlu/rasa/core/policies/ensemble.py", line 90, in train
        policy.train(training_trackers, domain, **kwargs)
      File "/usr/src/rasa/rasa_nlu/rasa/core/policies/memoization.py", line 157, in train
        self._add_states_to_lookup(trackers_as_states, trackers_as_actions, domain)
      File "/usr/src/rasa/rasa_nlu/rasa/core/policies/memoization.py", line 111, in _add_states_to_lookup
        if online:
    NameError: name 'online' is not defined
```

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/nlu/components/
language: de
pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SklearnIntentClassifier"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"


# Configuration for Rasa Core.
# https://rasa.com/docs/core/policies
policies:
  - name: KerasPolicy
    epochs: 150
    max_history: 15
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 15
  - name: FormPolicy

```

**Comment by akelad** [comment] 2019-05-09 14:39
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment] 2019-05-09 14:47
@tomgrassmann The issue is already fixed on the master branch.

**Comment by akelad** [comment] 2019-05-10 15:56
will close this then

**Closed by akelad** 2019-05-10 15:56 UTC
