### ISSUE TITLE
Inconsistent behavior with FormPolicy in submit() function when dispatching utterance

### ISSUE THREAD

**Issue by leondroidgeeks** [RasaHQ/rasa#6063] opened 2020-06-25 10:42 UTC
**Rasa version**: 1.10.0

**Rasa X version** (if used & relevant): 0.29.1

**Python version**: 2.7.17

**Operating system** (windows, osx, ...): linux, docker

**issue**:
Exploring the FormPolicy with CustomMappings and dispatching utterances with slots that were collected by the form, I think I found a bug where slots are not picked up by the template that is dispatched.
I already made two posts about this one at the forum, please have a look at them:
https://forum.rasa.com/t/custom-slot-mapping-is-producing-none-value/30624
https://forum.rasa.com/t/slots-get-filled-twice-in-formaction/13660/18?u=leondroidgeeks

**Comment by sara-tagger** [comment] 2020-06-25 12:00
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment] 2020-06-25 12:33
Closing as a duplicate of https://github.com/RasaHQ/rasa-sdk/issues/167

**Closed by erohmensing** 2020-06-25 12:33 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
