### ISSUE TITLE
Bert model with AlbertTokenizer problem

### ISSUE THREAD

**Issue by ganbaaelmer** [RasaHQ/rasa#10584] opened 2021-12-27 03:17 UTC
### Rasa Open Source version

2.8.16

### Rasa SDK version

2.8.3

### Rasa X version

0.42.6

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

the error came from a HF model using a different tokenizer  (e.g. BertModel with AlbertTokenizer), breaks due to the hard coded mapping in registry.py.

https://forum.rasa.com/t/how-to-import-huggingface-models-to-rasa/50238

**Comment by sara-tagger** [comment] 2021-12-27 07:00
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ganbaaelmer** [comment] 2021-12-28 02:08
@aeshky please help us

**Comment by mleimeister** [comment] 2022-01-07 15:41
This is not a bug but rather a known limitation of the current implementation. The documentation has been updated to clarify which models work with the current version of `LanguageModelFeaturizer` here: https://github.com/RasaHQ/rasa/issues/10385
Exploratory work on how it can be improved and allow loading arbitrary models is already happening (https://github.com/RasaHQ/rasa/issues/6307, https://github.com/RasaHQ/rasa/pull/10624), therefore this ticket could be closed imo.

**Comment by aeshky** [comment] 2022-01-10 13:19
Thanks for looking into this @mleimeister. I'm closing this issue based on your comment.

**Closed by aeshky** 2022-01-10 13:19 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:

**Comment by mleimeister** [comment] 2022-01-10 13:23
@ganbaaelmer Please follow [this ticket](https://github.com/RasaHQ/rasa/issues/6307) for further updates on the progress.
