### ISSUE TITLE
dynamodb bug 

### ISSUE THREAD

**Issue by kawtarZ** [RasaHQ/rasa#5417] opened 2020-03-12 16:50 UTC
**Rasa version**: 1.7.4

**Rasa SDK version**  1.7.0

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Windows

**Issue**: **similar to the issue [#5215](https://github.com/RasaHQ/rasa/issues/5215)**

We are currenlty using the DynamoDB tracker store, and in all the custom actions we get the following error : 

``` 
2020-03-12 17:41:56 DEBUG    rasa.core.processor  - Object of type Decimal is not JSON serializable
Traceback (most recent call last):
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\site-packages\rasa\core\processor.py", line 597, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\site-packages\rasa\core\actions\action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\site-packages\rasa\utils\endpoints.py", line 146, in request
    **kwargs,
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\site-packages\aiohttp\client.py", line 365, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\site-packages\aiohttp\payload.py", line 389, in __init__
    dumps(value).encode(encoding),
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\saskour\appdata\local\programs\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable

```

The source of this bug is the Decimal values returned by the tracker, as DynamoDB has this behavior of converting int/float/timestamp data types into Decimal, which not "jsonifiable" .
 
the workaround we did as a temporary solution is to add a static method in the class **RemoteAction in rasa/core/actions/actions.py** that convert all the Decimal values returned by the tracker into strings.

**Comment by erohmensing** [comment] 2020-03-12 17:26
@rgstephens have you seen this before?

**Comment by rgstephens** [comment] 2020-03-12 21:27
Yes, this is a duplicate of #5215. Closing.

**Closed by rgstephens** 2020-03-12 21:27 UTC
Labels: type:bug :bug:
