### ISSUE TITLE
Rasa1.7.1 segmentation fault(core dumped)

### ISSUE THREAD

**Issue by gitpranjal** [RasaHQ/rasa#5228] opened 2020-02-12 09:50 UTC
**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
1.7.1

**Python version**:
3.6.8

**Operating system** (windows, osx, ...):
Ubuntu18.04LTS

**Issue**:
Segmentation fault(core dumped) upon attempting to training the rasa core model

**Error (including full traceback)**:
```
Segmentation fault (core dumped)
```

**Command or request that led to error**:
```
rasa train -c config_bluekaktus_-_manufacturing.yml --out models

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
- name: "SpacyNLP"
  case_sensitive: false
- name: "SpacyTokenizer"
- name: "CountVectorsFeaturizer"
  analyzer: 'word'
  min_ngram: 1
  max_ngram: 3
  lowercase: true
  OOV_token: oov
  return_sequence: true
- name: "SpacyFeaturizer"
  return_sequence: true
- name: "RegexFeaturizer"
  return_sequence: true
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "EmbeddingIntentClassifier"
  loss_type: "margin"
- name: "ResponseSelector"
- name: "retrieval_action_fallback.ResponseThreshold"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "MemoizationPolicy"
    max_history: 81
  - name: "KerasPolicy"
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 81
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: "MappingPolicy"
  - name: "FormPolicy"
  - name: "FallbackPolicy"
    nlu_threshold: 0.6
    core_threshold: 0.3
    fallback_action_name: "action_default_fallback"


importers:
- name: "RasaFileImporter"
- name: "my_training_data_importer.MyImporter"
  project_name: "bluekaktus_-_manufacturing"
```

**Content of domain file (domain.yml)** (if relevant):
```yml

**Comment by sara-tagger** [comment] 2020-02-12 13:00
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment] 2020-02-12 15:15
@gitpranjal is this thread helpful at all? https://github.com/RasaHQ/rasa/issues/5196

**Comment by gitpranjal** [comment] 2020-02-13 05:15
Yes, that worked. Uninstalling gym and reinstalling a previous version solved the issue.
pip uninstall gym
pip install gym==0.15.4

And then it worked. Thanks!

**Comment by erohmensing** [comment] 2020-02-13 09:06
Got it. Yeah, the segmentation fault seems to only happen on Ubuntu based on the issues i've seen. 

The rest seems like just a general memory error how much memory does your machine have?

**Comment by benos** [comment] 2020-02-16 19:43
I have the same problem when using the Docker images.

With this image, training works fine:
FROM rasa/rasa:1.7.0-spacy-en

With these, core training fails: (Segmentation fault right at the beginning of training core).
FROM rasa/rasa:1.7.1-spacy-en
FROM rasa/rasa:1.7.2-spacy-en

Tried boosting the RAM of Docker to 6GB with a 4GB swap but to no avail. Also, the failure happens at the exact same point regardless of the amount of RAM.

**Comment by wochinge** [comment] 2020-02-17 10:10
Thanks @benos That made it really easy to reproduce for me. I'll have a look

**Comment by wochinge** [comment] 2020-02-17 10:12
Using `python -q -X faulthandler` I get this stack trace
```
Training Core model...
Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1316.98it/s, # trackers=1]
Fatal Python error: Segmentation fault

Thread 0x00007fb7ca23d740 (most recent call first):
  File "/build/lib/python3.6/site-packages/rasa/core/utils.py", line 73 in subsample_array
  File "/build/lib/python3.6/site-packages/rasa/core/training/generator.py", line 482 in _create_start_trackers_for_augmentation
  File "/build/lib/python3.6/site-packages/rasa/core/training/generator.py", line 374 in generate
  File "/build/lib/python3.6/site-packages/rasa/core/training/__init__.py", line 69 in load_data
  File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 672 in load_data
  File "/build/lib/python3.6/site-packages/rasa/core/train.py", line 65 in train
  File "/build/lib/python3.6/site-packages/rasa/train.py", line 361 in _train_core_with_validated_data
  File "/build/lib/python3.6/site-packages/rasa/train.py", line 223 in _do_training
  File "/build/lib/python3.6/site-packages/rasa/train.py", line 188 in _train_async_internal
  File "/build/lib/python3.6/site-packages/rasa/train.py", line 101 in train_async
  File "/build/lib/python3.6/site-packages/rasa/train.py", line 50 in train
  File "/build/lib/python3.6/site-packages/rasa/cli/train.py", line 76 in train
  File "/build/lib/python3.6/site-packages/rasa/__main__.py", line 76 in main
  File "/build/lib/python3.6/site-packages/rasa/__main__.py", line 87 in <module>
  File "/usr/local/lib/python3.6/runpy.py", line 85 in _run_code
  File "/usr/local/lib/python3.6/runpy.py", line 193 in _run_module_as_main
Segmentation fault
```

**Comment by wochinge** [comment] 2020-02-17 10:19
`pip install gym==0.15.4` fixes it @erohmensing . Thanks for the pointer 👍

**Comment by wochinge** [comment] 2020-02-17 10:55
I suggest pinning this to <=0.15.4. Research is removing the `gym` dependency with TF2.0 (cc @dakshvar22 )

**Comment by wochinge** [comment] 2020-02-17 14:11
i'm fixing the segmentation fault with https://github.com/RasaHQ/rasa/pull/5248 . 

@gitpranjal How much memory has your machine?

**Comment by gitpranjal** [comment] 2020-02-17 14:12
I have got 16 GB ram, Ubuntu 18.04 OS

**Comment by wochinge** [comment] 2020-02-17 14:14
And how much memory is consumed? Can you please monitor the memory consumption during the training with a tool like `htop` or similar

**Comment by gitpranjal** [comment] 2020-02-18 06:18
[image: Screenshot from 2020-02-18 11-31-26.png]
[image: Screenshot from 2020-02-18 11-31-58.png]
[image: Screenshot from 2020-02-18 11-32-00.png]
[image: Screenshot from 2020-02-18 11-31-47.png]
[image: Screenshot from 2020-02-18 11-29-57.png]

In my config.yml file, max history is set to 251. It is getting killed at
even 181

**Comment by wochinge** [comment] 2020-02-19 08:56
> In my config.yml file, max history is set to 251. It is getting killed at

This is a very very very large `max_history`. Any specific reason to set it that hight? Can you maybe give it a try with something in the range 3-10?

**Comment by gitpranjal** [comment] 2020-02-20 07:33
Yes, the stories are very long with a lot of slot filling and buttons being
clicked giving multiple cases. On reducing the max_history below 180,
stories are not followed properly.

**Comment by wochinge** [comment] 2020-02-20 08:36
I don't know your use case / story structure, but I would argue that this seems like an issue with the stories. I talked to a couple of colleagues and nobody has ever seen a `max_history` settings even close to it. I'm closing this issue since the segmentation fault is fixed and the `max_history` problem is a different thing. However, feel free to continue our discussion in here or in the [Rasa Forum](https://forum.rasa.com)

**Closed by wochinge** 2020-02-20 08:36 UTC
Labels: area:Rasa Open Source, type:bug :bug:
