### ISSUE TITLE
There is not a proper method to pass a parameter of max_event_history to DialogueStateTracker

### ISSUE THREAD

**Issue by ghostHBL** [RasaHQ/rasa#4101] opened 2019-07-25 00:45 UTC
**Description of Problem**:

When pass a message to Agent, Agent pass the message to MessageProcessor, MessageProcessor will get or create a tracker for the sender id first.
```
class MessageProcessor(object):
    ...
    def _get_tracker(self, sender_id: Text) -> Optional[DialogueStateTracker]:
        sender_id = sender_id or UserMessage.DEFAULT_SENDER_ID
        return self.tracker_store.get_or_create_tracker(sender_id)
```
But it doesn't pass a parameter of max_event_history to the tracker store, tracker store will always pass  max_event_history  as None to DialogueStateTracker. The deque of events in DialogueStateTracker will be very larger after a long dialogue with a sender id, the application will be slower and slower since it take longer and longer time to serialise and deserialise the tracker.
```
class TrackerStore(object):
    def __init__(
        self, domain: Optional[Domain], event_broker: Optional[EventChannel] = None
    ) -> None:
        self.domain = domain
        self.event_broker = event_broker
        self.max_event_history = None
    ....

    def get_or_create_tracker(self, sender_id, max_event_history=None):
        tracker = self.retrieve(sender_id)
        self.max_event_history = max_event_history
        if tracker is None:
            tracker = self.create_tracker(sender_id)
        return tracker

    def init_tracker(self, sender_id):
        if self.domain:
            return DialogueStateTracker(
                sender_id, self.domain.slots, max_event_history=self.max_event_history
            )
        else:
            return None

    def create_tracker(self, sender_id, append_action_listen=True):
        """Creates a new tracker for the sender_id.

        The tracker is initially listening."""

        tracker = self.init_tracker(sender_id)
        if tracker:
            if append_action_listen:
                tracker.update(ActionExecuted(ACTION_LISTEN_NAME))
            self.save(tracker)
        return tracker
```
**Overview of the Solution**:

We need a proper method to pass a parameter of max_event_history to DialogueStateTracker, maybe we can pass a max_event_history to TrackerStore when init it, and don't modify it when call method of get_or_create_tracker. Just like the suggestion of #2661

**Comment by msamogh** [comment] 2019-07-25 06:48
Thanks for raising this issue, @wochinge will get back to you about it soon.

**Comment by wochinge** [comment] 2019-07-25 09:16
@ghostHBL Thanks for proposing this solution. However, I close it since it's a duplicate of https://github.com/RasaHQ/rasa/issues/3011 . Could you add your comments there?

**Closed by wochinge** 2019-07-25 09:16 UTC
Labels: enhancement
