### ISSUE TITLE
HFTransformersNLP add param from_pt to support customer pytorch model

### ISSUE THREAD

**Issue by Timooooooo** [RasaHQ/rasa#6181] opened 2020-07-10 02:05 UTC
**Description of Problem**:

today i want to use chinese_wwm_ext_L-12_H-768_A-12 model in my project in pipeline HFTransformersNLP ,but it crashed with "OSError: Unable to load weights from h5 file. If you tried to load a TF 2.0 model from a PyTorch checkpoint, please set from_pt=True."
**Overview of the Solution**:

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment] 2020-07-10 06:00
Thanks for submitting this feature request 🚀 @wochinge will get back to you about it soon! ✨

**Comment by wochinge** [comment] 2020-07-10 07:10
@dakshvar22 Can you please take this one over?

**Comment by dakshvar22** [comment] 2020-07-10 09:16
@Timooooooo `from_pt=True` parameter is intentionally kept out because we don't support pytorch backend yet in order to keep the package lean. I would recommend you to convert the pytorch checkpoint to tensorflow checkpoint and then use them. Please refer to this [thread](https://github.com/RasaHQ/rasa/issues/6071) if you need more info on how to do it.
Closing this issue as it is a duplicate of the linked thread as well.

**Closed by dakshvar22** 2020-07-10 09:16 UTC
Labels: area:rasa-oss :ferris_wheel:, type:enhancement :sparkles:

**Comment by hei-my** [comment] 2021-03-31 10:21
> **Description of Problem**:
> 
> today i want to use chinese_wwm_ext_L-12_H-768_A-12 model in my project in pipeline HFTransformersNLP ,but it crashed with "OSError: Unable to load weights from h5 file. If you tried to load a TF 2.0 model from a PyTorch checkpoint, please set from_pt=True."
> **Overview of the Solution**:
> 
> **Examples** (if relevant):
> 
> **Blockers** (if relevant):
> 
> **Definition of Done**:

你好，请问下你使用中文bert训练的config.xml配置可以参考一下嘛？我弄的HFTransformersNLP配置识别不出来实体，谢谢
