### ISSUE TITLE
Entity Values are not used in training

### ISSUE THREAD

**Issue by skier233** [RasaHQ/rasa#11312] opened 2022-07-09 22:35 UTC
### Rasa Open Source version

3.2.1

### Python version

3.9

### What operating system are you using?

Windows

### What happened?

From my testing and from looking at some forum posts on the rasa forums, I've discovered that it appears entity values do not get used in training (only perhaps if there are any entities). Instead, you have to map the entities to a slot and then check the value of the slot. This is annoying to do and leads to a lot of useless extra slots. The documentation on the wiki heavily suggests that entity values should in fact affect the next action: https://rasa.com/docs/rasa/training-data-format/#user-messages
stories:
- story: story with entities
  steps:
  - intent: account_balance
    entities:
    - account_type: credit
  - action: action_credit_account_balance

It appears to me that this above story would not currently work because the model would not know to take the action: "action_credit_account_balance" since it does not have any information about the account_type entity or that its value is "credit".  The docs also state:
"It is important to include the entities here as well because the policies learn to predict the next action based on a combination of both the intent and entities (you can, however, change this behavior using the [use_entities](https://rasa.com/docs/rasa/training-data-format/#entities) attribute)."
which does not seem to be true currently.

This also seems to contradict the paradigm shown for end-to-end training as well (from https://rasa.com/docs/rasa/training-data-format/#end-to-end-training): 

stories:
- story: full end-to-end story
  steps:
  - intent: greet
    entities:
    - name: Ivan
  - bot: Hello, a person with a name!
  - intent: search_restaurant
  - action: utter_suggest_cuisine
  - user: I can always go for [sushi](cuisine)
  - bot: Personally, I prefer pizza, but sure let's search sushi restaurants
  - action: utter_suggest_cuisine
  - user: Have a beautiful day!
  - action: utter_goodbye

This end-to-end story is getting the entity "cuisine" and its value "sushi" and using it to determine the next action.

**Comment by skier233** [comment] 2022-07-13 12:13
bump

**Comment by skier233** [comment] 2022-07-18 11:40
> That looks like a misunderstanding on the user side: _entities_ are featurized only for existence, not for there value - so te next action can only be predicted based on the fact that an entity was given, but not on the value it has.
> 
> In the doc it looks as if that would work, because there are _slots_ that are filled based on the entities, which can support multiple featurizations (existence - text, values - categorical/boolean, etc.) and thus influence the predictions based on values.
> 
> Work on the documentation, please. The code works fine.

@raoulvm I'm aware that entities can autofill into slots and then those slots can be used in stories. However, if this was the case in the stories listed in the docs, then the slot_was_set conditional would have needed to be declared to specify that the next action was being determined by a slot. Without that, then I believe the multiple examples in the wiki wouldn't work.

**Comment by melindaloubser1** [comment] 2022-07-20 22:53
@skier233 This is a pretty confusing thing, both in design and documentation, but @raoulvm is correct: Although the `slot_was_set` steps are not being explicitly declared, they are implicitly there due to the `store_entities_as_slots` parameter: https://rasa.com/docs/rasa/domain#config
Therefore the examples in the docs will work, but not because they're using entity values directly to influence prediction; rather the stories, once turned into trackers, include `slot_was_set` steps of those entity values, allowing to influence the prediction based on value.
This has been a point of confusion before; if you have suggestions (in PR or in comment) on how to more clearly communicate this behaviour in the docs, please do share them.

I'm closing this as not a bug.

**Closed by melindaloubser1** 2022-07-20 22:53 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
