### ISSUE TITLE
still "violation access"

### ISSUE THREAD

**Issue by chongtwo** [RasaHQ/rasa#6288] opened 2020-07-29 06:28 UTC
**Rasa version**: 1.10.7

**Rasa SDK version** (if used & relevant): 1.10.7

**Rasa X version** (if used & relevant): 1.10.7

**Python version**: 3.7

**Operating system** (windows, osx, ...): windows

**Issue**:
In the latest rasa as above, I still get the "violation access" error. I have seen the related issues but they don't help. I also found that when my training data is small like 7KB, it works fine without the error, but when my training data is larger like 642KB, the error appears, the config files are exactly same. And the time the error appear is just when the program is trying to save the model in windows user's temp directory. So I doubt if there is anything to do with temp directory e.g. the model is too large to store in temp directory?   

**Error (including full traceback)**:
```
Part II: train segment classifier
now do training
num training samples: 17267
2020-07-29 12:47:34 INFO     rasa.nlu.model  - Finished training component.
Traceback (most recent call last):
  File "E:\PycharmProjects\rasa-1.10.7\rasa\train.py", line 453, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "E:\PycharmProjects\rasa-1.10.7\rasa\train.py", line 482, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "E:\PycharmProjects\rasa-1.10.7\rasa\nlu\train.py", line 94, in train
    path, persistor, fixed_model_name, persist_nlu_training_data
  File "E:\PycharmProjects\rasa-1.10.7\rasa\nlu\model.py", line 231, in persist
    update = component.persist(file_name, dir_name)
  File "E:\PycharmProjects\rasa-1.10.7\rasa\nlu\extractors\mitie_entity_extractor.py", line 174, in persist
    self.ner.save_to_disk(entity_extractor_file, pure_model=True)
  File "D:\Anaconda3\envs\py37\lib\site-packages\mitie\mitie.py", line 271, in save_to_disk
    if (_f.mitie_save_named_entity_extractor_pure_model(filename, self.__obj) != 0):
OSError: exception: access violation reading 0x0000000000000030

Process finished with exit code 1

```
I tried to debug it, and it said named_entity_extractor doesn't have attribute __obj
**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment] 2020-07-29 12:00
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ArjaanBuijk** [comment] 2020-07-29 23:02
@chongtwo ,

This seems to be something specific to your environment. 

can you post this question in the [forum](https://forum.rasa.com/)?

I will close the issue here, but please tag me in the forum issue, and I will try to help you find the cause of this error.

**Closed by ArjaanBuijk** 2020-07-29 23:02 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:

**Comment by chongtwo** [comment] 2020-07-30 08:00
@ArjaanBuijk ,
I have post this question in the forum with topic "still 'violation access'" in Rasa Open Source category, but I don't find the right place to tag you, so I replied here. Hope you can help me solve the problem. Thanks in advance.
