### ISSUE TITLE
Update documenation for training only NLU

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa#4909] opened 2019-12-04 21:45 UTC
The current documentation [here](https://rasa.com/docs/rasa/user-guide/command-line-interface/) provides misleading info about training the NLU by itself.

The command line interface section suggests that you can use the same syntax `rasa train ... nlu`, but in reality that doesn't work. If you do `rasa train nlu --help` you are informed that the API for just NLU is different than what's in the docs. The `Using NLU Only` section of the docs also ignores the fact that there's an `--nlu` parameter instead of `data` difference.

The docs currently say this:
```
usage: rasa train [-h] [-v] [-vv] [--quiet] [--data DATA [DATA ...]]
                  [-c CONFIG] [-d DOMAIN] [--out OUT]
                  [--augmentation AUGMENTATION] [--debug-plots]
                  [--dump-stories] [--fixed-model-name FIXED_MODEL_NAME]
                  [--persist-nlu-data] [--force]
                  {core,nlu}
```
So if you tried that, like:
```
rasa train --data /app/data/training-data/ --config /app/data/config-files/config.yaml --out /app/models/nlu-only/ nlu
```
It would train an nlu model as if you had only the defaults, ignoring all your command line arguments.

What works instead is 
```
rasa train nlu --nlu /app/data/training-data/ --config /app/data/config-files/config.yaml --out /app/models/nlu-only/ nlu
```

Am I missing something, or should the docs clarify that?

**Comment by sara-tagger** [comment] 2019-12-05 07:00
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment] 2020-02-19 16:46
Hi @jamesmf. Apologies for my super late response. I am not able to reproduce the problem you are facing - using the first command the nlu model gets trained taking into account the cmd arguments (config.yml and others). I will close it for now, but if the problem persists, let us know.

**Closed by JustinaPetr** 2020-02-19 16:46 UTC

**Comment by jamesmf** [comment] 2020-04-06 16:42
https://rasa.com/docs/rasa/user-guide/command-line-interface/#evaluating-a-model-on-test-data

vs

https://rasa.com/docs/rasa/user-guide/testing-your-assistant/#evaluating-an-nlu-model

one says `rasa test nlu [options]` the other says `rasa test [options] nlu` and the latter is wrong I think.
