### ISSUE TITLE
No matching distribution found for tensorflow==1.15.0

### ISSUE THREAD

**Issue by Poojan66** [RasaHQ/rasa#4783] opened 2019-11-18 06:16 UTC
Rasa version: pip install rasa

Python version: 3.6.8

Operating system (linux): ubuntu

Issue:
I keep getting this tensorflow error

>Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15.0

**Comment by sara-tagger** [comment] 2019-11-18 07:00
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment] 2019-11-18 07:51
closing bc duplicate of https://github.com/RasaHQ/rasa/issues/4783

**Closed by amn41** 2019-11-18 07:51 UTC

**Comment by gittar** [comment] 2019-12-30 22:03
@amn41: how can issue 4783 be closed bc duplicate of 4783? Then it is gone, or? Rgds.
