### ISSUE TITLE
GraphComponentException if `hidden_layers_size` used with only one (text) overwritten key

### ISSUE THREAD

**Issue by JulianGerhard21** [RasaHQ/rasa#10391] opened 2021-11-25 13:43 UTC
### Rasa Open Source version

3.0.0

### Rasa SDK version

3.0.0

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

I wanted to train a migrated AI with the following config for `DIETClassifier`:

```
- name: DIETClassifier
  random_seed: 42
  loss_type: cross_entropy
  model_confidence: softmax
  constrain_similarities: True
  intent_classification: True
  entity_recognition: False
  use_masked_language_model: True
  epochs: 80
  number_of_transformer_layers: 4
  transformer_size: 256
  drop_rate: 0.2
  batch_size: [64, 256]
  embedding_dimension: 50
  hidden_layers_sizes:
    text: [512, 128]
```
The result was the following error:

```
  File "...rasa\nlu\classifiers\diet_classifier.py", line 1277, in __init__
    self._prepare_layers()
  File "...rasa\nlu\classifiers\diet_classifier.py", line 1437, in _prepare_layers
    self.config[HIDDEN_LAYERS_SIZES][self.label_name],
  File "...wrapt\wrappers.py", line 394, in __getitem__
    return self.__wrapped__[key]
KeyError: 'label'
```

followed by 

`rasa.engine.exceptions.GraphComponentException: Error running graph component for node train_DIETClassifier5.`

After digging into it, it seems to me, that even if the documentation sais:

```
hidden_layers_sizes: This parameter allows you to define the number of feed forward layers and their output dimensions for user messages and intents (default: text: [], label: []). 
```
it is not enough to specify only one of the keys. After changing the config to:

```
  hidden_layers_sizes:
    text: [512, 128]
    label: []
```

everything worked fine. I am not absolutely sure but this worked in Rasa `2.8.x`.

### Relevant log output

```shell
2021-11-25 14:36:48 INFO     rasa.engine.training.hooks  - Restored component 'LexicalSyntacticFeaturizer' from cache.
2021-11-25 14:36:48 INFO     rasa.engine.training.hooks  - Restored component 'CountVectorsFeaturizer' from cache.
2021-11-25 14:36:48 INFO     rasa.engine.training.hooks  - Restored component 'CountVectorsFeaturizer' from cache.
2021-11-25 14:36:48 INFO     rasa.engine.training.hooks  - Restored component 'MemoizationPolicy' from cache.
2021-11-25 14:36:48 INFO     rasa.engine.training.hooks  - Restored component 'RulePolicy' from cache.
2021-11-25 14:36:49 INFO     rasa.engine.training.hooks  - Starting to train component 'DIETClassifier'.
...
  File "...rasa\nlu\classifiers\diet_classifier.py", line 1277, in __init__
    self._prepare_layers()
  File "...rasa\nlu\classifiers\diet_classifier.py", line 1437, in _prepare_layers
    self.config[HIDDEN_LAYERS_SIZES][self.label_name],
  File "...wrapt\wrappers.py", line 394, in __getitem__
    return self.__wrapped__[key]
KeyError: 'label'
```

Definition of Done:
- [x] Discovered the problem
- [x] Fixed the problem
- [x] Made sure the same problem does not exist for other parameters of the component and also other ML components like TEDPolicy, ResponseSelector and UnexpecTEDIntentPolicy
- [x] Model regression tests run on the PR
- [x] PR is merged to `3.0.x`
- [ ] New micro version released after the bugfix is merged.

**Comment by sara-tagger** [comment] 2021-11-26 07:00
Thanks for raising this issue, @jupyterjazz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment] 2021-11-26 12:29
@dakshvar22 any thoughts about what might have happened here?

**Comment by koernerfelicia** [comment] 2021-11-26 17:37
> Made sure the same problem does not exist for other parameters of the component and also other ML components like TEDPolicy, ResponseSelector and UnexpecTEDIntentPolicy

@dakshvar22 why'd you restrict this to just ML components? Am I missing sth about the nature of how these params are specified?

**Comment by dakshvar22** [comment] 2021-11-29 13:00
@koernerfelicia Mainly because those are the only components where a configuration parameter can have a dictionary of values with keys as some text and values being a list / scalar. The above reported issue suggests a problem with those kind of configuration parameters.

**Comment by kedz** [comment] 2021-11-29 15:02
@koernerfelicia is reviewer

**Comment by mleimeister** [comment] 2021-11-30 09:37
The config of `hidden_layers_sizes` with only setting the `text` key does not lead to the same issue in the other components. However, using the config

```
dense_dimension:
  text: 128
```

(i.e. not specifying the other available keys, such as `label` for DIET, `action_name` for TED, etc.) triggers a similar error for `DIETClassifier` as well as `TEDPolicy` and `UnexpecTEDIntentPolicy`:

```shell
rasa.engine.exceptions.GraphComponentException: Error running graph component for node train_UnexpecTEDIntentPolicy2.

File "/Users/matthias/Workspace/rasa3/rasa/utils/tensorflow/rasa_layers.py", line 291, in <listcomp>
    config[DENSE_DIMENSION][attribute]
KeyError: 'action_name'
```
I was not able to reproduce the same behaviour for `ResponseSelector` using the nested dictionary parameters available there.

This suggests that the issue comes from the general setting of parameters if they contain nested dictionaries and not all keys are specified. The errors that surface then seem to be related to whether the component actually tries to use those missing entries.

**Comment by koernerfelicia** [comment] 2021-11-30 16:36
Thanks for the update!

> This suggests that the issue comes from the general setting of parameters if they contain nested dictionaries and not all keys are specified

I think that this means we shouldn't constrain the investigation to ML components. [CountVectorsFeaturizer](https://rasa.com/docs/rasa/components/#countvectorsfeaturizer) for example allows for nested dictionaries:
```
- name: CountVectorsFeaturizer
  additional_vocabulary_size:
    text: 1000
    response: 1000
    action_text: 1000
```
Haven't looked into the PRs you linked, so it's possible the solution is general enough to cover non-ML components as well.

**Comment by mleimeister** [comment] 2021-11-30 17:06
Hi, thanks for the feedback! In that case I'll also check the `CountVectorsFeaturizer` config. I added some documentation on the potential cause I think I found and steps I implemented for a possible fix in the second [PR's comment](https://github.com/RasaHQ/rasa/pull/10428#issue-1067388337). Since it would touch a core part of the components, it would be great though to discuss if this is actually the correct root cause, and if so a viable fix.

**Comment by koernerfelicia** [comment] 2021-12-07 18:37
@mleimeister you can close the issue when the PR is merged, you don't have to wait for it to be released! I believe the "Fixes" keyword only closes the associated issue if the PR targets `main`, that's why this didn't happen automatically.

**Closed by koernerfelicia** 2021-12-07 18:37 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:, area:rasa-oss/ml 👁, area:rasa-oss/ml/nlu-components, effort:research/4
