### ISSUE TITLE
rasa story visualize WARNING

### ISSUE THREAD

**Issue by HatuneMiku** [RasaHQ/rasa#3650] opened 2019-05-30 02:46 UTC
**Rasa version**:
`Rasa 1.0.2`
**Python version**: 
`Python 3.6.8`
**Operating system** (windows, osx, ...):
`Windows 10 Pro 1903`
**Issue**:
I run this code to visualize my story, but I get a WARNING, json parse error, but my story has the quotes. 
```
rasa visualize --stories data/stories.md
```
this is my story file:

```

## Generated Story -7088822440678882125
* chitchat
    - action_get_user_info
    - slot{"family_members": [{"主人": 614}]}
    - slot{"account_name": "上海"}
    - action_identification_ask
* whoami{"person": "主人"}
    - action_check_identity
    - action_slot_reset

```

and I get this WARNING message:
```
2019-05-30 10:33:12 INFO     rasa.core.visualize  - Starting to visualize stories...
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.27it/s, # trackers=1] 
2019-05-30 10:33:12 WARNING  rasa.core.interpreter  - Invalid to parse arguments in line '/whoami{person: 主人}'. Failed to decode parametersas a json object. Make sure the intentfollowed by a proper json object. Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-05-30 10:33:12 INFO     rasa.core.visualize  - Finished graph creation. Saved into file://D:\OneDrive\Work\rasabot\graph.html
```
Is this a bug?

(By the way, the chinese char shows `��Ҫ����` in graph, I have submitted in #3564, maybe this is related.)

**Comment by erohmensing** [comment] 2019-05-30 08:22
Yes, this warning had to do with the fact that it sanitized (i.e. removed the quotes) and then tried to parse again later. I fixed this while fixing the other issue you submitted, which is now merged into master 🙂 

> By the way, the chinese char shows ��Ҫ���� in graph
I'm not 100 percent sure about this, because I'v'e never run into this -- it may be OS-specific. But I made sure to also utf-8 that output in the line you described. Let me know if this problem still persists!

**Closed by erohmensing** 2019-05-30 08:22 UTC

**Comment by HatuneMiku** [comment] 2019-05-31 02:26
@erohmensing I have tested this in rasa 1.0.3, everything is going right. THANKS!

**Comment by erohmensing** [comment] 2019-05-31 06:16
Perfect! Glad to hear it!

**Comment by becerrag** [comment] 2019-09-12 04:26
@erohmensing I am using Rasa 1.2.5    I am trying to use the visualize command, but it always generates an html file that renders an empty canvas.   I have tried pointing it to my stories file without any luck.   Any suggestions?

**Comment by erohmensing** [comment] 2019-09-16 09:02
ok @becerrag i tested it out and was able to visualize your data, here's the generated file: 
[graph.html.zip](https://github.com/RasaHQ/rasa/files/3615400/graph.html.zip)

Can you try opening it and seeing if you have any luck? (that can tell us if the issue is happening in the writing or reading of the HTML file) 

What browser do you use to open HTML files?

**Comment by becerrag** [comment] 2019-09-17 21:31
@erohmensing well... the file you shared works.  I use Chrome but have also tried on Firefox and Brave (even safari... just in case).   What command did you try?

Thank you for your help, btw.

**Comment by erohmensing** [comment] 2019-09-18 07:35
Super weird, i just used `rasa visualize` -- normally if I run into an issue like this then it's an OS problem, but i'm also on macOS and use chrome 😅 Can you attach the file that yours creates? Can check out the diff to see if there is anything weird. 

I used the latest version of rasa, which is the one thing i can think is different, but I don't think the viz script has changed since 1.2.5 🤔

**Comment by HatuneMiku** [comment] 2019-12-04 12:57
The chinese char shows ��Ҫ���� in graph again, and my version is `Rasa 1.4.6`.  @erohmensing ,  could you check it out, Thanks!

**Comment by erohmensing** [comment] 2019-12-04 16:57
Before I look into it can you please try the same on the latest version?

**Comment by HatuneMiku** [comment] 2019-12-05 06:32
I'm sorry I didn't make it clear. I found it works fine on `rasa visualize` but not good on `rasa interactive` visualisation.
chinese chars shows `����Ѫѹ����` on `rasa interactive` Visualisation at `http://localhost:5006/visualization.html.` , but in cmd it shows chinese chars right. and I test it on rasa version 1.5.1 and 1.4.6. @erohmensing Thanks.
