### ISSUE TITLE
rasa x train model is different of rasa cmdline train model

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa#4030] opened 2019-07-17 10:24 UTC
**Rasa version**:
1.1.3

**Rasa X version** (if used & relevant):
0.19.4

**Python version**:
3.6.5

**Operating system** (windows, osx, ...):
osx

**Issue**:
why i use rasax front-end interface train model is different with cmdline train model?

**Comment by psds01** [comment] 2019-07-17 13:33
`cmdline` model is probably using the latest model. But for `rasa x`, you need to manually change the `production` model to latest. Go to `http://{localhost-our-what-ever-your-ip}:5002/models` and assign the `production` tag to latest model. Like this:
![test](https://user-images.githubusercontent.com/49634935/61379584-723af180-a8c5-11e9-92e4-1cd89d2ae8a8.png)

**Comment by GaoQ1** [comment] 2019-07-17 13:59
i know that, and rasax i also make the latest model  as `production`. i doubt that maybe the two type train funciton use different parameters.

**Comment by olenasch** [comment] 2019-07-18 11:50
I had the same issue, and as it came out later, my domain.yml file got edited by rasa x and used for the training. In my case the {triggers} directives were missing. 
Maybe it is similar in your case? Check your domain.yml and see if it got changed.

**Comment by psds01** [comment] 2019-07-18 11:58
Interesting. Related issue: https://github.com/RasaHQ/rasa/issues/4037

**Comment by akelad** [comment] 2019-07-19 20:36
@GaoQ1 what kind of different behaviour are you experiencing? Is it from using the mapping policy or something else?

**Comment by GaoQ1** [comment] 2019-07-22 08:29
@akelad yes, i use mapping policy

**Comment by akelad** [comment] 2019-07-22 11:11
Ah ok yeah then this is a duplicate of #4037, we'll add this functionality soon

**Closed by akelad** 2019-07-22 11:11 UTC
Labels: bug
