### ISSUE TITLE
Fix for #8496 - shape mismatch error when finetuning

### ISSUE THREAD

**Issue by tttthomasssss** [RasaHQ/rasa#8895] opened 2021-06-16 08:02 UTC
This issue is for fixing #8496.

### Reproduction

**Rasa version**: 2.7.0

**Rasa SDK version**: 2.7.0

**Python version**: 3.7.6

**Operating system**: Darwin-19.2.0-x86_64-i386-64bit

I could reproduce the bug with a fresh rasa `2.7.0` installation. The bug can be reproduced by training an initial rasa model (e.g. via `rasa train`) and subsequently doing the following:

1.  Make changes such that a core model and an NLU model will be finetuned (i.e. add a story to the stories file and add intent examples to the NLU file). The NLU model is finetuned first, upon loading the pipeline for finetuning the core model, the code crashes with the above error.
2.  Finetune only the NLU model (i.e. add examples to an intent in the NLU file). Then finetune the already finetuned NLU model _again_ . Upon loading the NLU model, the code crashes with the above error.

For reproducing the error I have used the data from `carbon-bot` (`phoenix-bot` branch). The config from the original bug report in #8496 should be used for reproducing the issue.

### Investigation

The cause of the problem comes from new features added to the `LexicalSyntacticFeaturizer`, i.e. with new NLU examples, the `LexicalSyntacticFeaturizer` _might_ extract new features, increasing its dimentionality in subsequent layers (e.g. the `DIETClassifier`'s `sequence_layer.text` layer in the sparseToDense mapping where the size of the `CountVectorsFeaturizer` and the size of the `LexicalSyntacticFeaturizer` determine the size of the sparseToDense layer in `DIET`).

The problem comes from this set of weights not being expanded upon serialisation - i.e. the `DIET` is model persisted with the old dimensionality, however the `LexicalSyntacticFeaturizer` is persisted with the _new_ dimenionality. Subsequently, upon loading the pipeline again, there is a size mismatch between the size of the incoming features and the size of the first layer in `DIET` causing the above error.

**Comment by tttthomasssss** [comment] 2021-06-16 09:52
@dakshvar22 From what I've seen the inconsistency is introduced in the first finetuning run but it doesn't yet break. Indeed the `LexicalSyntacticFeaturizer` does extract new features on the first finetuning round. 

Whats slightly baffling now that I have had another look is that on the first round of finetuning, the model data have the "new" size (i.e. with the new features that the `LexicalSyntacticFeaturizer` has extracted upon its finetuning call). However when `self.model.fit(...)` is called inside the `DIETClassifier`'s `train` method, the `model`'s `sequence_layer.text` size is still at the "old" size, yet training proceeds without any problems (and its slightly iffy to step through the code here b/c of all the TF and Keras internals that get in the way, so I can't say yet what is happening). 

Of course when you then serialise the model, the `LexicalSyntacticFeaturizer` has the new dimensionality - and so has the `data_example` - and the `DIET` model is persisted with the old dimensionality. Upon loading pretty much everything is set to the "new" size (s.a. the `data_signature`), so when the model is loaded its fit on a `data_example` with the "new" size (thus initialising the `_tf_layers` (specifically the layer `sequence_layer.text`) to that size and then it calls `model.load_weights(...)` which tries to load the weights with the old size into the model with the new size and the error happens.

So essentially, the problem is that the finetuned model from the first run isn't persisted with the new size. However, I haven't figured out why training doesn't fail given that all the inputs are already set to the new size. Happy to take any pointers if you have a hunch of where and why this is happening.

**Comment by dakshvar22** [comment] 2021-06-16 11:11
Okay, from my investigation there are two problems:

1. `LexicalSyntacticFeaturizer` simply doesn't support incremental training. We never accounted for the fact that the feature vector size of features coming from `LexicalSyntacticFeaturizer` can change during incremental training runs. This was ofcourse my mistake 🙂  Glad that we hit this problem now.

2. So, why does this not cause a problem in the first finetuning run itself? Reason: Since the burden of accounting for new features was given to featurizers themselves in the first place, our models could stay agnostic to the change in feature vector sizes during incremental training and we never needed to change `self.data_signature` of our models during a fine-tuning run. As an effect of that, when a generated batch is first broken down into [different attributes and their feature types](https://github.com/RasaHQ/rasa/blob/fe9f14919df4dcb454ba1052de344fae1466a6d1/rasa/nlu/classifiers/diet_classifier.py#L1499), the models use the old data signature to do this. This is particularly problematic [here](https://github.com/RasaHQ/rasa/blob/6a73b2e799b495411af46230dbc02f5edec3741c/rasa/utils/tensorflow/models.py#L440) as a new sparse tensor is created with the shapes gathered from the data signature. Hence, when this batch is passed to the model architecture there is no problem because the batch now contains a sparse tensor with "compatible" input shape.

So, the root of the problem is actually (1). I'd suggest we don't do anything about this issue until we merge https://github.com/RasaHQ/rasa/issues/8232 . PRs for the linked issue are expected to get merged before `2.8` release and is a better solution as it makes our models more flexible to change in sizes of feature vectors.

**Closed** 2022-10-10 13:33 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
