### ISSUE TITLE
Can not add new intent unless editing the domain.yml manually

### ISSUE THREAD

**Issue by weiczhu** [RasaHQ/rasa#3621] opened 2019-05-28 10:02 UTC
**Rasa version**:
1.0.1
**Python version**: 
3.7
**Operating system** (windows, osx, ...):
osx
**Issue**:
When using the Rasa X we want to add new intents to the NLU Training page, however, there is no way to do so unless editing the domain.yml manually from outside of Rasa X (because there is no UI to edit the domain.yml).

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment] 2019-05-29 07:51
Hi @weiczhu this is a duplicate of #3610. We're looking into getting it fixed, we'll have the UI for editing the domain in an upcoming release.

Thanks for trying out Rasa X, would you be up for giving us some feedback with this [survey](https://rasahq.typeform.com/to/NSJvZM)?

**Closed by akelad** 2019-05-29 07:51 UTC
