### ISSUE TITLE
Parallel tests documentation

### ISSUE THREAD

**Issue by icaropires** [RasaHQ/rasa#4843] opened 2019-11-26 18:02 UTC
**Rasa version**: 1.6.0a1

**Rasa X version** (if used & relevant):

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): Fedora 30

**Issue**: PR #4833 removed `get-num-jobs` task from Makefile, with this change, the feature of passing number of jobs through `-j` flag on `make` command won't work, the only way of telling pytest the number of workers is through `JOBS` environment variable, but the documentation was not updated (check [here](https://github.com/RasaHQ/rasa#running-the-tests)).

By the way, I don't understand the reason the feature was removed. I added that on #4504 and it was working fine by that time. I'm available for helping too if needed :smiley:

**Error (including full traceback)**:
``` bash
(env) ✔︎ rasa (master) make test -j 2
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f  {} +
rm -rf build/
rm -rf .pytype/
rm -rf dist/
rm -rf docs/_build
# OMP_NUM_THREADS can improve overral performance using one thread by process (on tensorflow), avoiding overload
OMP_NUM_THREADS=1 pytest tests -n 1 --cov rasa # The command should be with -n 2 flag
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by erohmensing** [comment] 2019-11-26 18:13
@icaropires would be great if you could help out on #4839

**Comment by icaropires** [comment] 2019-11-26 18:21
> @icaropires would be great if you could help out on #4839

Sure. I'll comment there

**Comment by wochinge** [comment] 2019-11-28 09:24
I close this since it's a duplicate of https://github.com/RasaHQ/rasa/issues/4839

**Closed by wochinge** 2019-11-28 09:24 UTC
Labels: bug
