### ISSUE TITLE
Overlapping graphs in NLU model comparison graph

### ISSUE THREAD

**Issue by razvanra2** [RasaHQ/rasa#8800] opened 2021-06-03 08:03 UTC
**Rasa version**: 2.6.1

**Rasa SDK version** (if used & relevant): 2.6.0

**Rasa X version** (if used & relevant): 2.6.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): mac os 11.3.1

**Issue**: Two graphs are overlapped in the final output of the nlu model comparison graph when testing over five folds for 4 pipelines. See: https://twitter.com/razvan_radoi/status/1399438547938066435 for the issue.
See https://github.com/razvanra2/ChatBot for the source code.
Run:

**Error (including full traceback)**:
```
See image in tweet
```

**Command or request that led to error**:
```
 rasa test nlu --nlu data/nlu.yml --config test_configs/config_1.yml test_configs/config_2.yml test_configs/config_3.yml test_configs/config_4.yml  
```

**Content of configuration file (config.yml)** (if relevant):
```yml
see in repo
```

**Content of domain file (domain.yml)** (if relevant):
```yml
see in repo

```

**Comment by sara-tagger** [comment] 2021-06-03 12:00
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by TyDunn** [comment] 2021-06-03 13:59
Hi @razvanra2. Thanks for opening this issue. I'm going to close it because it is a duplicate of https://github.com/RasaHQ/rasa/issues/8200. We plan to tackle it this sprint, so it should be fixed soon

**Closed by TyDunn** 2021-06-03 13:59 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
