### ISSUE TITLE
Exception when training a model

### ISSUE THREAD

**Issue by mmalhotra** [RasaHQ/rasa#4849] opened 2019-11-26 22:40 UTC
**Rasa version**: 1.4.5

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.6

**Operating system** (windows, osx, ...): docker image

**Issue**: 
While training with a huge training data, the http connection is closed right when training is complete, and the server doesn't respond with 200. 
If you train again then it works instantly (as the model is loaded in rasa, you can see from the logs). 

**Error (including full traceback)**:
```
            | 2019-11-26 21:59:23 INFO     rasa.nlu.model  - Finished training component.
            | 2019-11-26 21:59:24 INFO     rasa.nlu.model  - Successfully saved model into '/tmp/tmpjof8tl3r/nlu'
            | Core model training completed.
            | Training NLU model...
            | NLU model training completed.
            | Your Rasa model is trained and saved at '/app/models/20191126-215924.tar.gz'.
            | [2019-11-26 21:59:27 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:5005/model/train'
            | NoneType: None
            | /build/lib/python3.6/site-packages/sanic/server.py:803: ResourceWarning: unclosed file <_io.BufferedReader name='models/20191126-215924.tar.gz'>
            |   loop.run_forever()
            | 2019-11-26 21:59:27 DEBUG    rasa.server  - Traceback (most recent call last):
            |   File "/build/lib/python3.6/site-packages/rasa/server.py", line 708, in train
            |     model_path, filename=filename, headers={"filename": filename}
            |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
            |     return self.gen.throw(type, value, traceback)
            |   File "/build/lib/python3.6/site-packages/sanic/response.py", line 315, in file
            |     async with open_async(location, mode="rb") as _file:
            |   File "/build/lib/python3.6/site-packages/aiofiles/base.py", line 78, in __aenter__
            |     self._obj = yield from self._coro
            |   File "/build/lib/python3.6/site-packages/aiofiles/threadpool/__init__.py", line 35, in _open
            |     f = yield from loop.run_in_executor(executor, cb)
            | concurrent.futures._base.CancelledError
```

**Command or request that led to error**:
call to /model/train endpoint 
https://rasa.com/docs/rasa/api/http-api/#operation/trainModel

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
- name: "WhitespaceTokenizer"
  case_sensitive: false
- name: "RegexFeaturizer"
- name: DucklingHTTPExtractor
  url: http://duckling:8000
  dimensions: ["time", "number", "amount-of-money", "distance"]
  locale: "en_US"
  timezone: "America/New_York"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: "IntentNERFeaturizer"
- name: "CRFEntityExtractor"
  features: [["low"], ["low"], ["low"], ["low"], ["low", "digit", "pattern", "ner_features"], ["low"], ["low"], ["low"], ["low"]]
- name: "EntitySynonymMapper"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment] 2019-11-27 07:00
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment] 2020-02-25 15:51
@mmalhotra Sorry, completely overlooked this. How long did the training run? How did you start the training? via the http api?

**Comment by mmalhotra** [comment] 2020-02-25 16:01
> How long did the training run? 

~3816 seconds
> How did you start the training?

HTTP POST /model/train

**Comment by wochinge** [comment] 2020-03-02 08:45
Ok, that's then hitting the default timeout. We have to make that configurable. I'll close this as a duplicate of this issue https://github.com/RasaHQ/rasa/issues/4756 (I'm happy to help you with it if you want to fix this yourself @mmalhotra )

**Closed by wochinge** 2020-03-02 08:45 UTC
Labels: type:bug :bug:
