### ISSUE TITLE
Max_history parameter should be carried over to the featurizer definition in TEDPolicy

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#5786] opened 2020-05-07 09:41 UTC
If you have your configuration defined like this, with the featurizer defined explicitly:

*   name: TEDPolicy
     max_history: 5
     featurizer:
*   name: MaxHistoryTrackerFeaturizer
     state_featurizer:
*   name: LabelTokenizerSingleStateFeaturizer

The `max_history` parameter won't get carried over to the `MaxHistoryTrackerFeaturizer`. This is kind of strange behaviour, because if you specify the policy like this:

*   name: TEDPolicy
     max_history: 5

The policy loads up `MaxHistoryTrackerFeaturizer` internally with `max_history: 5`.

See forum post for source of confusion: [https://forum.rasa.com/t/running-oom-in-tedpolicy-with-900-stories-1-10-0/28230/6](https://forum.rasa.com/t/running-oom-in-tedpolicy-with-900-stories-1-10-0/28230/6)

**Comment by chkoss** [comment] 2020-06-11 13:53
Is this rather an issue for @RasaHQ/production-squad or for research squad?

**Comment by wochinge** [comment] 2020-06-12 07:27
@Ghostvv Does it actually make sense to do this when we use Genie's featurizer for everything? If this should still be done, then I think we can handle this + I think it's even good if we can get our feet wet with easier issues like this one.

**Comment by Ghostvv** [comment] 2020-06-12 07:34
it still makes sense to do, we'll have `max_history` parameter anyhow

**Comment by joaoCeilandia** [comment] 2021-03-20 13:07
Me and some friends where working on this issue and wue found that this behavior happens because when creating a featurizer it is instantiated as a `TrackerFeaturizer`  and when no featurizer is instantiated, it is created as a `MaxHistoryTrackerFeaturizer`. this code shows this:
![image](https://user-images.githubusercontent.com/31783143/111869900-41e00c00-8960-11eb-8d41-24db99e3df83.png)

So the only way to make `max_history` be inside the featurizer is by don't instantiating one. 

we tought about make a change by our own to try to fix this but as we don't know what is wanted for this issue( e.g.  if we could make a non-instanciated featurizer just became a `TrackerFeaturizer` or make a intanciated one became a `MaxHistoryFeaturizer` ), we came ask for some directioning.

@akelad @Ghostvv @wochinge @chkoss

**Comment by dakshvar22** [comment] 2021-05-13 18:54
@wochinge IMO, the [fix](https://github.com/RasaHQ/rasa/pull/8292) here does not solve the problem correctly but is more of a hack. It passes the specified `max_history` parameter to the policy and relies on the policy to set the `max_history` of tracker.
An easier and more full proof fix of this would be to do this inside `get_featurizer_from_dict` function in `ensemble.py`. The real issue is that `get_featurizer_from_dict` assumes that the dictionary (`policy`) passed to it contains information for all attributes including `max_history`. However, for that assumption to be correct [`from_dict`](https://github.com/RasaHQ/rasa/blob/408655890aadffc24338fe8fd0a65f886a96aea0/rasa/core/policies/ensemble.py#L404) function should add the `max_history` parameter if specified to the dictionary constructed [here](https://github.com/RasaHQ/rasa/blob/408655890aadffc24338fe8fd0a65f886a96aea0/rasa/core/policies/ensemble.py#L427). This would simplify the constructor and `load` methods of policies.
What do you think? Should I reopen this issue and put it in enable's inbox?

**Comment by wochinge** [comment] 2021-05-17 08:23
> However, for that assumption to be correct from_dict function should add the max_history parameter if specified to the dictionary constructed here. 

You mean using something like `setdefault` to avoid overriding any given `max_history` param? Makes absolutely sense for me 👍🏻

**Comment by dakshvar22** [comment] 2021-05-25 11:31
Also, please let research team know once the issue is closed as there are[ bits of code in policies](https://github.com/RasaHQ/rasa/blob/4b06e362a6cf34f6bdce03ba2373f8d6cc088f12/rasa/core/policies/ted_policy.py#L336) which will simplify once this is in place.

**Closed** 2023-01-09 09:16 UTC
Labels: type:enhancement :sparkles:, area:rasa-oss :ferris_wheel:, area:rasa-oss/ml 👁, area:rasa-oss/ml/policies
