### ISSUE TITLE
DIET Classifier Custom Validation Dataset

### ISSUE THREAD

**Issue by sahinbatmaz** [RasaHQ/rasa#6610] opened 2020-09-09 05:38 UTC
**Description of Problem**:
DIET Classifier has parameter 'evaluate_on_number_of_examples' which determines the size of validation data where it is obtained from the training data. Training data is splitted into train and validation and examples are obtained from each intent with proper counts (stratified). 

However, I would like to use a separate validation data for this purpose.

**Comment by sara-tagger** [comment] 2020-09-09 06:00
Thanks for submitting this feature request 🚀 @tmbo will get back to you about it soon! ✨

**Comment by tabergma** [comment] 2020-09-09 13:34
duplicate of https://github.com/RasaHQ/rasa/issues/5747

**Closed by tabergma** 2020-09-09 13:34 UTC
Labels: area:rasa-oss :ferris_wheel:, type:enhancement :sparkles:
