### ISSUE TITLE
2.0.0rc4: Interactive learning still exports nlu-data and stories as markdown

### ISSUE THREAD

**Issue by N-Olbert** [RasaHQ/rasa#6968] opened 2020-10-08 12:00 UTC
**Rasa version**: 2.0.0rc4

**Python version**: 3.8

**Operating system** (windows, osx, ...): Windows 10 1909

**Issue**:
Stories (and also NLU training data) generated with interactive learning are still exported in the old markdown format.

**Comment by amn41** [comment] 2020-10-08 12:56
thanks! duplicate of https://github.com/RasaHQ/rasa/issues/6935 I think. Already fixed and the release is imminent! :)

**Closed** 2020-10-08 12:56 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
