### ISSUE TITLE
http endpoints become unresponsive while nlu model is updating

### ISSUE THREAD

**Issue by Birne94** [RasaHQ/rasa#3910] opened 2019-07-02 14:03 UTC
**Rasa version**:
Rasa 1.1.4

**Python version**:
Python 3.7.2

**Operating system**:
macOS 10.13.5

**Issue**:
I am using rasa as an nlu service only. When configuring [automatic model pulling](https://rasa.com/docs/rasa/user-guide/running-the-server/#fetching-models-from-a-server), the `/model/parse` endpoint becomes unresponsible for a few seconds while the model is training.

From glancing at the code, the model pulling and update should happen in the background (using `apscheduler`) but it appears to still block standard request handling.

This issue also happens when using the `PUT /model` endpoint to load a model from e.g. S3 or when configuring Sanic to use multiple workers (`app.run(..., workers=4)`).

**endpoints.yml**
```yml

models:
  url: http://localhost:5001/model
  wait_time_between_pulls:  10
```

**Command or request that led to error**:
```
rasa run --enable-api -p 5000 --endpoints endpoints.yml --credentials credentials.yml
```

**Comment by akelad** [comment] 2019-07-05 13:38
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment] 2019-07-08 14:29
@Birne94 Yes, that is true. But not sure if that is really an issue as the server has just one model at a time loaded. If that model gets updated, there is no model to answer any requests. However, you could use the "old" model until the "new" model is loaded. But that would be an improvement in my opinion and not a bug.

**Comment by wochinge** [comment] 2019-09-20 08:37
@tabergma But isn't the issue that you can't use the old model while a new one is training? Makes also sense cause the training is blocking all processing.

**Comment by tabergma** [comment] 2019-09-20 10:23
@wochinge I can't remember anymore. We should test it again.

**Comment by wochinge** [comment] 2019-09-20 12:33
Could you please do that? (no rush)

**Comment by tabergma** [comment] 2019-09-26 07:34
@wochinge Yes. Training is blocking everything and the server is not responding to any other requests.

**Comment by charlielin** [comment] 2019-11-15 08:18
Not only training. Loading is also blocking every requests.

**Comment by charlielin** [comment] 2019-11-15 08:48
Maybe we can put `Agent.load_local_model()` inside `asyncio.run_in_executor` in `rasa/core/agent.py` to resolve this.

**Comment by wochinge** [comment] 2019-11-15 12:57
@erohmensing

**Comment by erohmensing** [comment] 2019-11-15 13:05
@charlielin you mean when loading the model via this endpoint, right? https://rasa.com/docs/rasa/api/http-api/#operation/replaceModel

**Comment by charlielin** [comment] 2019-11-15 14:06
@eric-bonfadini yes

**Comment by erohmensing** [comment] 2019-11-15 16:21
Great. I've confirmed the behavior on my side as well! But i'll open a separate PR for it since it requires another complicated test to be written. Unless you'd like to contribute it? 🙂

**Comment by erohmensing** [comment] 2020-02-07 18:49
Closing as the original issue, requests being blocked during model training, is now fixed via #4774

**Closed** 2020-02-10 12:16 UTC
Labels: area:Rasa OSS, type:enhancement :sparkles:

**Comment by wochinge** [comment] 2020-02-10 13:51
Updating and training is a different thing, isn't it @erohmensing ?

**Comment by erohmensing** [comment] 2020-02-10 15:53
@wochinge I understood the issue as `When configuring automatic model pulling, the /model/parse endpoint becomes unresponsible for a few seconds while the model is training.`

**Comment by wochinge** [comment] 2020-02-11 09:15
I understood this part 😀

> This issue also happens when using the PUT /model endpoint to load a model from e.g. S3 or when configuring Sanic to use multiple workers (app.run(..., workers=4)).
