### ISSUE TITLE
Slot reverts to initial value when SlotSet event is forgotten by AugmentedMemoizationPolicy

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#9471] opened 2021-08-27 15:39 UTC
### Rasa Open Source version

2.6.2

### Python version

Other

### What operating system are you using?

Other

### What happened?

The `AugmentedMemoizationPolicy` seems  to modify a state:
Before calling the delorean, the value of a slot is (0.0, 0.0, 0.0, 1.0, 0.0, 0.0).
After calling the delorean, the value of a slot is (1.0, 0.0, 0.0, 0.0, 0.0, 0.0).

A similar bug was seen before and it might be fixed in the current version. Customer is checking if its fixed with 2.7.1.
Discussion: https://rasa-hq.slack.com/archives/C021ZTVSY77/p1629720593324400

**Comment by koernerfelicia** [comment] 2021-08-30 14:49
Shukri confirmed they're seeing the issue with 2.7.1 as well

**Comment by koernerfelicia** [comment] 2021-09-01 07:19
This actually isn't a matter of sorting. It seems that the "SlotSet" event is forgotten by the policy, and the slot returns to its initial state.

```
slots:
   thing:
    type: rasa.shared.core.slots.CategoricalSlot
    initial_value: abc
    auto_fill: true
    influence_conversation: true
    values:
    - abc
    - def
    - ghi
```
Before calling the delorean, the value of a slot is "ghi" (0.0, 0.0, 1.0).
After calling the delorean, the value of a slot is "abc" (1.0, 0.0, 0.0).

See tests demonstrating this [here](https://github.com/RasaHQ/rasa/pull/9489)

**Comment by koernerfelicia** [comment] 2021-09-03 13:17
@hsm207 am I good to close this as not a bug? You're planning on clarifying this in the docs, right?

**Comment by hsm207** [comment] 2021-09-03 13:35
@koernerfelicia yes, we can close this and i will clarify in the docs

**Closed** 2021-09-03 13:35 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
