### ISSUE TITLE
Rule contradicts with story although slots infulencing conversations should disambiguate them

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7472] opened 2020-12-07 19:01 UTC
**Rasa version**: 2.1.3

**Rasa SDK version**: 2.1.2

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
I have a rule with a condition that a text slot (which influence conversation) is set. I have a story which has this slot set to `null` very early in the conversation. The validation fails stating that the story and rule contradicts each other but this slot makes them different. 

**rule.yml**
```
version: "2.0"
rules:
- rule: respond to apartment FAQs
  conversation_start: false
  condition:
    - slot_was_set:
      - slug: ABCDE
  steps:
  - intent: faq_apartment
  - action: action_faq_apartment
```

**story.yml**
```
version: "2.0"
stories:
- story: Story from Conversation ID 633c1ae1e2694de1ac4ad254346fd2ce
  steps:
  ...
  - slot_was_set:
    - slug: null
  ... many intents, actions and slot_was_set events, none of which setting slug...
  - intent: faq_apartment
    entities:
    - time: '2021-01-03T00:00:00.000-05:00'
    - number: 1
    - mention: the third one
  - action: action_set_apt_selected
  - slot_was_set:
    - slug: ABCDE
```

**Error (including full traceback)**:
```
InvalidRule: 
Contradicting rules or stories found 🚨

- the prediction of the action 'action_set_apt_selected' in story 'Story from Conversation ID 633c1ae1e2694de1ac4ad254346fd2ce' is contradicting with rule(s) 'respond to apartment FAQs' which predicted action 'action_faq_apartment'.
Please update your stories and rules so that they don't contradict each other.
You can find more information about the usage of rules at https://rasa.com/docs/rasa/rules. 
```

**Command or request that led to error**:
```
rasa train core
```

**Content of configuration file (config.yml)** (if relevant):
```yml
policies:
  - name: TEDPolicy
    max_history: 7
    epochs: 200
  - name: RulePolicy
    check_for_contradictions: true
```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
  slug:
    type: text
    influence_conversation: true
```

**Comment by sara-tagger** [comment] 2020-12-08 07:00
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by joejuzl** [comment] 2020-12-15 12:31
@Ghostvv is it expected behaviour that we flag a rule and story as contradicting even if they have different slot conditions?

**Comment by Ghostvv** [comment] 2020-12-15 16:26
It feels like a bug. Strange, I thought I tested for this case

**Comment by aeshky** [comment] 2021-02-17 11:10
@nbeuchat Thanks for flagging the issue. 
I recreated your example but could not reproduce the error. I’m able to invoke the contradiction error when there is indeed a contradiction, but not when there isn’t. 
Is this still a problem that you’re facing? Could you please upgrade to the latest version of Rasa and try again? If the issue persists, then please provide me with enough details to reproduce the error. Perhaps you can supply the complete rather than partial story, and anything else that might be relevant (e.g., custom action or form). 
Thanks!

**Comment by nbeuchat** [comment] 2021-02-17 11:49
Hi @aeshky! Thanks for your response. I have since then quite significantly changed my stories and rules and updated to a latest version of Rasa. I haven't faced this issue since though

**Comment by nbeuchat** [comment] 2021-02-17 11:50
You can probably close for now. If I get this issue again I'll ask to reopen

**Comment by aeshky** [comment] 2021-02-17 12:55
Thanks for your quick response @nbeuchat. 
I'm happy to hear that you haven't faced this issue since. I'll go ahead and close it, and please reopen if it comes up again.

**Closed** 2021-02-17 12:59 UTC
Labels: area:rasa-oss :ferris_wheel:, area:rasa-oss/ml 👁, area:rasa-oss/ml/policies, area:rasa-oss/training-data, type:bug :bug:
