### ISSUE TITLE
Rasa PyPI repository certificate has expired

### ISSUE THREAD

**Issue by connorbrinton** [RasaHQ/rasa#9170] opened 2021-07-19 16:20 UTC
**Rasa version**: Only applies to Rasa X (I think)

**Rasa SDK version** (if used & relevant): N/A

**Rasa X version** (if used & relevant): N/A

**Python version**: All--I specifically was using 3.7.10

**Operating system** (windows, osx, ...): OS X

**Issue**:

The HTTPS certificate for the Rasa PyPI repository has expired.

<img width="1904" alt="Screen Shot 2021-07-19 at 12 18 03 PM" src="https://user-images.githubusercontent.com/1848731/126193258-a45162cf-fa36-430d-988a-f7bbc925a777.png">

I know this is really only an issue for Rasa X users, but since many Rasa users have the Rasa PyPI repository in their list of package sources, I figured it made sense to post here. I also don't know where to report Rasa X issues 😅 

Third-party report: https://www.ssllabs.com/ssltest/analyze.html?d=pypi.rasa.com&hideResults=on&latest

**Comment by Anirudhaagrawal** [comment] 2021-07-19 17:36
Suffering from the same issue. Is there any temporary fix for this?

**Comment by connorbrinton** [comment] 2021-07-19 18:24
May be related to the ongoing LetsEncrypt incident?
https://letsencrypt.status.io/pages/55957a99e800baa4470002da

**Comment by Anirudhaagrawal** [comment] 2021-07-20 05:35
Is there any temporary workaround for this? @connorbrinton

**Comment by tczekajlo** [comment] 2021-07-20 07:45
The issue is solved.

**Closed by tczekajlo** 2021-07-20 07:45 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
