### ISSUE TITLE
The web page for documentation have some weird CSS style

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6156] opened 2020-07-08 02:38 UTC
The web page for documentation has some weird CSS style, make it not easy to read. Here is a sample:

https://rasa.com/docs/rasa/nlu/components/#crfentityextractor

![image](https://user-images.githubusercontent.com/1263428/86868065-990dbb80-c106-11ea-97e3-1a01e70e41ae.png)

**Comment by sara-tagger** [comment] 2020-07-08 06:00
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment] 2020-07-09 12:03
Thanks for bringing this up! We're aware of this -- I'm going to close it as its a duplicate of https://github.com/RasaHQ/rasa/issues/6141

**Closed by erohmensing** 2020-07-09 12:03 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:

**Comment by hellonearthis** [comment] 2020-09-09 17:50
This is still an issue. 
Adding   margin-left: 5px;
To the div.body dd, div.body li, div.body p {}
Corrects the formatting.

If you have greasemonkey or tampermonkey installed on your browser you can run this script to patch the CSS like above.
`// ==UserScript==
// @name         Rasa
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://rasa.com/docs/rasa/*
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';
})();

GM_addStyle ( "div.body dd, div.body li, div.body p {  margin-left: 5px;  }" );`
