### ISSUE TITLE
Unable to export to stories in Rasa Interactive

### ISSUE THREAD

**Issue by Aiodhan** [RasaHQ/rasa#6933] opened 2020-10-06 11:52 UTC
**Rasa version**: 2.0.0.rc4

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): Windows 10

**Issue**:  Unable to export conversation data to stories in interactive mode

**Error (including full traceback)**:
```
Specify a proper file name eg stories.md
```

**Command or request that led to error**:
```
1. rasa interactive
2. Ctrl + C after conversation ended

```

The folder structure contains stories.yml and nlu.yml files in the data folder

**Comment by sara-tagger** [comment] 2020-10-06 12:00
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment] 2020-10-07 06:43
hi @Aiodhan ! I just installed tried to reproduce this but was unable to. 

1. running `2.0.0rc4` on python `3.7.6`
2. created a fresh project with `rasa init`
3. tried many different combinations with `rasa interactive` , creating new NLU data, new stories, export and quit, just hitting ctrl+C twice. 

Wasn't able to get this same error. Can you please share your project structure and the output of `rasa --version` ?

**Comment by amn41** [comment] 2020-10-07 07:57
ah, I was using the `2.0.x` branch rather than release. This is a duplicate of https://github.com/RasaHQ/rasa/issues/6935 and has been fixed :)

**Closed by amn41** 2020-10-07 07:57 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
