### ISSUE TITLE
poetry version conflict with uvicorn

### ISSUE THREAD

**Issue by syntithenai** [RasaHQ/rasa#9718] opened 2021-09-26 12:24 UTC
### Rasa Open Source version

2.8.7

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I am trying to use RASA behind websocket endpoints in a FastAPI server with uvicorn.

The current poetry lock for RASA limits  (via sanic) the websockets version to 8.1. 

Unfortunately uvicorn fails to find the legacy attribute (see LOG1 below) due to requiring changes introduced in websockets 9.0 even though it installs OK. (https://websockets.readthedocs.io/en/latest/project/changelog.html#id10)

The latest sanic 21.6.2 allows for websockets 10

It would be great if rasa and rasa-sdk could be updated to allow for a more recent version of sanic which would let me use a more up to date version of websockets that will work with uvicorn.

For now, as a workaround I can 
```
poetry shell
pip install websockets==10
exit
```

cheers and thanks
Steve

### Command / Request

```shell
# see log2
poetry add rasa
```

### Relevant log output

```shell
=================================================
LOG 1
=================================================

Error in opening handshake
Traceback (most recent call last):
  File "/home/stever/.cache/pypoetry/virtualenvs/api-4EIooTQt-py3.7/lib/python3.7/site-packages/websockets/server.py", line 134, in handler
    extra_headers=self.extra_headers,
  File "/home/stever/.cache/pypoetry/virtualenvs/api-4EIooTQt-py3.7/lib/python3.7/site-packages/websockets/server.py", line 532, in handshake
    early_response = await early_response_awaitable
  File "/home/stever/.cache/pypoetry/virtualenvs/api-4EIooTQt-py3.7/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 136, in process_request
    websockets.legacy.handshake.check_request(headers)
AttributeError: module 'websockets' has no attribute 'legacy'
```

=================================================
LOG 2
=================================================

Using version ^2.8.7 for rasa

Updating dependencies
Resolving dependencies... (31.7s)

  SolverProblemError

  Because no versions of sanic match >19.12.2,<19.12.3 || >19.12.3,<19.12.4 || >19.12.4,<19.12.5 || >19.12.5,<20.3.0 || >20.3.0,<20.6.0 || >20.6.0,<20.6.1 || >20.6.1,<20.6.2 || >20.6.2,<20.6.3 || >20.6.3,<20.9.0 || >20.9.0,<20.9.1 || >20.9.1,<20.12.0
   and sanic (20.9.1) depends on websockets (>=8.1,<9.0), sanic (>19.12.2,<19.12.3 || >19.12.3,<19.12.4 || >19.12.4,<19.12.5 || >19.12.5,<20.3.0 || >20.3.0,<20.6.0 || >20.6.0,<20.6.1 || >20.6.1,<20.6.2 || >20.6.2,<20.6.3 || >20.6.3,<20.9.0 || >20.9.0,<20.12.0) requires websockets (>=8.1,<9.0).
  And because sanic (20.9.0) depends on websockets (>=8.1,<9.0)
   and sanic (20.6.3) depends on websockets (>=8.1,<9.0), sanic (>19.12.2,<19.12.3 || >19.12.3,<19.12.4 || >19.12.4,<19.12.5 || >19.12.5,<20.3.0 || >20.3.0,<20.6.0 || >20.6.0,<20.6.1 || >20.6.1,<20.6.2 || >20.6.2,<20.12.0) requires websockets (>=8.1,<9.0).
  And because sanic (20.6.2) depends on websockets (>=8.1,<9.0)
   and sanic (20.6.1) depends on websockets (>=8.1,<9.0), sanic (>19.12.2,<19.12.3 || >19.12.3,<19.12.4 || >19.12.4,<19.12.5 || >19.12.5,<20.3.0 || >20.3.0,<20.6.0 || >20.6.0,<20.12.0) requires websockets (>=8.1,<9.0).
  And because sanic (20.6.0) depends on websockets (>=8.1,<9.0)
   and sanic (20.3.0) depends on websockets (>=7.0,<9.0), sanic (>19.12.2,<19.12.3 || >19.12.3,<19.12.4 || >19.12.4,<19.12.5 || >19.12.5,<20.12.0) requires websockets (>=7.0,<9.0).
  And because sanic (19.12.5) depends on websockets (>=7.0,<9.0)
   and sanic (19.12.4) depends on websockets (>=7.0,<9.0), sanic (>19.12.2,<19.12.3 || >19.12.3,<20.12.0) requires websockets (>=7.0,<9.0).
  And because sanic (19.12.3) depends on websockets (>=7.0,<9.0)
   and sanic (19.12.2) depends on websockets (>=7.0,<9.0), sanic (>=19.12.2,<20.12.0) requires websockets (>=7.0,<9.0).
  Because no versions of rasa match >2.8.7,<3.0.0
   and rasa (2.8.7) depends on sanic (>=19.12.2,<20.12.0), rasa (>=2.8.7,<3.0.0) requires sanic (>=19.12.2,<20.12.0).
  Thus, rasa (>=2.8.7,<3.0.0) requires websockets (>=7.0,<9.0).
  So, because api depends on both websockets (^10.0) and rasa (^2.8.7), version solving failed.
```

**Comment by sara-tagger** [comment] 2021-09-27 06:00
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment] 2021-09-27 12:17
Thanks for raising this. Closing this as duplicate of https://github.com/RasaHQ/rasa/issues/9315

**Closed by wochinge** 2021-09-27 12:17 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
