### ISSUE TITLE
Mislabeling of "sentence features" as "dense features" in documentation

### ISSUE THREAD

**Issue by alexyuwen** [RasaHQ/rasa#7845] opened 2021-01-29 18:39 UTC
You can see in the `_get_sentence_features` method in the `rasa/nlu/classifiers/sklearn_intent_classifier.py` file that the error message reads "No sentence features present. Not able to train sklearn policy."  This is misleading because sentence features are referred to as "dense features" in the documentation.

I have attached a zip folder containing test component code as well as my `config.yml` file. I used the test component code to test that the features were not present from the spacy_featurizer.  When outputting the features I found that they were empty, as you can see in these screenshots:
<img width="1345" alt="features" src="https://user-images.githubusercontent.com/68449128/106346519-020c7a80-6275-11eb-8fc4-8a62ebcd20a0.png">
<img width="1345" alt="features2" src="https://user-images.githubusercontent.com/68449128/106346520-03d63e00-6275-11eb-9fa5-e7baab200019.png">

[code.zip](https://github.com/RasaHQ/rasa/files/5897330/code.zip)

@kearnsw

**Comment by sara-tagger** [comment] 2021-02-01 07:00
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment] 2021-04-29 09:25
@koaning Are you working on this? If not, can you remove your assignment?

**Comment by dakshvar22** [comment] 2021-04-29 11:59
@alexyuwen I wasn't able to reproduce this on the latest rasa version `2.5.1` and also on `main`. I was able to successfully train a model with this config: 

```
pipeline:
 # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
 # If you'd like to customize it, uncomment and adjust the pipeline.
 # See https://rasa.com/docs/rasa/tuning-your-model for more information.

    - name: SpacyNLP
    - name: SpacyTokenizer
    - name: SpacyFeaturizer
    - name: SpacyEntityExtractor
    - name: SklearnIntentClassifier
    - name: EntitySynonymMapper
    - name: FallbackClassifier
      threshold: 0.3
      ambiguity_threshold: 0.1
```

I also tried with 

```
pipeline:
 # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
 # If you'd like to customize it, uncomment and adjust the pipeline.
 # See https://rasa.com/docs/rasa/tuning-your-model for more information.

    - name: SpacyNLP
    - name: SpacyTokenizer
    - name: SpacyFeaturizer
    - name: SpacyEntityExtractor
    - name: DIETClassifier
    - name: EntitySynonymMapper
    - name: FallbackClassifier
      threshold: 0.3
      ambiguity_threshold: 0.1
      
 ```

Command used: `rasa train nlu`

Let us know if the issue persists for you on the above mentioned versions . I am closing the issue until then.
Thanks!

**Comment by samsucik** [comment] 2021-05-07 14:17
@alexyuwen I'm gonna disagree with you on the terminology issue but I'm more than open to discussion 😉 
> the error message reads "No sentence features present. Not able to train sklearn policy." This is misleading because sentence features are referred to as "dense features" in the documentation.

This particular classifier needs _dense_ features, as the docs say. However, in addition to that, those dense features have to be _sentence-level_ ones (because this classifier can't deal with token-level features (a.k.a "sequence" features), as opposed to transformer-based classifiers like DIET which happily consume sequences of token-level features). Hence, the error message is also correct when it says that sentence features aren't present. It would also be correct to say that "dense, sentence-level features aren't present", though -- I'm not gonna lie 😄 

One thing that now comes to my mind is how openly we talk about dense vs sparse features when talking in the docs about which classifier requires what. But we don't really mention sentence- vs token-level features in the same place. I guess this is primarily because, internally, Rasa tries to construct both sentence-level and token-level features using whatever featuriser, and so users seldom have to worry about a featuriser requiring sentence- or token-level features, but they do have to make sure that they have a dense featuriser if the classifier requires dense features.

Let me know what you think. I'm closing the issue for now though 🙂

**Closed by samsucik** 2021-05-07 14:17 UTC
Labels: area:rasa-oss :ferris_wheel:, area:rasa-oss/ml 👁, area:rasa-oss/ml/nlu-components, type:bug :bug:, type:docs :book:
