### ISSUE TITLE
consolidate `sender_id` and `conversation_id`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4683] opened 2019-10-28 12:32 UTC
Currently we are both using `sender_id` and `conversation_id` in our code. This should be consolidated to `conversation_id`.

Based on this forum comment [https://forum.rasa.com/t/how-can-i-get-a-conversation-id-so-i-run-an-action-via-post-from-an-app/19987/5?u=tobias_wochinger](https://forum.rasa.com/t/how-can-i-get-a-conversation-id-so-i-run-an-action-via-post-from-an-app/19987/5?u=tobias_wochinger)

**Comment by solyarisoftware** [comment] 2020-05-02 18:14
I'd want the issue to be reopened. I think is not "stale"; isn't exactly solved yet; my reasons in this RASA forum post:
https://forum.rasa.com/t/how-can-i-get-a-conversation-id-so-i-run-an-action-via-post-from-an-app/19987/9?u=solyarisoftware

**Comment by solyarisoftware** [comment] 2020-08-02 10:37
I think the issue is probably "stale" and minor, but it could be remain open.

**Comment by solyarisoftware** [comment] 2020-11-02 09:39
The stale motivation of closing the issue is a bit unfair., or it's not clear to me. 

Has the issue current been solved?

See also:
- https://forum.rasa.com/t/how-can-i-get-a-conversation-id-so-i-run-an-action-via-post-from-an-app/19987/9?u=solyarisoftware
- https://github.com/RasaHQ/rasa/issues/5763


Thanks
giorgio

**Comment by wochinge** [comment] 2020-11-02 10:15
> The stale motivation of closing the issue is a bit unfair., or it's not clear to me.

It's simply based on activity. This issue still has to be fixed 👍

**Comment by solyarisoftware** [comment] 2021-07-21 13:29
I think the issue is probably "stale" and minor, but it could be remain open until the documentation will unify naming, choosing a single name, by example: `converstaion_id`

**Comment by rgstephens** [comment] 2022-01-10 04:22
Please, Mr. Stale Bot, don't close this.

**Comment by solyarisoftware** [comment] 2022-01-10 10:21
Yes, please don't close this. For me the problem is already present in the RASA documentation.

**Closed** 2023-01-09 09:17 UTC
Labels: type:maintenance :wrench:, area:rasa-oss :ferris_wheel:
