### ISSUE TITLE
Slack cannot receive any replies from rasa

### ISSUE THREAD

**Issue by Tenglu** [RasaHQ/rasa#3085] opened 2019-03-18 02:21 UTC
**Rasa Core version**: 0.3.13

**Python version**: 3.6

**Operating system** (windows, osx, ...): Linux Ubuntu  16.04

**Issue**: I've used rasa core since last year and the connection between slack and rasa core was good. But when I try to use the latest version of rasa core to connect slack, I did not get any response from rasa core. Would you please help me to check if there is anything wrong with my configuration?  I look through all the issues about slack connection raised in here but did not find the same situation. 

In Event Subscription Section, I input the following events: 
![image](https://user-images.githubusercontent.com/8437103/54502398-4f272200-4965-11e9-9b40-e9811c025ab7.png)

![image](https://user-images.githubusercontent.com/8437103/54502416-6a922d00-4965-11e9-9802-b0531ec3ade9.png)

In Interactive Components, I input: http://ce8fdf9b.ngrok.io/webhooks/slack/webhook

In my credentials file, I included slack channel and token:
![image](https://user-images.githubusercontent.com/8437103/54502441-8eee0980-4965-11e9-9b84-a29aedd652f9.png)

This is the commands I used, which is to run rasa core:
python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --port 5002 --credentials credentials.yml

Every time I send a message from slack, I can get 200 response code in rasa terminal console, but I did not get replies in slack. 
![image](https://user-images.githubusercontent.com/8437103/54502522-0c197e80-4966-11e9-8f57-56c471844f08.png)

In ngrok, it also shows 200 response code:
![image](https://user-images.githubusercontent.com/8437103/54502803-6ebf4a00-4967-11e9-8ad2-17c5b6201a2d.png)

The example I used is "joke robot". I can get replies when I run in command lines, but I never succeed when using slack. 

Would you help to find the reason why it failed to reply? Let me know if I should provide more evidence. Thank you so much!

**Comment by erohmensing** [comment] 2019-03-27 15:31
@Tenglu, have you added a Redirect URL to your OAuth Tokens and Redirect URLs? Perhaps this is why you're not receiving messages:

> The endpoint for receiving slack messages is http://localhost:5005/webhooks/slack/webhook, replacing the host and port with the appropriate values. This is the URL you should add in the OAuth & Permissions section.

**Comment by erohmensing** [comment] 2019-03-27 15:32
Didn't mean to close this, oops

**Comment by erohmensing** [comment] 2019-03-27 16:07
>  I can get replies when I run in command lines, but I never succeed when using slack.

What command are you using to run in the command line?

**Comment by Tenglu** [comment] 2019-04-13 10:14
@erohmensing  Thank you so much for you reply! I'm sorry that I didn't reply in time. I just followed your suggestion to change redirect url to: http://localhost:5055/webhooks/slack/webhook (the port number in my endpoint file is 5055, I also tried 5005 actually), and it's still not working.
![image](https://user-images.githubusercontent.com/8437103/56078161-6ac40200-5e17-11e9-8eff-05347bfc505a.png)
![image](https://user-images.githubusercontent.com/8437103/56078172-8202ef80-5e17-11e9-9171-878189c285f6.png)

When I added --debug to my command line, I saw the following log in my terminal:

![image](https://user-images.githubusercontent.com/8437103/56078140-32242880-5e17-11e9-91aa-571e90b02216.png)

It seems that I received the "hi" from slack, prepare the output which is "hey there! tell me your name",
but slack did not receive it. (or rasa did not send it)

Would you find anything wrong from the log? Thank you!

**Comment by erohmensing** [comment] 2019-04-16 11:40
@Tenglu i've looked into this issue by creating my own bot -- I was wrong about the redirect URL, it shouldn't be necessary. Keep the action endpoint stuff the way it was -- I think the issue is actually the slack channel -- if you want the bot to respond to you in it's own "App" channel (what I assume from `'@chatbot'`, simply leave out the `slack_channel` in your credentials. If it's posting to a channel, say the channel is called chatbot, then it should be `slack_channel: "#chatbot"`.

Let me know if this works for you!

**Closed** 2019-04-30 17:49 UTC
Labels: more-information-needed
