### ISSUE TITLE
Run RASA X on HTTPS

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#4704] opened 2019-10-31 08:26 UTC
Hi,

I enable https of rasa core with the below command and rasa core is now running on HTTPS.

rasa run --ssl-certificate <.crt> --ssl-keyfile <.key> --enable-api -m models/

https://localhost:5005

But when I am trying to do the same stuff with rasa X 
rasa x --ssl-certificate <.crt> --ssl-keyfile <.key>

then still its showing running on http://localhost:5002 not on HTTPS.

**Comment by erohmensing** [comment] 2019-10-31 08:29
duplicate of #4703

**Closed by erohmensing** 2019-10-31 08:29 UTC
Labels: duplicate, question
