### ISSUE TITLE
Remove warning for missing training for nlu_fallback

### ISSUE THREAD

**Issue by iszainab** [RasaHQ/rasa#7659] opened 2020-12-31 17:46 UTC
**Rasa version**: 2.2.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:
The following warning is redundant and should be removed for this particular intent.
"UserWarning: Intent 'nlu_fallback' has only 1 training examples! Minimum is 2, training may fail."

**Comment by wochinge** [comment] 2021-01-29 10:38
closing as duplicate of https://github.com/RasaHQ/rasa/issues/7076

**Closed by wochinge** 2021-01-29 10:38 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
