### ISSUE TITLE
required_slots function in form is not called

### ISSUE THREAD

**Issue by jonahgeladze1** [RasaHQ/rasa#11199] opened 2022-06-17 10:20 UTC
h3\.   Rasa Open Source version

3.1.0

h3\.   Rasa SDK version

3.1.2

h3\.   Python version

3.7

h3\.   What operating system are you using?

Windows

h3\.   What happened?

I've created a form with form validation. Form doesn't call my required_slots method in spite of I've created a custom required_slots function. This is my code:

It calls firstly action_ask_totalizator_block_form_card_number action. But I expect firstly to go to my overriden required_slots function. (I tested on other forms and this works well)

    class ValidateTotalizatorBlockForm(FormValidationAction):

        def name(self) -> Text:
            """Unique identifier of the form. """
            return "validate_totalizator_block_form"

        async def required_slots(
                self,
                domain_slots: List[Text],
                dispatcher: "CollectingDispatcher",
                tracker: "Tracker",
                domain: "DomainDict",
        ) -> Optional[List[Text]]:
            token = get_metadata_parameters(tracker, key="token")
            if not token:
                return []

            number = tracker.get_slot("number")
            card_number = tracker.get_slot("card_number")
            otp = tracker.get_slot("otp")
            accept = tracker.get_slot("accept")

            logger.info(f"number {number}")
            logger.info(f"card_number {card_number}")
            logger.info(f"otp {otp}")
            logger.info(f"accept {accept}")

            if card_number and accept == "no":
                return []

            return ["card_number", "accept", "otp"]

    domain.yml
      - action_ask_totalizator_block_form_card_number
      - action_ask_totalizator_block_form_otp
      - action_submit_totalizator_block_form
      - validate_totalizator_block_form

      totalizator_block_form:
        required_slots:
          - card_number
          - accept
          - otp

    rules:
    - rule: Activate totalizator_block_form
      steps:
      - intent: totalizator.block
      - action: totalizator_block_form
      - active_loop: totalizator_block_form # Keep requesting form slots until they're filled in

    - rule: Submit totalizator_block_form
      condition: # Condition that form is active
      - active_loop: totalizator_block_form
      steps:
      - action: totalizator_block_form
      - active_loop: null # Stop the form
      - slot_was_set:
        - requested_slot: null
      - action: action_submit_totalizator_block_form

h3\.   Command / Request

When I trigger `totalizator.block` intent, it goes to my `action_ask_totalizator_block_form_card_number`. I want it to go to required_slots function firstly.

h3\.   Relevant log output

<pre>Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "C:\Users\igeladze\AppData\Local\Continuum\anaconda3\envs\rasa3\lib\site-packages\rasa_sdk\endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "C:\Users\igeladze\AppData\Local\Continuum\anaconda3\envs\rasa3\lib\site-packages\rasa_sdk\executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "C:\Users\igeladze\AppData\Local\Continuum\anaconda3\envs\rasa3\lib\site-packages\rasa_sdk\utils.py", line 230, in call_potential_coroutine
    return await coroutine_or_return_value
  File "C:\Users\igeladze\Desktop\BOG_Projects\Chatbot3\actions\form\totalizator_block_form.py", line 287, in run
    message, buttons, card_number_and_card_id_map = self.get_card_list(tracker)
  File "C:\Users\igeladze\Desktop\BOG_Projects\Chatbot3\actions\form\totalizator_block_form.py", line 239, in get_card_list
    channel = chat_rb_channel_mapping(channel)
  File "C:\Users\igeladze\Desktop\BOG_Projects\Chatbot3\common\general.py", line 65, in chat_rb_channel_mapping
    assert chat_channel in channels_mapping</pre>

This happens because it calls action_ask_totalizator_block_form_card_number function and not my required_slots function. In my required_slots function, I return [] if user is not logged in. Then it should go to submit and this error will not happen. My question is why it doesnt go to my required_slots function firstly.

**Comment by ScottWalkerAU** [comment] 2022-06-22 10:33
I have encountered this as well, when migrating from Rasa 2 to Rasa 3.

In my experience, Rasa 2 called this function before requesting the first slot.
Now, Rasa 3 calls the function after the first requested slot is attemped to be filled.

A workaround I have used to mimic Rasa 2 behaviour is to list a dummy pre-filled slot as the first slot in the `forms.yml` defintion. Since it's already filled it won't be requested again.

**Comment by melindaloubser1** [comment] 2022-06-22 13:38
This [PR](https://github.com/RasaHQ/rasa/pull/11149) which was part of `3.1.1` addresses a related issue about extracting slots that have `from_trigger_intent` mappings. @jonahgeladze1 I can't run your example as-is since it's not quite complete, could you please confirm if the issue persists on `3.1.1` as well?

**Comment by jonahgeladze1** [comment] 2022-06-23 13:24
@ScottWalkerAU I've tested your solution and it works well, but seems really artificial. 
I think that form should firstly check the required_slots function and after that any "utter_ask" functions.

**Comment by melindaloubser1** [comment] 2022-06-24 08:54
I created this minimal reproducible example here to validate this bug (nothing new to those on this issue, just for future reference)
 https://github.com/melindaloubser1/moodbot/tree/bug_required_slots_not_called

**Comment by melindaloubser1** [comment] 2022-07-20 22:44
Fixed in #11326

**Closed by melindaloubser1** 2022-07-20 22:44 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:, triaged
