### ISSUE TITLE
Fix rasa chat widget storybooks

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#9742] opened 2021-09-29 10:51 UTC
### Rasa Open Source version

2.8.1

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

When using the storybooks page provided for the rasa chat widget located [here](https://chat-widget-docs.rasa.com/?path=/docs/rasa-chat-widget--widget), properties are not properly added to the code the user is supposed to add to a website.

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/32679117/135254335-86025928-8b9c-4b0f-85d6-12aac3504891.png)</span>](https://user-images.githubusercontent.com/32679117/135254335-86025928-8b9c-4b0f-85d6-12aac3504891.png)

As it can be seen above, the properties are added but they don't have the correct syntax.

Above example code:

<>

 The widget will won't show here, instead it will attach itself to the main page 

 {600} 

id="rasa-chat-widget" /> </>

Correct code (different `data-default-open` and `data-width` properties):

<>

 The widget will won't show here, instead it will attach itself to the main page 

 > 

This should be checked for all attributes to make sure they work well.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by hsm207** [comment] 2021-09-29 10:55
This is related to #9739

**Comment by hsm207** [comment] 2022-01-10 08:11
bump

**Comment by m-vdb** [comment] 2022-12-08 08:48
Closing, can't reproduce this issue.

**Closed by m-vdb** 2022-12-08 08:48 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
