### ISSUE TITLE
Predicted intent is always 'greet' for every message that doesn't exists in the training data

### ISSUE THREAD

**Issue by georak** [RasaHQ/rasa#10102] opened 2021-11-08 11:20 UTC
### Rasa Open Source version

2.8.12

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

'greet' intent always return as the selected intent with confidence 1 when user types a message that doesn't exists in the training data.

nlu.yml
```yml
version: "2.0"
nlu:
  - intent: greet
    examples: |
      - γεια
      - γεια σας
      - καλησπέρα
      - καλημερα
      - kalispera
      - geia
      - geia sas
      - kalimera
      - hey
      - hello
      - hi
      - hello there
      - good morning
      - good evening
      - hey dude
      - goodmorning
      - goodevening
      - good afternoon
  - intent: affirm
    examples: |
      - yes
      - sure
```

domain.yml is the default
config.yml is the default + added FallbackClassifier with threshold 0.3

User input: "I am writting something"

predicted intent is always "greet"

![image](https://user-images.githubusercontent.com/3660446/140733318-648a5128-fcf6-4c75-bb67-d7a9fc2bce89.png)

**Comment by koaning** [comment] 2021-11-08 12:45
Just to confirm, does your `nlu.yml` file only contains one intent? If so, this seems like expected behavior. If there is only one class to pick from, the classifier will do exactly that.

**Comment by georak** [comment] 2021-11-08 13:47
I Have multiple, 
I tried it also with a fresh rasa project which has multiple intents too (greet, affirm etc)

FYI
I have also set up a nlu_fallback rule
`
version: "2.0"

rules:

- rule: Fallback
  steps:
  - intent: nlu_fallback
  - action: utter_fallback

- rule: Default Fallback
  steps:
  - intent: action_default_fallback
  - action: utter_fallback


responses:
  utter_fallback:
    - text: fallback
`

**Comment by georak** [comment] 2021-11-08 13:54
This is on a fresh project. 
Shouldn't fallback?

![image](https://user-images.githubusercontent.com/3660446/140754101-2cf3880e-ec1e-4fd9-9388-c2170029fc1f.png)

**Comment by koaning** [comment] 2021-11-08 14:01
Could you try running `rasa shell nlu` so that we can see the confidence values of a few examples? The thing that's hard here is that an ML algorithm is able to give a confidence of 1.0 while giving the wrong answer. That means that right now it's possible that the fallback is not being triggered as opposed to the fallback being broken.

**Comment by georak** [comment] 2021-11-08 14:17
![image](https://user-images.githubusercontent.com/3660446/140757572-c660530c-ffa2-4890-aa0d-4a4d28af3cad.png)

![image](https://user-images.githubusercontent.com/3660446/140757744-4ce94c5c-fe91-4844-baa7-e78794704342.png)

**Comment by koaning** [comment] 2021-11-08 14:32
@georak please refrain from posting screenshots into the issue if it can also be copied/pasted as text. It's better for the screen real-estate and it also makes the contents searchable/copyable. 

That said, looking at your output I have no reason to assume that the fallback trigger is the issue. Instead, it seems like you expected low confidence for these utterances while the model seems to emit a high value. It may sound strange, but this isn't entirely unexpected. [This PyData talk](https://youtu.be/Z8MEFI7ZJlA?t=256) might help explain why you're seeing this. 

Out of curiosity, how many examples do you have for each intent?

**Comment by georak** [comment] 2021-11-08 14:37
Ok Sorry, I will do! 

 3-4 examples

Thank you for our help.
Is there any work arround?

**Comment by koaning** [comment] 2021-11-08 14:41
My gut says that adding more examples will go a long way. I'd try having at least 12 examples per intent. The model may be overfitting on the few examples that exist and is thus learning only to output high confidence values.

**Comment by koaning** [comment] 2021-11-10 09:10
I'll close this issue since it doesn't seem like Rasa is directly breaking here. 

If you'd like to discuss this issue further, please start a thread on our forum at https://forum.rasa.com. That's a preferable place to talk about specific bot issues.  You can ping me there via my @koaning user name there as well.

**Closed by koaning** 2021-11-10 09:10 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
