### ISSUE TITLE
rasa x removes "triggers" from intents in domain.yml

### ISSUE THREAD

**Issue by creadoit** [RasaHQ/rasa#4037] opened 2019-07-17 17:21 UTC
Rasa version: 1.1.4

Rasa X version (docker): 0.19.5

Python version: Python 3.6.9

Operating system (windows, osx, ...): Linux/Docker

**Issue**:

Hi, working with Rasa X the intent "triggers" are removed in the `domain.yml`

**Content of domain file before opening/saving with rasa x**:

```yml
intents:
- affirm
- requirements:
    triggers: action_requirements
- requirements_age:
    triggers: action_apprenticeship_age
- start:
    triggers: action_start_date
```

**Content of domain file after opening/saving with rasa x**:

```yml
intents:
- affirm
- requirements
- requirements_age
- start
```

Even if I try to add the triggers back via the Rasa x UI, after saving all triggers are gone again.

Thanks for your help! :)

**Comment by neumann-d** [comment] 2019-07-18 10:07
observed the same issue when using Rasa X

**Comment by akelad** [comment] 2019-07-19 20:34
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment] 2019-07-22 06:17
Hi @creadoit, thanks for pointing this out. Triggers are not yet supported in the Rasa X domain. We'll be sure to add support soon 🙂

**Comment by imLew** [comment] 2019-07-24 08:22
@creadoit @ricwo there was a very similar issue that caused intent properties, most noticeably `triggers` not to be saved when a domain was exported from interactive learning. This fix is in version 1.1.5 and up but was not in 1.1.4 yet.

**Comment by msamogh** [comment] 2019-07-31 12:24
@ricwo But are we still considering this as a bug or will this only be addressed only after support for triggers is added to Rasa X?

**Comment by ricwo** [comment] 2019-08-02 05:35
it's not a bug as it's expected behaviour until we add support for triggers

**Comment by tmbo** [comment] 2019-08-06 14:25
mhm, but if the triggers are in the domain, shouldn't they just stay there instead of being removed?

**Closed** 2019-08-08 15:00 UTC
Labels: Rasa X
