### ISSUE TITLE
Timeout with long lookup tables

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#4514] opened 2019-09-24 10:49 UTC
**Rasa version**:
Rasa 1.1.8

**Rasa X version** (if used & relevant):

**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
Ubuntu

**Issue**:
After extending my lookup tables (table_1: 270k table:55k examples) it takes significantly longer to process the very first text messages. In 90% of the cases I get a timeout error, however, when the message gets processed correctly additional messages get processed pretty much instantly. To fix this issue I increased the [timeout limit](https://github.com/RasaHQ/rasa/blob/8357bb664aa55b176ba73e2c4911d7a3b53de50f/rasa/core/channels/console.py#L23), so that at least no exception is thrown if it takes longer. Guess the problem here is, that the RegexFeaturizer is loaded to process the first message, but just takes a little bit too long in most cases. 

**Error (including full traceback)**:
```
2019-09-24 12:41:16 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/rasa/core/run.py:115> exception=TimeoutError()>
Traceback (most recent call last):
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/rasa/core/run.py", line 119, in run_cmdline_io
    server_url=constants.DEFAULT_SERVER_FORMAT.format(port)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/rasa/core/channels/console.py", line 137, in record_messages
    async for response in bot_responses:
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/async_generator/_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/async_generator/_impl.py", line 205, in throw
    return self._invoke(self._it.throw, type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/rasa/core/channels/console.py", line 102, in send_message_receive_stream
    async for line in resp.content:
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/aiohttp/streams.py", line 40, in __anext__
    rv = await self.read_func()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/aiohttp/streams.py", line 329, in readline
    await self._wait('readline')
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/aiohttp/streams.py", line 297, in _wait
    await waiter
  File "/home/local/MGM/hschroeder/.virtualenvs/A12Bot/lib/python3.6/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Command or request that led to error**:
Simply typing the first text message. If I type '\{some_intent} it gets processed instantly, but the next following text message gets effected.

**Content of configuration file (config.yml)** (if relevant):
```yml
language: 'de_core_news_sm'
pipeline:
- name: "SpacyNLP"
- name: "SpacyFeaturizer"
- name: "SpacyTokenizer"
- name: "SklearnIntentClassifier"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
  features: [
              ["low", "title", "upper"],
              ["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3",
               "suffix2", "upper", "title", "digit", "pattern"],
              ["low", "title", "upper"]
            ]
- name: "DucklingHTTPExtractor"
  url: "http://localhost:40003"
  dimensions: ["time"] # ENTER DIMENSIONS to extract
  locale: "de_DE" # enter country code  e.g. en_US
  timezone: "Europe/Berlin" # enter timezone

# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "utils.custom_policies.RestartPolicy"
  - name: MemoizationPolicy
  - name: MappingPolicy
  - name: KerasPolicy
  - name: FormPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.4
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_ask_affirmation"
    deny_suggestion_intent_name: "out_of_scope"
```

**Comment by IgNoRaNt23** [comment] 2019-09-24 11:10
There should be probably no/way longer timeout limit, when the NLU model loads for the first time. Or this should happen at another point.

**Comment by sara-tagger** [comment] 2019-09-24 12:00
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment] 2019-09-25 16:09
@IgNoRaNt23 You are using `rasa shell`, aren't you? Are you having the same issue if you `rasa shell` and then wait for a while before sending the first message?

**Comment by IgNoRaNt23** [comment] 2019-09-26 06:46
Yes, Im using `rasa shell`. I tried waiting, but that has no effect. I may even communicate with the bot, by sending pure intent message like `\greet` and it works fine. The error occurs whenever I sent the first standard text message.

**Comment by wochinge** [comment] 2019-10-09 11:47
@IgNoRaNt23 Sorry for my delayed answer, I was away for a while. Seems to me that we have to make this part https://github.com/RasaHQ/rasa/blob/a61810706002076ed8f7ed8380fbae6e9bb1b262/rasa/core/run.py#L125 more robust. Would you be interested in fixing this?

**Comment by m-vdb** [comment] 2020-05-06 09:02
Hello @IgNoRaNt23, for the sake of understanding your use case: what's in your lookup tables? They seem really long compared to what we commonly see. Also, is this still an issue with newest Rasa versions? Thanks 🙏

**Comment by IgNoRaNt23** [comment] 2020-05-12 08:32
The lookup table was a list of all unique street names in germany from a map database. However, it was just a showcase project at that time and we're currently not working on anything adress related. I may check if the problem is still there. But at least for the shell one can define the timeout now, can't one?

**Comment by m-vdb** [comment] 2020-05-12 16:53
yes this is now possible ✅ :
https://github.com/RasaHQ/rasa/blob/81b1cbe9d46f44e8235f5970ae43aab17c06476b/rasa/core/channels/console.py#L112-L119

**Comment by wochinge** [comment] 2021-01-28 13:45
duplicate of https://github.com/RasaHQ/rasa/issues/5909

**Closed by wochinge** 2021-01-28 13:45 UTC
Labels: area:rasa-oss :ferris_wheel:, area:rasa-oss/channels 📞, priority:low, type:bug :bug:
