### ISSUE TITLE
 Tried to set non existent slot 'count_list'. Make sure you added all your slots to your domain file.

### ISSUE THREAD

**Issue by mohankumargx** [RasaHQ/rasa#3803] opened 2019-06-17 14:30 UTC
**Rasa version**: 1.1.3

**Rasa X version** (if used & relevant):Not using

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Windows 10

**Issue**: When i tried to use interactive learning getting this error though i mentioned all the slots in domain file.. It was working well earlier in rasa==1.0.7 version.

**Error (including full traceback)**:
```
2019-06-17 19:35:24 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ca2c5d2b07f140bb90668586f1c28b10'
2019-06-17 19:35:24 DEBUG    rasa.core.processor  - Received user message 'list all impacted cis' with intent '{'name': 'ci_info', 'confidence': 0.9596539735794067}' and entities '[{'start': 0, 'end': 4, 'value': 'List', 'entity': 'count_list', 'confidence': 0.9737233844587407, 'extractor': 'CRFEntityExtractor', 'processors': ['EntitySynonymMapper']}, {'start': 9, 'end': 17, 'value': 'Impacted', 'entity': 'impa_noimpa', 'confidence': 0.9975736855043231, 'extractor': 'CRFEntityExtractor', 'processors': ['EntitySynonymMapper']}]'
2019-06-17 19:35:24 DEBUG    rasa.core.processor  - Current slot values:
        count_list: List
        filter1: None
        impa_noimpa: Impacted
        item_text: None
        item_value: None
        open_close: None
2019-06-17 19:35:24 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 4 events
2019-06-17 19:35:25 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ca2c5d2b07f140bb90668586f1c28b10'
? Is the intent 'ci_info' correct for '[list](count_list:List) all [impacted](impa_noimpa:Impacted) cis' and are all entities labeled correctly?  Yes
2019-06-17 19:35:30 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ca2c5d2b07f140bb90668586f1c28b10'
2019-06-17 19:35:30 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'entity_count_list': 1.0, 'intent_ci_info': 1.0, 'slot_count_list_0': 1.0, 'slot_impa_noimpa_0': 1.0, 'prev_action_listen': 1.0, 'entity_impa_noimpa': 1.0}]
2019-06-17 19:35:30 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '8'
2019-06-17 19:35:30 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
2019-06-17 19:35:30 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ca2c5d2b07f140bb90668586f1c28b10'
2019-06-17 19:35:30 ERROR    rasa.core.trackers  - Tried to set non existent slot 'count_list'. Make sure you added all your slots to your domain file.
2019-06-17 19:35:30 ERROR    rasa.core.trackers  - Tried to set non existent slot 'impa_noimpa'. Make sure you added all your slots to your domain file.
------
Chat History

 #    Bot                                                                                        You
────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1    action_listen
────────────────────────────────────────────────────────────────────────────────────────────────────────────
 2                                         [list](count_list:List) all [impacted](impa_noimpa:Impacted) cis
                                                                                       intent: ci_info 0.96
────────────────────────────────────────────────────────────────────────────────────────────────────────────
 3    slot{"count_list": "List"}
      slot{"impa_noimpa": "Impacted"}
```

**Command or request that led to error**:
```
rasa interactive --debug --endpoints endpoints.yml
```

**Content of configuration file (config.yml)** (if relevant):
```yml


```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment] 2019-06-18 07:02
Please post your domain file as well

**Comment by mohankumargx** [comment] 2019-06-18 07:48
@akelad Please find the domain file

"""
slots:
  item_value: 
    type: text
  item_text: 
    type: text
  open_close:
    type: text
  count_list:
    type: text
  impa_noimpa:
    type: text
  filter1:
    type: text


intents:
  - greet
  - farewell
  - how_doing
  - out_of_scope
  - thank
  - item_info
  - count_list_info
  - ci_info
  - ticket_ci
  - development


entities:
  - open_close
  - item_value
  - item_text
  - count_list
  - impa_noimpa
  - filter1

templates:
  utter_greet:
    - text: "Hello! I'm customerbot🤖 and will be happy to help you with Ticket and CI information"
    - text: "Hi! I'm customerbot🤖 and will be happy to help you with Ticket and CI information"
    - text: "Greetings for the day, I'm customerbot🤖 and will be happy to help you with Ticket and CI information"

  utter_farewell:
    - text: "Goodbye! 👋"
    - text: "Bye-Bye! 👋"
    - text: "Bye 👋, was nice talking to you!"

  utter_how_doing:
    - text: "I'm very well, thank you."
    - text: "I'm good, thanks!"
    - text: "I'm great! Thanks for asking."

  utter_anything_else:
    - text: "Is there anything else I can help you with?"

actions:
- utter_greet
- utter_farewell
- utter_anything_else
- utter_noworries
- utter_out_of_scope
- utter_how_doing
- utter_default
- utter_help
- utter_select
- action_item_info
- action_count_list_info
- utter_ask_ticket_number
- utter_ask_priority 
- action_ci_info
- action_ticket_ci
- utter_development
"""

**Comment by GianMariaPandolfi** [comment] 2019-06-18 09:56
I got this error too

**Comment by mohankumargx** [comment] 2019-06-18 10:55
@GianMariaPandolfi  agree with you.. It works

**Comment by mohankumargx** [comment] 2019-06-18 11:08
@GianMariaPandolfi  yeah it works.. I didn't proceed and check as i was getting the error

**Comment by mohankumargx** [comment] 2019-06-18 11:09
@GianMariaPandolfi  yeah it works.. Thank you...

**Comment by Lucioric2000** [comment] 2019-06-18 18:10
I also got this issue, that is driving my and my employer crazy

**Comment by akelad** [comment] 2019-06-19 08:53
Ok this is strange, just to clarify so we can try and reproduce this, you're running the command `rasa interactive` right? with a newly trained model?

**Comment by mohankumargx** [comment] 2019-06-19 09:03
> Ok this is strange, just to clarify so we can try and reproduce this, you're running the command `rasa interactive` right? with a newly trained model?

Yes @akelad

**Comment by akelad** [comment] 2019-06-19 16:17
alright, @imLew would be great if you could try and reproduce this

**Comment by sjtilney** [comment] 2019-06-21 01:11
Same issue. initially happened with Rasa 1.1.1
I upgraded to Rasa 1.1.3, retrained my models, but the issue still persists.
I'm not noticing any issues with performance, everything still seems to be working as expected, just getting the errors
![Screen Shot 2019-06-20 at 6 07 18 PM](https://user-images.githubusercontent.com/9960124/59890610-8d7a1600-9386-11e9-813b-3e0858c74638.png)

Domain file:
```
entities:
- conf_room_name
- building_name
- food_type
- duration
- occasion
- menu_type
- station_name
- country
- colleague_name
- cafe_name
- query_location
- restrictions
- start_time
- time_period
- query_date
slots:
  building_name:
    type: unfeaturized
  cafe_name:
    type: unfeaturized
  colleague_name:
    type: list
  conf_room_name:
    type: text
  country:
    type: unfeaturized
  domain:
    type: unfeaturized
  duration:
    type: unfeaturized
  food_type:
    type: unfeaturized
  menu_type:
    type: unfeaturized
  occasion:
    type: text
  occasion_count:
    type: unfeaturized
  occasion_dates:
    type: unfeaturized
  occasion_titles:
    type: unfeaturized
  query_date:
    type: text
  query_location:
    type: text
  query_person_name:
    type: text
  requested_slot:
    type: unfeaturized
  restrictions:
    type: unfeaturized
  room_available:
    type: bool
  rooms_available:
    type: bool
  start_time:
    type: text
  station_name:
    type: unfeaturized
  time_period:
    type: text
```

**Comment by imLew** [comment] 2019-06-24 10:01
@akelad Yes, this happens even on the latest master, I will see if I can figure out why

**Comment by dptelecom** [comment] 2019-07-05 23:37
Hi i have the same issue i renamed a slot and did it every where.
also search the whole project folder nowhere a trace find of the slot name and i get this now every time
![Screen Shot 2019-07-06 at 01 32 12](https://user-images.githubusercontent.com/42352742/60748458-78a89f80-9f8e-11e9-978c-925d482e70a2.jpg)

**Comment by imLew** [comment] 2019-07-08 08:12
@dptelecom the PR addressing the problem should be merged today, please try again using the master branch once this issue is closed.

**Closed** 2019-07-08 09:29 UTC
Labels: bug

**Comment by TayyibahR** [comment] 2019-07-25 14:10
I had this same issue yesterday. in interactive mode i was getting an error while trying to set entities and slot(my domain file had entities and slots correctly defined):
error:  rasa.core.trackers - Tries to set non existent slot

At first i thought i needed trackers.py update but when i looked into nlu.md data that interactive mode generated i found some inconsistencies in entity extraction(there were new entities and intents i didnt want). I fixed those inconsistencies and i no longer get this error.

**Comment by imLew** [comment] 2019-07-29 10:47
@TayyibahR Please create a seperate issue for this, as it sounds like the underlying problem is different. Or, if you could turn your fix into a PR that would be even better :D!

**Comment by sachin10101998** [comment] 2020-07-06 16:35
Same issue. Any fix?

**Comment by srikanth9444** [comment] 2021-01-30 07:05
Hi, I'm getting the same error ERROR    rasa.shared.core.trackers  - Tried to set non existent slot 'gender'. Make sure you added all your slots to your domain file. Actually I double checked no issue with the slots and indentation. it was working fine, after added some small talk content and tried to retrain the model, then this issue started.
Any suggestions to fix this issue would be greatly appreciated

**Comment by leenaborasahaj** [comment] 2021-02-22 14:12
If domain file is correct... then you possibly you might be missing out on retraining and starting rasa server again and not just rasa action server

**Comment by snek93** [comment] 2021-02-26 09:40
I am having the same issue. Not only is it thinking that a certain slot is non-existent, but it also fills it and then requests it again inside the form. After that, Rasa-X refuses to run the next action because the action tries to extract this particular slot from the tracker.

**Comment by akelad** [comment] 2021-02-26 09:42
please open a new issue for this, the functionality has changed significantly since version 1.1.3, so it's unlikely this has anything to do with the originally reported issue.
