### ISSUE TITLE
Req payload - Attribute type for training a model using HTTP API

### ISSUE THREAD

**Issue by vishnupriyavr** [RasaHQ/rasa#7608] opened 2020-12-20 10:34 UTC
**Description of Problem**:
Some feedback for training a model using the HTTP API, it would be really helpful if the attribute-type for each of the key attributes ( nlu ,domain ,config, stories )can be exposed as JSON types instead of strings. @TyDunn, tagging you as discussed on the #feedback-for-rasa slack channel.

**Overview of the Solution**:
It would be helpful if the request payload attributes for train HTTP API goes on these lines:
{
"intents": [
{"intent": "<intentname>", "examples":["<example1>","<example2"] },
			],
  "entities": [
{"entity": "<entityname>" ,"value": "<entityvalue>"}
              ],
  "responses": [
{"response":"<responsename>", "message":"<utter_response>"},
               ],
 "stories": [
{"stories":"<storyname>", "steps":"<storysteps>"},
               ],               
} 

**Definition of Done**:

**Comment by sara-tagger** [comment] 2020-12-21 07:00
Thanks for submitting this feature request 🚀 @desmarchris will get back to you about it soon! ✨

**Comment by desmarchris** [comment] 2020-12-21 15:12
thanks for the post @vishnupriyavr - Ty is out of office for the end of the year. I'll set a reminder to review this with him when he's back!

**Comment by TyDunn** [comment] 2021-01-04 13:44
@degiz Can you help me understand why they are exposed as strings and not JSON types today?

**Comment by wochinge** [comment] 2021-01-29 10:07
duplicate of https://github.com/RasaHQ/rasa/issues/3999

**Closed by wochinge** 2021-01-29 10:07 UTC
Labels: area:rasa-oss :ferris_wheel:, area:rasa-oss/server, type:enhancement :sparkles:
