### ISSUE TITLE
Invalid warnings produced by rasa test

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#8636] opened 2021-05-07 15:56 UTC
**Rasa versions**: 2.6.0, 2.5.0, 2.4.0, and 2.3.0  (this issue does not occur with 2.2.0)

**Rasa SDK version**: 2.6.0

**Python version**: 3.8.8

**Operating system**: macOS-10.16-x86_64-i386-64bit

**Issue**:
I upgraded to the latest version of rasa, and `rasa test` is giving me some invalid warnings. It complains that all of my intents are missing from the `domain` file when they aren't. 

You can reproduce the warnings by creating a new project using: 
```
rasa init
```
Then running:
```
Rasa test
```
You should get the following warnings for each intent: 
```
UserWarning: Issue found in './tests/test_stories.yml': Found intent 'greet' in stories which is not part of the domain.
```
and
```
UserWarning: Issue found in 'data/stories.yml': Found intent 'greet' in stories which is not part of the domain.
```
And also warnings for intents in the `rules.yml` file: 
```
UserWarning: Issue found in 'data/rules.yml': Found intent 'goodbye' in stories which is not part of the domain.
```

**Comment by rgstephens** [comment] 2021-05-14 16:14
This is a duplicate of #8135

**Closed by rgstephens** 2021-05-14 16:14 UTC
Labels: area:rasa-oss :ferris_wheel:, priority:low, type:bug :bug:
