### ISSUE TITLE
Metadata.template_name (in bot events) renamed in 2.4 to utter_action without backwards compatibility and mentioning in the changelog

### ISSUE THREAD

**Issue by PROrock** [RasaHQ/rasa#8841] opened 2021-06-07 12:19 UTC
**Rasa version**:
tested on 2.6.2, most likely affects 2.4.0 and higher 
**Rasa SDK version** (if used & relevant):
Tested on Java SDK, modified https://github.com/rbajek/rasa-java-sdk. But it's not really about SDK.
**Rasa X version** (if used & relevant):
No Rasa X used.
**Python version**:
3.7.9
**Operating system** (windows, osx, ...):
osx
**Issue**:
Rasa version 2.4. includes bigger rename/refactoring - mostly renaming objects with the word "template" to use the word "response". Most of the changes are backwards compatible as you only added the new field/attribute and keep the old one (which will be removed in Rasa 3.0.0 release).

But for events of type "bot", you have renamed the metadata's attribute "template_name" to "utter_action", which is not backwards compatible. We are reading this attribute in the action server (we have one in Java) and we have to change the name there at the same time. We also use this field in reporting code (looking at events in the tracker store).

It wouldn't really help us, but for companies/users who are still on a version lower than 2.4.0 it can help them with the migration if you would add the original attribute "template_name" would still be there in tandem with the new attribute.
It would also help if you can mention this in the changelog (as from that it seems that the changes affect only the NLG server, which is not true).

Links to places that would probably need to be fixed:
Method run in a few actions in https://github.com/RasaHQ/rasa/blob/main/rasa/core/actions/action.py specifically:
ActionBotResponse
ActionRetrieveResponse
RemoteAction
ActionDefaultAskAffirmation

Sorry, if this isn't a bug per-se and should be reported differently.

**Error (including full traceback)**:
there is no error per-se.

**Command or request that led to error**:
no explicit command needed

**Content of configuration file (config.yml)** (if relevant):
not relevant

**Content of domain file (domain.yml)** (if relevant):
not relevant

**Comment by sara-tagger** [comment] 2021-06-08 06:00
Thanks for the issue, @hsm207 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by PROrock** [comment] 2021-09-10 13:51
Hi, any update on this?

**Comment by melindaloubser1** [comment] 2021-09-21 15:53
You're right that the impact on the action server should have been made clear in the changelog. 

Re. backwards compatibility: Since it only becomes incompatible with an action server other than rasa-sdk, that's probably why it was not considered. 

Since it's not a bug per se, I'll close this issue.

**Closed by melindaloubser1** 2021-09-21 15:53 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
