### ISSUE TITLE
Action server is not responding (status code 500)

### ISSUE THREAD

**Issue by HovHak** [RasaHQ/rasa#3307] opened 2019-04-24 05:09 UTC
**Rasa version**:13.3

**Python version**: 3.6

**Operating system** (windows, osx, ...):Windows 10

**Issue**: during the interactive training I try to run action_weather after I gave it the input text 'what is the weather like in Italy?'

![image](https://user-images.githubusercontent.com/48651497/56633574-997f7b00-6656-11e9-8bdc-ae54aea15785.png)

it does not look like it is failing but it seems like it is in the infinite loop or something because it is not returning anything

![image](https://user-images.githubusercontent.com/48651497/56633710-2d514700-6657-11e9-9d6d-9a523d95be80.png)

it is just not doing anything i am confused whether what can cause this issue 

**Content of actions.py **:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core.actions import Action
# from rasa_core_sdk import Action
# from rasa_core_sdk.events import SlotSet

from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

#from WeatherAPIXU.client

class ActionWeather(Action):
    def name(self):
        return 'action_weather'

    def run(self, dispatcher, tracker, domain):
        from apixu.client import ApixuClient
        api_key = '333'  # your apixu key
        client = ApixuClient(api_key)

        loc = tracker.get_slot('location')
        current = client.getcurrent(q=loc)

        country = current['location']['country']
        city = current['location']['name']
        condition = current['current']['condition']['text']
        temperature_c = current['current']['temp_c']
        humidity = current['current']['humidity']
        wind_mph = current['current']['wind_mph']

        response = """It is currently {} in {} at the moment. The temperature is {} degrees, the humidity is {}% and the wind speed is {} mph.""".format(
            condition, city, temperature_c, humidity, wind_mph)

        dispatcher.utter_message(response)
        return [SlotSet('location', loc)]


class ActionScheduleMeeting(Action):
    def name(self):
        return 'action_schedule_meeting'

    def run(self, dispatcher, tracker, domain):
        print('scheduling meeting is completed! ')
        pass


class ActionShowMeeting(Action):
    def name(self):
        return 'action_show_meeting'

    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message('Here is the meeting information!')
        return []
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
    - schedule_meeting
    - search_for_meeting
    - greet
    - inform
    - goodbye

entities:
    - meeting
    - time
    - location

slots:
    location:
         type: text
    time:
         type: text
    meeting:
         type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_goodbye:
        - 'Talk to you later.'
        - 'Bye bye :('
    utter_ask_meeting_time:
        - 'What time would you like me to schedule your meeting?'
    utter_ask_location:
        - 'In what location?'
actions:
    - utter_greet
    - utter_goodbye
    - utter_ask_meeting_time
    - utter_ask_location
    - actions.ActionShowMeeting
    - actions.ActionWeather
```

**Comment by akelad** [comment] 2019-04-24 13:21
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment] 2019-04-24 14:21
Hey @HovHak,
You are calling action `actions.ActionWeather` in the domain file, but the custom action you build is called `action_weather`:
```
def name(self):
        return 'action_weather'
```
Everything else looks fine to me so far, so if you change the action names so that they are consistent in your domain file and custom actions this should work for you.

Please let me know here if this fixes your issue.

**Comment by HovHak** [comment] 2019-04-24 14:47
> Hey @HovHak,
> You are calling action `actions.ActionWeather` in the domain file, but the custom action you build is called `action_weather`:
> 
> ```
> def name(self):
>         return 'action_weather'
> ```
> Everything else looks fine to me so far, so if you change the action names so that they are consistent in your domain file and custom actions this should work for you.
> 
> Please let me know here if this fixes your issue.

Hi @paulaWesselmann  thanx for helping me,

I have done it as you said but then run to this error 
![image](https://user-images.githubusercontent.com/48651497/56668903-37e7fc80-66a8-11e9-9efa-58e971efd4d6.png)

I also had action-weather specified in the domain as actions.action_weather  it still gave me the same result

**Comment by paulaWesselmann** [comment] 2019-04-24 15:14
@HovHak I'm confused on why it is trying to connect to the slack/webhook when you are running the custom action. 

There are two more things I can think of right now that might be causing this:
1. You are calling `tracker` without ever importing it. Add `from rasa_core_sdk import Tracker` to your imports and rename `tracker` to `Tracker`

2. If it still doesn't work:
 Try `current = client.current(q=loc)`  instead of `current = client.getcurrent(q=loc)`

**Comment by paulaWesselmann** [comment] 2019-04-24 15:16
I will close this issue here since this is a usage issue and not a code issue. 
Please still let me know in here if this worked for you. 
For further questions you can use the [Rasa forum](https://forum.rasa.com/).

**Comment by HovHak** [comment] 2019-04-24 15:33
> I will close this issue here since this is a usage issue and not a code issue.
> Please still let me know in here if this worked for you.
> For further questions you can use the [Rasa forum](https://forum.rasa.com/).

Dear @paulaWesselmann  before trying interactive training i was trying to run my nlu and dialogue model on Slack which is why in the endpoints i have passed it as slack/webhook  so that the sack recognizes the actions but it did not give me any replies so i thought i need to perform interactive training to update my stories(since there were not many) and then try to run them again on a slack

**Comment by paulaWesselmann** [comment] 2019-04-24 15:41
@HovHak did you try this?
>You are calling tracker without ever importing it. Add from rasa_core_sdk import Tracker to your imports and rename tracker to Tracker

can you post your endpoint file?
I think you'll have to change it back in order for it to work.

Please also post the output of your action server, when running this.

**Comment by HovHak** [comment] 2019-04-24 15:51
> @HovHak did you try this?
> 
> > You are calling tracker without ever importing it. Add from rasa_core_sdk import Tracker to your imports and rename tracker to Tracker
> 
> can you post your endpoint file?
> I think you'll have to change it back in order for it to work.
> 
> Please also post the output of your action server, when running this.
yes I did i have imported the trucker 


action_endpoint:
  url: "http://localhost:5055/webhooks/slack/webhook"

**Comment by paulaWesselmann** [comment] 2019-04-24 18:51
@HovHak Try changing the endpoint back to
```
action_endpoint:
    url: http://localhost:5055/webhook
```
when running interactive learning.

**Comment by HovHak** [comment] 2019-04-24 18:56
> @HovHak Try changing the endpoint back to
> 
> ```
> action_endpoint:
>     url: http://localhost:5055/webhook
> ```
> when running interactive learning.

i did anfot this error again
![image](https://user-images.githubusercontent.com/48651497/56686020-1ba98700-66cb-11e9-9160-e94c1c5c89f3.png)

**Comment by paulaWesselmann** [comment] 2019-04-24 19:44
I think you have a typo since your action server states `POST /webhooks` instead of `POST /webhook`

**Comment by HovHak** [comment] 2019-04-24 19:50
> I think you have a typo since your action server states `POST /webhooks` instead of `POST /webhook`

oh sorry silly(, it run to a different error not the 404
![image](https://user-images.githubusercontent.com/48651497/56689260-96c26b80-66d2-11e9-8ef1-34d2f6c3fe3a.png)

**Comment by paulaWesselmann** [comment] 2019-04-24 20:18
Great! This should be easy to fix now. When I told you to add import the tracker and change it to `Tracker` I was mistaken, I didn't see the tracker is passed to the run function. Revert that change and I hope your error is gone!

**Comment by HovHak** [comment] 2019-04-24 20:58
> Great! This should be easy to fix now. When I told you to add import the tracker and change it to `Tracker` I was mistaken, I didn't see the tracker is passed to the run function. Revert that change and I hope your error is gone!
> Sorry for being misleading before.

yes, i did that before, it still does not work ago,

![image](https://user-images.githubusercontent.com/48651497/56693100-8367ce00-66db-11e9-9aef-f09bc89b8ac2.png)

i tried both when testing 
![image](https://user-images.githubusercontent.com/48651497/56693152-a6927d80-66db-11e9-91b5-ef74afd52fa7.png)

**Comment by paulaWesselmann** [comment] 2019-04-24 21:09
Ah damn, that would have been too nice.
I think the `.getcurrent` attribute now is just `current`.

**Comment by HovHak** [comment] 2019-04-24 21:19
> Ah damn, that would have been too nice.
> I think the `.getcurrent` attribute now is just `.current`.

yes i had it commented because i tried both ways it still returns the same erorr. sorry about this.

**Comment by paulaWesselmann** [comment] 2019-04-24 21:30
I'm sorry this isn't working, but I still don't think it is an actual code issue, but rather a usage issue.
I'll look more into that tomorrow. 
In the meantime you can try using --deug flag and try to run it in the command line without using interactive learning.

**Comment by HovHak** [comment] 2019-04-24 21:33
> I'm sorry this isn't working, but I still don't think it is an actual code issue, but rather a usage issue.
> I'll look more into that tomorrow.
> In the meantime you can try using --deug flag and try to run it in the command line without using interactive learning.

oh thanx i look forward on hearing from you)))

**Comment by HovHak** [comment] 2019-04-26 02:36
Hey @paulaWesselmann any updates regarding this issue ?

**Comment by paulaWesselmann** [comment] 2019-04-26 05:29
@HovHak I'm sorry this issue isn't my priority and I will not get back to it this week. Please seek help on the [forum](https://forum.rasa.com/) for issues like this. 
I'll investigate if this is a bug in the code, but I assume your issue is with how you use the Apixu client
Maybe try adding some debugging messages and see if it works without using the  Apixu client and sending a generic message like `dispatcher.utter_message("test test")` to narrow down where the bug is.
Thank you for your patience!

**Comment by HovHak** [comment] 2019-04-28 15:52
> @HovHak I'm sorry this issue isn't my priority and I will not get back to it this week. Please seek help on the [forum](https://forum.rasa.com/) for issues like this.
> I'll investigate if this is a bug in the code, but I assume your issue is with how you use the Apixu client
> Maybe try adding some debugging messages and see if it works without using the Apixu client and sending a generic message like `dispatcher.utter_message("test test")` to narrow down where the bug is.
> Thank you for your patience!

Hey, I am sorry to disturb you with this issue but I have tried to do trouble shouting with dispatcher.utter_message("test test") but it seems that athe action servers do not repond at all 
![image](https://user-images.githubusercontent.com/48651497/56866826-dbe9e480-69d5-11e9-84f7-d16553cb679b.png)

could you please help me to resolve this issue? or you would want me to open a new issue? 

thank you.

**Comment by paulaWesselmann** [comment] 2019-04-28 16:41
Hey @HovHak I'll reopen this issue.
Please also post the action servers error messages you are getting (restart the action server before running interactive learning again).
Can you also run `pip list |grep rasa` in the command line and let me know the output?
Thank you!

**Comment by HovHak** [comment] 2019-04-28 16:58
> Hey @HovHak I'll reopen this issue.
> Please also post the action servers error messages you are getting (restart the action server before running interactive learning again).
> Can you also run `pip list |grep rasa` in the command line and let me know the output?
> Thank you!

thanx for coming back), 

![image](https://user-images.githubusercontent.com/48651497/56867619-1015d300-69df-11e9-82d3-6632a1c5bdc3.png)

i have tried this pip list |grep rasa but it seems like windows does not support grep, i am currently tring to install it

**Comment by paulaWesselmann** [comment] 2019-04-28 17:22
In this currently instance that you send just now the problem is that you haven't annotated the location entity and and the location slot is not filled.
To avoid your custom action from failing when the required slots for it are not filled, I recommend to handle those cases in your custom action, re-requesting the slot. 
Please restart your action server and restart your interactive learning conversation and send me the action server error messages for when the location entity is annotated and the location slot is filled before entering the custom action.

**Comment by HovHak** [comment] 2019-04-28 17:35
> In this currently instance that you send just now the problem is that you haven't annotated the location entity and and the location slot is not filled.
> To avoid your custom action from failing when the required slots for it are not filled, I recommend to handle those cases in your custom action, re-requesting the slot.
> Please restart your action server and restart your interactive learning conversation and send me the action server error messages for when the location entity is annotated and the location slot is filled before entering the custom action.

so i was going through my code and noticed that the I was returning the slot 'location when trying to which instead should be returning [] 
I have commented out everything in the action weather and left only dispatcher.utter_message('test test')
and return []. after what it worked

![image](https://user-images.githubusercontent.com/48651497/56867959-10fd3380-69e4-11e9-9437-763f55097888.png)

so it looks like atm. my code is the issue 
**Content of actions.py f**:
```actions
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core.actions import Action
# from rasa_core_sdk import Action
# from rasa_core_sdk.events import SlotSet

from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet
#from rasa_core_sdk import Tracker
#from WeatherAPIXU.client

class ActionWeather(Action):
    def name(self):
        return 'action_weather'

    def run(self, dispatcher, tracker, domain):
        from apixu.client import ApixuClient
        api_key = '333'  # your apixu key
        client = ApixuClient(api_key)

        loc = tracker.get_slot('location')
        #current = client.getcurrent(q=loc)
        current = client.current(q=loc)

        country = current['location']['country']
        city = current['location']['name']
        condition = current['current']['condition']['text']
        temperature_c = current['current']['temp_c']
        humidity = current['current']['humidity']
        wind_mph = current['current']['wind_mph']

        response = """It is currently {} in {} at the moment. The temperature is {} degrees, the humidity is {}% and the wind speed is {} mph.""".format(
            condition, city, temperature_c, humidity, wind_mph)

        dispatcher.utter_message(response)
        #dispatcher.utter_message('test test')
        return [SlotSet('location', loc)]
        #return []

class ActionShowMeeting(Action):
    def name(self):
        return 'action_show_meeting'

    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message('Here is the meeting information!')
        return []

class ActionScheduleMeeting(Action):
    def name(self):
        return 'action_schedule_meeting'

    def run(self, dispatcher, tracker, domain):
        print('scheduling meeting is completed! ')
        pass


```

**Comment by paulaWesselmann** [comment] 2019-04-28 17:47
Awesome so there is no rasa issue! I'm glad we solved this now.
Since this is an issue with your usage of the `apixu` I recommend checking out:
https://github.com/apixu/apixu-python and 
https://www.apixu.com/doc/getting-started.aspx
Good luck!

**Closed by paulaWesselmann** 2019-04-28 17:47 UTC

**Comment by pratikh07** [comment] 2019-08-10 15:15
> I will close this issue here since this is a usage issue and not a code issue.
> Please still let me know in here if this worked for you.
> For further questions you can use the [Rasa forum](https://forum.rasa.com/).

AttributeError: 'ApixuClient' object has no attribute 'getcurrent'

please help me mam
