### ISSUE TITLE
Response time in `rasa shell` taking 2.5 seconds with original project on Windows

### ISSUE THREAD

**Issue by skier233** [RasaHQ/rasa#11288] opened 2022-06-29 23:42 UTC
### Rasa Open Source version

3.2.1

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

I can not get rasa to run with a reasonable execution time on my windows computer. I've tried uninstalling python, restarting windows, making new virtual environments, using both powershell and command prompt, and using debug statements. 

I put a ton of debug statements in the code and I see the debug message here (debug 28 in console.py _send_message_receive_stream):
      

async def _send_message_receive_stream(
    server_url: Text,
    auth_token: Text,
    sender_id: Text,
    message: Text,
    request_timeout: Optional[int] = None,
) -> AsyncGenerator[Dict[Text, Any], None]:
    logger.debug("debug 25")
    payload = {"sender": sender_id, "message": message}

    url = f"{server_url}/webhooks/rest/webhook?stream=true&token={auth_token}"

    # Define timeout to not keep reading in case the server crashed in between
    timeout = _get_stream_reading_timeout(request_timeout)
    logger.debug("debug 24")
    async with aiohttp.ClientSession(timeout=timeout) as session:
        logger.debug("debug 28")
        async with session.post(url, json=payload, raise_for_status=True) as resp:
            logger.debug("debug 27")
            async for line in resp.content:
                if line:
                    logger.debug("debug 26")
                    yield json.loads(line.decode(DEFAULT_ENCODING))

and then after about 2.5seconds, I see the next debug message here (debug 36 in rest.py receive). Also it's important to note there is no other debug or console information between these 2 debug statements:

        @custom_webhook.route("/webhook", methods=["POST"])
        async def receive(request: Request) -> Union[ResponseStream, HTTPResponse]:
            logger.debug("debug 36")

I tried setting my own timeout for the aiohttp session used in that post command. If I set the timeout to 5 seconds it works but takes long (as described above). If I set the timeout to 2 seconds or less, then aiohttp throws an error because it couldn't get a response in the timeout time.

Something in between these 2 messages is taking around 2.5 seconds and I can't figure out what it is or how to fix it. Any help would be greatly appreciated!

### Command / Request

```shell
rasa shell
```

**Comment by larryhchen8888** [comment] 2022-07-04 06:10
I have the same problem. On the same PC, if I use wsl to run the same project, it takes less than 1 second. Hope someone can shed some light on this. I don't want to run wsl because the vm takes up too much memory.

**Comment by larryhchen8888** [comment] 2022-07-04 06:48
I figured it out. It's the connection to the duckling server. Once I deleted the rule in config.yml, the response time reduced to 0.15 sec on average. The question is then what functionalities I lose without using duckling server.

**Comment by larryhchen8888** [comment] 2022-07-04 06:57
After further investigation, the problem is "localhost" for duckling server url. If I change it to url: http://127.0.0.1:8000 in config.yml, the response time remains 0.15sec. Mystery solved!

**Comment by larryhchen8888** [comment] 2022-07-04 07:02
After further investigation, the problem is "localhost" for duckling server url. If I change it to url: http://127.0.0.1:8000/ in config.yml, the response time remains 0.15sec. Mystery solved!

**Comment by Skier23** [comment] 2022-07-04 14:00
I’ll give that a try and report back.

**Comment by skier233** [comment] 2022-07-04 14:21
I'm not sure what a "duckling" server is but I don't believe I have one of those so there's nothing for me to change in my config.yml.

**Comment by skier233** [comment] 2022-07-05 18:07
Any help with this would be greatly appreciated!

**Comment by larryhchen8888** [comment] 2022-07-05 19:05
I was able to reduce the response time with the api calls. My rasa shell response time is still about 2 seconds. Since I don’t use rasa shell for my purpose, I decided not to spend more time on it.

**Comment by skier233** [comment] 2022-07-05 19:07
I noticed when I run in a docker container on linux I don't get this issue. Also, I get this issue when running as a server using a callback but not when using rest. I believe the issue is coming from aiohttp but I don't know exactly why it occurs.

**Comment by larryhchen8888** [comment] 2022-07-05 21:18
I'm almost certain the delay is caused by resolving localhost. Try making IPv4 preferred:

# Make IPv4 (::ffff:0:0/96) preferred:
netsh interface ipv6 set prefix ::ffff:0:0/96 60 4

You can also verify it with the following:
rasa run --enable-api --debug
create a python script, say call it cmdlinechat.py:
#=============
import asyncio
import uuid

from rasa.core import constants
from rasa.core.channels import console
print(constants.DEFAULT_SERVER_FORMAT.format("http", 5005))
print(uuid.uuid4().hex)
asyncio.run(console.record_messages(
    server_url=constants.DEFAULT_SERVER_FORMAT.format("http", 5005),
#    server_url="http://127.0.0.1:5005",
    sender_id=uuid.uuid4().hex,
))
#================
This is a frontend shell that will connect to your rasa server. You can uncomment the server_url by using the 127 IP address directly. The difference in response time are immediately noticeable.

Hope this helps.

**Comment by ancalita** [comment] 2022-07-06 08:16
@skier233 In order for me to reproduce this issue I would need all your rasa project files, you can submit these on the [forum ](https://forum.rasa.com/)and then ping the link in a comment here. Please also confirm all the versions of your venv packages by running `pip list` and posting the output here.
Please also run `rasa shell --debug` and posting the logs here.

**Comment by skier233** [comment] 2022-07-06 12:30
1. This doesn't need any specific files. I've repro'd it several times on an entirely fresh virtualenv with a new project using rasa init. I've also uninstalled and reinstalled python 2 times and tried 3 different python versions.
2. Here is the current pip list: 
Package                      Version
---------------------------- ---------
absl-py                      0.13.0
aio-pika                     6.8.2
aiofiles                     0.8.0
aiohttp                      3.8.1
aiormq                       3.3.1
aiosignal                    1.2.0
APScheduler                  3.7.0
astunparse                   1.6.3
async-timeout                4.0.2
asynctest                    0.13.0
attrs                        21.2.0
bidict                       0.22.0
boto3                        1.24.21
botocore                     1.27.21
CacheControl                 0.12.11
cachetools                   4.2.4
certifi                      2022.6.15
cffi                         1.15.1
chardet                      3.0.4
charset-normalizer           2.1.0
cloudpickle                  1.6.0
colorama                     0.4.5
colorclass                   2.2.2
coloredlogs                  15.0.1
colorhash                    1.0.4
cryptography                 37.0.2
cycler                       0.11.0
dask                         2022.2.0
dnspython                    1.16.0
docopt                       0.6.2
fbmessenger                  6.0.0
fire                         0.4.0
flatbuffers                  2.0
frozenlist                   1.3.0
fsspec                       2022.5.0
future                       0.18.2
gast                         0.4.0
google-auth                  1.35.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
greenlet                     1.1.2
grpcio                       1.47.0
h5py                         3.7.0
httptools                    0.4.0
humanfriendly                10.0
idna                         3.3
importlib-metadata           4.12.0
importlib-resources          5.8.0
jmespath                     1.0.1
joblib                       1.0.1
jsonpickle                   2.0.0
jsonschema                   4.4.0
kafka-python                 2.0.2
keras                        2.7.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.3
libclang                     14.0.1
locket                       1.0.0
Markdown                     3.3.7
matplotlib                   3.3.4
mattermostwrapper            2.2
msgpack                      1.0.4
multidict                    5.2.0
networkx                     2.6.3
numpy                        1.19.5
oauthlib                     3.2.0
opt-einsum                   3.3.0
packaging                    20.9
pamqp                        2.3.0
partd                        1.2.0
Pillow                       9.1.1
pip                          20.1.1
prompt-toolkit               2.0.10
protobuf                     3.19.4
psycopg2-binary              2.9.3
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycparser                    2.21
pydot                        1.4.2
PyJWT                        2.4.0
pykwalify                    1.8.0
pymongo                      3.10.1
pyparsing                    3.0.9
pyreadline                   2.1
pyrsistent                   0.18.1
pyTelegramBotAPI             4.6.0
python-crfsuite              0.9.8
python-dateutil              2.8.2
python-engineio              4.3.2
python-socketio              5.6.0
pytz                         2021.3
PyYAML                       6.0
questionary                  1.10.0
randomname                   0.1.5
rasa                         3.2.1
rasa-sdk                     3.2.0
redis                        3.5.3
regex                        2022.4.24
requests                     2.28.1
requests-oauthlib            1.3.1
requests-toolbelt            0.9.1
rocketchat-API               1.25.0
rsa                          4.8
ruamel.yaml                  0.16.13
ruamel.yaml.clib             0.2.6
s3transfer                   0.6.0
sanic                        21.12.1
Sanic-Cors                   2.0.1
sanic-jwt                    1.8.0
sanic-routing                0.7.2
scikit-learn                 0.24.2
scipy                        1.7.3
sentry-sdk                   1.3.1
setuptools                   47.1.0
six                          1.16.0
sklearn-crfsuite             0.3.6
slackclient                  2.9.4
SQLAlchemy                   1.4.39
tabulate                     0.8.10
tarsafe                      0.0.3
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.3
tensorflow-addons            0.15.0
tensorflow-estimator         2.7.0
tensorflow-hub               0.12.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
terminaltables               3.1.10
threadpoolctl                3.1.0
toolz                        0.11.2
tqdm                         4.64.0
twilio                       6.50.1
typeguard                    2.13.3
typing-extensions            3.10.0.2
typing-utils                 0.1.0
tzlocal                      2.1
ujson                        5.3.0
urllib3                      1.26.9
wcwidth                      0.2.5
webexteamssdk                1.6.1
websockets                   10.3
Werkzeug                     2.1.2
wheel                        0.37.1
wrapt                        1.14.1
yarl                         1.7.2
zipp                         3.8.0


3. Here is the debug logs: (Note the delay occurs after "hello" and before any of the other messages)
Bot loaded. Type a message and press enter (use '/stop' to exit):
Your input ->  hello
2022-07-06 08:31:00 DEBUG    rasa.core.lock_store  - Issuing ticket for conversation '9b6e368c55964bbaaa04328130ccf225'.
2022-07-06 08:31:00 DEBUG    rasa.core.lock_store  - Acquiring lock for conversation '9b6e368c55964bbaaa04328130ccf225'.
2022-07-06 08:31:00 DEBUG    rasa.core.lock_store  - Acquired lock for conversation '9b6e368c55964bbaaa04328130ccf225'.
2022-07-06 08:31:00 DEBUG    rasa.core.tracker_store  - Could not find tracker for conversation ID '9b6e368c55964bbaaa04328130ccf225'.
2022-07-06 08:31:00 DEBUG    rasa.core.processor  - Starting a new session for conversation ID '9b6e368c55964bbaaa04328130ccf225'.
2022-07-06 08:31:00 DEBUG    rasa.core.processor  - Policy prediction ended with events '[]'.
2022-07-06 08:31:00 DEBUG    rasa.core.processor  - Action 'action_session_start' ended with events '[<rasa.shared.core.events.SessionStarted object at 0x0000024473CA7748>, ActionExecuted(action: action_listen, policy: None, confidence: None)]'.
2022-07-06 08:31:00 DEBUG    rasa.core.processor  - Current slot values:
        requested_activity: None
        session_started_metadata: None
2022-07-06 08:31:00 DEBUG    rasa.engine.runner.dask  - Running graph with inputs: {'__message__': [<rasa.core.channels.channel.UserMessage object at 0x000002440E4C0F88>]}, targets: ['run_RegexMessageHandler'] and ExecutionContext(model_id='b0bdad075d69488a80ea33ee9d5997f4', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'nlu_message_converter' running 'NLUMessageConverter.convert_user_message'.
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'run_WhitespaceTokenizer0' running 'WhitespaceTokenizer.process'.
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'run_RegexFeaturizer1' running 'RegexFeaturizer.process'.
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'run_LexicalSyntacticFeaturizer2' running 'LexicalSyntacticFeaturizer.process'.
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'run_CountVectorsFeaturizer3' running 'CountVectorsFeaturizer.process'.
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'run_CountVectorsFeaturizer4' running 'CountVectorsFeaturizer.process'.
2022-07-06 08:31:00 DEBUG    rasa.engine.graph  - Node 'run_DIETClassifier5' running 'DIETClassifier.process'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_EntitySynonymMapper6' running 'EntitySynonymMapper.process'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_ResponseSelector7' running 'ResponseSelector.process'.
2022-07-06 08:31:01 DEBUG    rasa.nlu.classifiers.diet_classifier  - There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2022-07-06 08:31:01 DEBUG    rasa.nlu.selectors.response_selector  - Adding following selector key to message property: default
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_FallbackClassifier8' running 'FallbackClassifier.process'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'domain_provider' running 'DomainProvider.provide_inference'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_RegexMessageHandler' running 'RegexMessageHandler.process'.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9999983310699463}' and entities '[]'
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 4 events.
2022-07-06 08:31:01 DEBUG    rasa.core.actions.action  - Validating extracted slots:
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Default action 'action_extract_slots' was executed, resulting in 0 events:
2022-07-06 08:31:01 DEBUG    rasa.engine.runner.dask  - Running graph with inputs: {'__tracker__': <rasa.shared.core.trackers.DialogueStateTracker object at 0x0000024473C80A08>}, targets: ['select_prediction'] and ExecutionContext(model_id='b0bdad075d69488a80ea33ee9d5997f4', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'rule_only_data_provider' running 'RuleOnlyDataProvider.provide'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'domain_provider' running 'DomainProvider.provide_inference'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_MemoizationPolicy0' running 'MemoizationPolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.memoization  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
2022-07-06 08:31:01 DEBUG    rasa.core.policies.memoization  - There is a memorised next action 'utter_greet'
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_RulePolicy1' running 'RulePolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user text: hello | previous action name: action_listen
2022-07-06 08:31:01 DEBUG    rasa.core.policies.rule_policy  - There is no applicable rule.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
2022-07-06 08:31:01 DEBUG    rasa.core.policies.rule_policy  - There is no applicable rule.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_TEDPolicy3' running 'TEDPolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.ted_policy  - TED predicted 'utter_greet' based on user intent.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_UnexpecTEDIntentPolicy2' running 'UnexpecTEDIntentPolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.unexpected_intent_policy  - Querying for intent `greet`.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.unexpected_intent_policy  - Score for intent `greet` is `1.2209702730178833`, while threshold is `-0.9161255359649658`.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.unexpected_intent_policy  - Top 5 intents (in ascending order) that are likely here are: `[('mood_unhappy', -1.7838209), ('deny', -1.6807455), ('bot_challenge', -1.6757848), ('greet', 1.2209703), ('request_action', 1.3810422)]`.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'select_prediction' running 'DefaultPolicyPredictionEnsemble.combine_predictions_from_kwargs'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.ensemble  - Made prediction using user intent.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.ensemble  - Added `DefinePrevUserUtteredFeaturization(False)` event.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.ensemble  - Predicted next action using MemoizationPolicy.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Predicted next action 'utter_greet' with confidence 1.00.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Policy prediction ended with events '[<rasa.shared.core.events.DefinePrevUserUtteredFeaturization object at 0x0000023E5C9CBFC8>]'.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Action 'utter_greet' ended with events '[BotUttered('Hey! How are you?', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"utter_action": "utter_greet"}, 1657110661.6971178)]'.
2022-07-06 08:31:01 DEBUG    rasa.engine.runner.dask  - Running graph with inputs: {'__tracker__': <rasa.shared.core.trackers.DialogueStateTracker object at 0x0000024473C80A08>}, targets: ['select_prediction'] and ExecutionContext(model_id='b0bdad075d69488a80ea33ee9d5997f4', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'rule_only_data_provider' running 'RuleOnlyDataProvider.provide'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'domain_provider' running 'DomainProvider.provide_inference'.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_MemoizationPolicy0' running 'MemoizationPolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.memoization  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
2022-07-06 08:31:01 DEBUG    rasa.core.policies.memoization  - There is a memorised next action 'action_listen'
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_RulePolicy1' running 'RulePolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
2022-07-06 08:31:01 DEBUG    rasa.core.policies.rule_policy  - There is no applicable rule.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_TEDPolicy3' running 'TEDPolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.ted_policy  - TED predicted 'action_listen' based on user intent.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'run_UnexpecTEDIntentPolicy2' running 'UnexpecTEDIntentPolicy.predict_action_probabilities'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.unexpected_intent_policy  - Skipping predictions for UnexpecTEDIntentPolicy as either there is no event of type `UserUttered`, event's intent is new and not in domain or there is an event of type `ActionExecuted` after the last `UserUttered`.
2022-07-06 08:31:01 DEBUG    rasa.engine.graph  - Node 'select_prediction' running 'DefaultPolicyPredictionEnsemble.combine_predictions_from_kwargs'.
2022-07-06 08:31:01 DEBUG    rasa.core.policies.ensemble  - Predicted next action using MemoizationPolicy.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Policy prediction ended with events '[]'.
2022-07-06 08:31:01 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'.
2022-07-06 08:31:01 DEBUG    rasa.core.lock_store  - Deleted lock for conversation '9b6e368c55964bbaaa04328130ccf225'.

**Comment by skier233** [comment] 2022-07-20 21:53
I don't believe you would see lag on requests to the web resthook if the requests you are sending are through postman or some other similar method. I noticed that I do not observe any latency communicating to the rasa server via postman or C#. I only experience the slowness when running in rasa shell (since rasa shell is using asyncio for the rest requests). All this being said, although this issue is annoying (and another dev I've been working with repro'd on their windows system using rasa shell), it isn't blocking me that much anymore since now I have my rasa server running inside a linux docker compose cluster where the issue does not appear. It seems the issue is specific to linux. If you can, try running in rasa shell and looking for the latency.

**Comment by melindaloubser1** [comment] 2022-07-20 22:10
Gotcha - I was testing in Postman; I do see more of a lag in `rasa shell`, harder to quantify but something like a second and a bit. I am curious why that is, but  if you have a sufficient workaround, I'd suggest closing this, especially since this is only affecting shell and not any of the channels used to serve end users.

**Comment by melindaloubser1** [comment] 2022-07-20 22:11
I'm also going to edit the title for clarity in case someone comes looking for the same symptom.

**Comment by skier233** [comment] 2022-07-20 22:14
> I'm also going to edit the title for clarity in case someone comes looking for the same symptom.

@melindaloubser1 Well, importantly, this seems to occurr anytime that asyncio rest request is used. One such time that call is used is when rasa does a callback. My application is getting around this since my rasa server is running in a container on linux where the problem doesn't occur. However, if I ever wanted to run my application as a windows server, this problem would be quite annoying. Also, there are probably a lot of users that would fall into this category.

**Comment by melindaloubser1** [comment] 2022-07-20 22:57
Have you tried the localhost resolution suggestion above for callback or shell?

**Comment by skier233** [comment] 2022-07-20 22:59
I wasn’t sure exactly what they were mentioning. They mentioned a duckling server but I’m not sure what that is as I don’t believe I have anything like that.

**Comment by melindaloubser1** [comment] 2022-07-21 09:59
I edited the code block to make it clearer - idea is to use `127.0.0.1` instead of localhost.

**Closed** 2023-01-09 09:05 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
