### ISSUE TITLE
"Mapping policy not included" warning appears when mapping policy in config

### ISSUE THREAD

**Issue by ice2tricky** [RasaHQ/rasa#4409] opened 2019-09-06 12:49 UTC
**Rasa version**: 1.3

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): windows

**Issue**:
following message started appearing after upgrading to 1.3

rasa.core.policies.ensemble  - MappingPolicy not included in policy ensemble. 

[link ](https://forum.rasa.com/t/mapping-policy-not-included-in-policy-ensemble-but-is-defined-in-the-config-yml/15170) to issue on the community site 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by erohmensing** [comment] 2019-09-06 15:03
Thanks for creating an issue for this. I've confirmed that it shows up even if you have mapping policy in the ensemble.

I think the issue occurs because in this line:
https://github.com/RasaHQ/rasa/blob/7d211d2e3c5bce595b71ee31170216b5ebeff941/rasa/core/policies/ensemble.py#L56

`self.policies` is probably a list of e.g. `policy_2_MappingPolicy`, leading to the same bug that led to the edit here with the `endswith`:
https://github.com/RasaHQ/rasa/blob/7d211d2e3c5bce595b71ee31170216b5ebeff941/rasa/core/policies/mapping_policy.py#L119

cc @imLew

**Comment by imLew** [comment] 2019-09-10 12:48
Oh man 😅, yes in 1.3 we added a check for that because MappingPolicy is required for default intents `/restart` and `/back` to work. But I think you're right @erohmensing, I'll try to have PR for this today or tomorrow.

**Comment by tdzienniak** [comment] 2019-09-26 09:02
In version 1.3.6 I get this bug when trying to predict actions:
```
2019-09-26 08:50:33 DEBUG    rasa.server  - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/server.py", line 583, in predict
    responses = app.agent.predict_next(conversation_id)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 478, in predict_next
    return processor.predict_next(sender_id)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 121, in predict_next
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 588, in _get_next_action_probabilities
    tracker, self.domain
  File "/usr/local/lib/python3.6/site-packages/rasa/core/policies/ensemble.py", line 382, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/policies/mapping_policy.py", line 119, in predict_action_probabilities
     ).__name__ or latest_action.policy.endswith("_" + type(self).__name__):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by imLew** [comment] 2019-09-27 12:26
@tdzienniak thanks for reporting that bug, please reopen it as a new issue though, as it is not related to the original issue.
This issue should have been closed when the PR fixing it was merged.

**Closed by imLew** 2019-09-27 12:26 UTC
Labels: Rasa, bug
