### ISSUE TITLE
Reponse validation gives incorrect warning for sub-intent responses

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8070] opened 2021-03-01 08:36 UTC
**Rasa version**:
2.3.1

As far as I can tell, this was introduced somewhere in 2.1, it's not an issue for 2.0.x

**Python version**:
3.7.2

**Operating system** (windows, osx, ...):
OSX

**Issue**:
The response validation fails to recognize sub-intent responses.

**Error (including full traceback)**:
```
rasa/rasa/shared/utils/io.py:96: UserWarning: Action 'utter_chitchat' is listed as a response action in the domain file, but there is no matching response defined. Please check your domain.
  More info at https://rasa.com/docs/rasa/responses
rasa/rasa/shared/utils/io.py:96: UserWarning: Action 'utter_faq' is listed as a response action in the domain file, but there is no matching response defined. Please check your domain.
  More info at https://rasa.com/docs/rasa/responses
rasa/rasa/shared/utils/io.py:96: UserWarning: Action 'utter_out_of_scope' is listed as a response action in the domain file, but there is no matching response defined. Please check your domain.
  More info at https://rasa.com/docs/rasa/responses
```

**Command or request that led to error**:
```
rasa train
```
in `rasa-demo`.

**Content of response file**:
https://github.com/RasaHQ/rasa-demo/blob/main/data/nlu/responses/responses.yml
```
version: "2.0"
responses:
  utter_out_of_scope/non_english:
  - text: "I only understand English, I'm sorry."
  utter_out_of_scope/other:
  - text: "I can't help you with that, I'm sorry."
  utter_faq/channels:
  - text: "We have a [comprehensive list of supported connectors](https://rasa.com/docs/core/connectors/),
    but if you don't see the one you're looking for, you can always create a custom connector by following
    [this guide](https://rasa.com/docs/rasa/user-guide/connectors/custom-connectors/)."
  utter_faq/community_size:
  - text: "Rasa has more than 7000 community members and over 300 code and content contributors 🚀."
  utter_faq/languages:
  - text: "You can use Rasa to build assistants in any language you want!"
 
...
```

**Comment by koernerfelicia** [comment] 2021-03-01 08:37
Related: https://forum.rasa.com/t/i-cannot-understand-the-error-regarding-responses/40414

**Comment by lullaby-afa** [comment] 2021-03-24 06:06
have fixed this bug?

**Comment by koernerfelicia** [comment] 2021-03-25 14:48
@lullaby-afa the issue will be closed when it's fixed! But this shouldn't be too much of a problem - you can just ignore the warning for now

**Comment by lullaby-afa** [comment] 2021-03-26 01:06
oki, Thank you~

**Comment by hsm207** [comment] 2021-11-24 14:37
This looks like a duplicate of #7645

**Comment by koernerfelicia** [comment] 2021-11-24 14:41
Yep, that's true, I think this one has already been looked at by Enable (when they moved it to "Future"), but the other has more context. Maybe we keep the other and move this one into Enable's "Future" column?

**Closed** 2021-11-24 16:12 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:

**Comment by TyDunn** [comment] 2021-11-24 16:13
@hsm207 Yes, we can close it. I accidentally closed the wrong one, so I probably messed up the prioritisation of the other issue in the CSE backlog. Can you check that it is still correct?

**Comment by hsm207** [comment] 2021-11-24 16:44
@TyDunn  it's all the way at the bottom now 🤣

I will move it back to the CSE Inbox so that the team can re-prioritise it on Monday.

**Comment by TyDunn** [comment] 2021-11-24 21:19
My apologies 😬
