### ISSUE TITLE
change the logic of retraining models

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#7581] opened 2020-12-17 12:14 UTC
currently if smth changed, we most likely retrain both NLU and core models (see https://github.com/RasaHQ/rasa/issues/7129 for details). However in majority of the cases this retraining is unnecessary. Instead of comparing data, we should compare featurizer outputs and retrain only if they changed, not the data

**Comment by twerkmeister** [comment] 2021-03-17 12:59
Hey @Ghostvv, I read through the issue #7129 that you linked. However, it is very difficult for me to understand what needs to be done here, as the issue is 3 months old and I don't know what has potentially changed since then. Are there any problems mentioned in that old issue that are still around?

What are examples of these changes that don't require a full retraining and how common are they? How much time does it cost you?

**Comment by Ghostvv** [comment] 2021-03-17 14:18
there are many variants, for example when you add some nlu examples that don't contain new words, you don't actually need to retrain core model.

Giving current architecture, I don't think it is easy implement right now. This is issue should be part of bigger refactoring where featurizers become independent component from nlu. cc @wochinge and @joejuzl

**Comment by wochinge** [comment] 2021-11-05 10:23
fixed with Rasa Open Source 3.0

**Closed by wochinge** 2021-11-05 10:23 UTC
Labels: type:enhancement :sparkles:, area:rasa-oss :ferris_wheel:, area:rasa-oss/ml 👁, area:rasa-oss/ml/policies, area:rasa-oss/ml/nlu-components
