### ISSUE TITLE
Rasa X: Correcting actions triggers “action_session_start” in the middle of conversation

### ISSUE THREAD

**Issue by alexyuwen** [RasaHQ/rasa#7787] opened 2021-01-23 01:18 UTC
Rasa X is incorrectly predicting `action_default_fallback`, and when I try to correct the action, `action_session_start` is automatically called.  It seems to start a new conversation which is inconsistent with my understanding of `action_session_start` that it should be called only at the beginning of conversations or following periods of inactivity.  I was able to successfully run `rasa data validate` so I don't believe the issue is with my domain or stories.

I attached 3 screenshots.  The first is when `action_default_fallback` is incorrectly predicted.  The second is after I click on "Correct action." The third is after I submitted the correct action.
<img width="1414" alt="Rasa X 1" src="https://user-images.githubusercontent.com/68449128/105564165-3b297580-5cde-11eb-8e7a-fc3727a470c7.png">
<img width="1414" alt="Rasa X 2" src="https://user-images.githubusercontent.com/68449128/105564168-3d8bcf80-5cde-11eb-9ded-bbb5ed70697c.png">
<img width="1414" alt="Rasa X 3" src="https://user-images.githubusercontent.com/68449128/105564170-3fee2980-5cde-11eb-9169-f13fc343ddc5.png">

I am using a Mac and PyCharm.  Here's the version info:
![Screen Shot 2021-01-18 at 11 39 50 AM](https://user-images.githubusercontent.com/68449128/105564098-e685fa80-5cdd-11eb-9c1a-820d0e5bed91.png)

**Comment by sara-tagger** [comment] 2021-01-25 07:00
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by mjaycub** [comment] 2021-02-25 13:17
Looks like an open source issue, need to double check.

**Comment by mprazz** [comment] 2021-07-12 13:51
No longer reproducible on `main` -- closing this issue

**Closed by mprazz** 2021-07-12 13:51 UTC
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:
