### ISSUE TITLE
Rasa X Template API call design issues

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4185] opened 2019-08-06 15:51 UTC
**Description of Problem**: The template related API calls seem inconsistent and not completely thought out. This is related to the domain issue raised in #4176.

For example, if I call the update domain [PUT](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/updateDomain) call it will update intents and actions and leave response templates alone. However, this call has a `store_templates` option that probably shouldn't be there. There's a separate group of template API calls which seems like the place for all template calls.

However, if I call the update domain with`store_templates=true`, I would expect it to only update response templates but instead it updates response templates, intents and actions.

There's also no DEL call for domains and templates so I have to use the PUT calls with null data.

**Overview of the Solution**: Remove all template related calls from the domain group of API calls.

In addition, complete the template API calls by adding the following:

*   `DEL` call to delete all **or** selected templates
*   Add a `POST` that templates from a YAML (this is the same as currently calling the domain PUT call with a YAML file which effectively is a POST if the YAML data is not already in Rasa X).
*   A `PUT` call that support a YAML payload (similar to the POST, this can already be accomplished via the domain `PUT` with `store_templates` but should be a separate template call)
*   A `GET` call that will return YAML (the current GET only returns json)

**Comment by sara-tagger** [comment] 2019-08-07 06:00
Thanks for submitting this feature request 🚀@wochinge will get back to you about it soon!✨

**Comment by wochinge** [comment] 2019-08-07 14:41
Regarding the domain endpoint issues you are having:
I think this is mostly a duplicate of https://github.com/RasaHQ/rasa/issues/4080, isn't it?

> DEL call to delete all or selected templates

That's actually there, but not documented 🙈Thanks for pointing that out! Will do a pr for this asap.

Regarding the compatibility with yaml: I think the domain endpoint actually covers that already and json is basically yaml. However, I'll share it for discussion with the rest of the team.

**Comment by rgstephens** [comment] 2019-08-08 14:23
Yes, there's overlap. I think this issue covers more than #4080 and that #4080 could be close.

**Comment by tmbo** [comment] 2019-08-20 12:27
I agree the domain and corresponding endpoints aren't very well thought through. I think the underlying issue is, that templates shouldn't be part of the domain in the first place as their configuration influences different parts of the pipeline (domain -> training, templates -> nlg, so prediction).

For the endpoints I think we should make sure:
- there is a `/templates` resource supporting CRUD
- there is a `/domain` resource supporting RU

**Comment by rgstephens** [comment] 2019-09-05 20:05
I've upgraded to the latest Rasa X (0.20.2) and just noted a new issue with this endpoint, #4400.

This got me looking more closely at the `/templates` endpoints. These endpoints all work in `json` Rasa is setup for the user to specify the templates in `markdown`. Unlike the intents and stories, there's no convert method between markdown and json.

Will the `/templates` endpoints be supporting markdown?

**Comment by rgstephens** [comment] 2019-09-10 22:03
I just noticed that @tmbo's comment about the `/domain` endpoint.  I believe that should support the full CRUD calls not just RU. I want to be able to completely remove and reload a Rasa X configuration so I'd like to be able to Create and Delete the domain.

**Comment by alexweidauer** [comment] 2022-06-08 12:14
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.

**Closed by alexweidauer** 2022-06-08 12:14 UTC
Labels: type:enhancement :sparkles:, area:rasa-x/backend :tophat:
