### ISSUE TITLE
Finetuning core QA: Adding a new rule and then retraining with `--finetune` leads to errors.

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#10107] opened 2021-11-08 15:00 UTC
**Steps to replicate issue**:
- `rasa init` in a new project
- run `rasa train`
- add a new rule in `rules.yml`:
```
- rule: Say greet anytime the user greets
  steps:
  - intent: greet
  - action: utter_greet
```
- run `rasa train --finetune`

**Debug log output**:

```
The configuration for pipeline and policies was chosen automatically. It was written into the config file at 'config.yml'.
2021-11-08 14:37:02 WARNING  rasa.shared.utils.common  - The Incremental Training feature is currently experimental and might change or be removed in the future 🔬 Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2021-11-08 14:37:03 WARNING  rasa.engine.caching  - Failed to restore cached output of type 'rasa.engine.storage.resource.Resource' from cache. Error:
Destination path '/var/folders/7b/f35sqj5n0llf_38l71z6r9jr0000gn/T/tmpow_mre7z/train_CountVectorsFeaturizer3' is not empty. Directories can only be copied to empty directories.
2021-11-08 14:37:03 WARNING  rasa.engine.caching  - Failed to restore cached output of type 'rasa.engine.storage.resource.Resource' from cache. Error:
Destination path '/var/folders/7b/f35sqj5n0llf_38l71z6r9jr0000gn/T/tmpow_mre7z/train_CountVectorsFeaturizer4' is not empty. Directories can only be copied to empty directories.
2021-11-08 14:37:03 WARNING  rasa.engine.caching  - Failed to restore cached output of type 'rasa.engine.storage.resource.Resource' from cache. Error:
Destination path '/var/folders/7b/f35sqj5n0llf_38l71z6r9jr0000gn/T/tmpow_mre7z/train_DIETClassifier5' is not empty. Directories can only be copied to empty directories.
2021-11-08 14:37:03 INFO     rasa.engine.training.hooks  - Restored component 'RegexFeaturizer' from cache.
2021-11-08 14:37:03 INFO     rasa.engine.training.hooks  - Restored component 'LexicalSyntacticFeaturizer' from cache.
Processed story blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1257.00it/s, # trackers=1]
Processed story blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 733.53it/s, # trackers=4]
Processed story blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 162.94it/s, # trackers=20]
Processed story blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 52.52it/s, # trackers=50]
Processed rules: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3405.39it/s, # trackers=1]
2021-11-08 14:37:04 INFO     rasa.engine.training.hooks  - Starting to train component 'MemoizationPolicy'.
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1462.45it/s, # action=17]
Processed actions: 17it [00:00, 12099.64it/s, # examples=17]
2021-11-08 14:37:04 INFO     rasa.engine.training.hooks  - Finished training component 'MemoizationPolicy'.
2021-11-08 14:37:04 INFO     rasa.engine.training.hooks  - Starting to train component 'RulePolicy'.
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1671.26it/s, # action=7]
Processed actions: 7it [00:00, 8816.86it/s, # examples=6]
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 990.16it/s, # action=17]
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 2557.50it/s]
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 1864.73it/s]
2021-11-08 14:37:05 INFO     rasa.engine.training.hooks  - Finished training component 'RulePolicy'.
2021-11-08 14:37:05 INFO     rasa.engine.training.hooks  - Starting to train component 'TEDPolicy'.
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244/244 [00:00<00:00, 2203.63it/s, # action=43]
Epochs:   0%|                                                                                                                                                                       | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/graph.py", line 455, in __call__
    output = self._fn(self._component, **run_kwargs)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/policies/ted_policy.py", line 718, in train
    self.run_training(model_data, label_ids)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/policies/ted_policy.py", line 673, in run_training
    self.model.fit(
AttributeError: 'NoneType' object has no attribute 'fit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ancalita/rasa-projects/qa-rc1/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/cli/train.py", line 91, in run_training
    training_result = train_all(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/api.py", line 105, in train
    return train(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/model_training.py", line 170, in train
    return _train_graph(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/model_training.py", line 237, in _train_graph
    trainer.train(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/training/graph_trainer.py", line 108, in train
    graph_runner.run(inputs={PLACEHOLDER_IMPORTER: importer})
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/runner/dask.py", line 106, in run
    dask_result = dask.get(run_graph, run_targets)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 560, in get_sync
    return get_async(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 503, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "/Users/ancalita/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/ancalita/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 545, in submit
    fut.set_result(fn(*args, **kwargs))
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 237, in batch_execute_tasks
    return [execute_task(*a) for a in it]
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 237, in <listcomp>
    return [execute_task(*a) for a in it]
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 228, in execute_task
    result = pack_exception(e, dumps)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/graph.py", line 461, in __call__
    raise GraphComponentException(
rasa.engine.exceptions.GraphComponentException: Error running graph component for node train_TEDPolicy3.
```

**Definition of Done**:
- [ ] investigate if source of exception was the failed cache retrievals.

**Comment by jupyterjazz** [comment] 2021-12-08 13:57
@ancalita, I followed the steps but couldn't reproduce the error (same happened when Matt and Kathrin tried it). Could you please try to run it again? or is there maybe a different way to reproduce it? 

Also, looking at your log output we noticed that caching is failing which is not the case in ours. So maybe that's one thing worth investigating...

**Comment by ancalita** [comment] 2021-12-08 14:14
@jupyterjazz yup this happened to me when I attempted a second time, as described in the [Notion title](https://www.notion.so/rasa/Adding-a-new-rule-and-then-retraining-with-finetune-leads-to-errors-can-be-ignored-since-I-was-b58bf32030064faa9f1678309200dc9e) 🙈
 It's very possible this was related to the cache failure which is partially why I added this issue, I can add a DoD (which I seem to have forgotten about 😅 ) to investigate this route, since this was actually my intention when submitting the issue.

**Comment by jupyterjazz** [comment] 2021-12-13 14:59
So the problem is in fact in loading, but I don't think it's necessarily a cache failure because the logs don't even mention `TED` i.e. the component that isn't loaded correctly. 
Probably the directory didn't have a usable model resulting in `self.model` being `None` (#10517), but we have no idea why this happened and given we can't reproduce it I suggest we close this issue and reopen it if we find something new.

**Closed by jupyterjazz** 2021-12-13 14:59 UTC
Labels: area:rasa-oss :ferris_wheel:, feature:rasa-3.0/architecture, resolution:cannot-reproduce, 3.0.0rc-QA-issue
