### ISSUE TITLE
Spacy Featurizer does not set word embeddings as features

### ISSUE THREAD

**Issue by robertanto** [RasaHQ/rasa#9784] opened 2021-10-02 11:46 UTC
### Rasa Open Source version

2.7.2

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

I am using the following pipeline to train an Italian NLU model.

language: "it"

pipeline:

*   name: SpacyNLP model: "it_core_news_sm"
*   name: SpacyTokenizer
*   name: SpacyFeaturizer pooling: "mean"
*   name: DIETClassifier epochs: 1
*   name: EntitySynonymMapper
*   name: ResponseSelector epochs: 100
*   name: FallbackClassifier threshold: 0.7

When I run `rasa train nlu`, I obtain the following error in the DIET training step: `TFLayerConfigException: The attribute signature must contain some sequence-level feature signatures but none were found.`

Going into the code of the spacy_featurizer:

def _set_spacy_features(self, message: Message, attribute: Text = TEXT) -> None: """Adds the spacy word vectors to the messages features.""" doc = self.get_doc(message, attribute)

if doc is None: return

1.  in case an empty spaCy model was used, no vectors are present if doc.vocab.vectors_length == 0: logger.debug("No features present. You are using an empty spaCy model.") return

sequence_features = self._features_for_doc(doc) sentence_features = self._calculate_sentence_features( sequence_features, self.pooling_operation )

final_sequence_features = Features( sequence_features, FEATURE_TYPE_SEQUENCE, attribute, self.component_config<span class="error">[FEATURIZER_CLASS_ALIAS]</span>, ) message.add_features(final_sequence_features) final_sentence_features = Features( sentence_features, FEATURE_TYPE_SENTENCE, attribute, self.component_config<span class="error">[FEATURIZER_CLASS_ALIAS]</span>, ) message.add_features(final_sentence_features)

I saw that `doc.vocab.vectors_length = 0` even if the spacy model has computed the word embeddings. Therefore, no features are set in the message for the following components.

It sounds like a bug, doesn't it?

### Command / Request

 _No response_ 

### Relevant log output

 _No response_ 

**Definition of done**:

*   [ ] Investigate where the bug is coming from (involves looking into Spacy `doc`s, e.g. `doc.vocab` and `doc.tensor`)
*   [ ] Write tests that catch the bug
*   [ ] Implement a fix, likely by adopting or extending the proposed one
*   [ ] Get the fix merged into `2.8.x`

**Comment by robertanto** [comment] 2021-10-02 14:45
In my case, I solved modifying the function in the following way:

```
    def _set_spacy_features(self, message: Message, attribute: Text = TEXT) -> None:
        """Adds the spacy word vectors to the messages features."""
        doc = self.get_doc(message, attribute)

        if doc is None:
            return

        sequence_features = doc.tensor # (num_tokens, dim_features)
        sentence_features = np.expand_dims(np.mean(doc.tensor,0),0) # (1, dim_features)

        final_sequence_features = Features(
            sequence_features,
            FEATURE_TYPE_SEQUENCE,
            attribute,
            self.component_config[FEATURIZER_CLASS_ALIAS],
        )
        message.add_features(final_sequence_features)
        final_sentence_features = Features(
            sentence_features,
            FEATURE_TYPE_SENTENCE,
            attribute,
            self.component_config[FEATURIZER_CLASS_ALIAS],
        )
        message.add_features(final_sentence_features)
```

**Comment by sara-tagger** [comment] 2021-10-04 06:00
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment] 2021-10-05 07:32
Hey @robertanto, this looks like a bug indeed, thanks for spotting it and digging into the code! I'll try to reproduce it first.

**Comment by samsucik** [comment] 2021-10-05 07:38
Alright, I've been able to reproduce this very easily -- by creating a default project (`rasa init`) and replacing the config with the one provided above.

**Comment by samsucik** [comment] 2021-10-05 11:56
I'm moving this along to our inbox to be picked up soon.

As far as I can see, `rasa train nlu` has been breaking on this thing for quite some time now. With `2.5.x` (i.e. after we upgraded to Spacy 3.0) I'm seeing the error reported above. With `2.4.x`, I see an older error which, however, seems to be due to the same thing -- features not being present where we expect them to be after Spacy featurisation. I think this deserves a deeper exploration and tests to see if the above fix is sufficient or if we need to do more.

**Comment by koaning** [comment] 2021-10-05 12:08
Could you try using the `md` model instead of the `sm` one? The `sm` models in spaCy don't always have proper vectors if I recall correctly.

**Comment by koaning** [comment] 2021-10-05 12:09
Per docs, [here](https://spacy.io/models/it):

![image](https://user-images.githubusercontent.com/1019791/136019572-6572b063-3b37-486a-ae21-ed46552e1585.png)

**Comment by koaning** [comment] 2021-10-05 12:18
Also [here](https://spacy.io/usage/linguistic-features#vectors-similarity). 

![image](https://user-images.githubusercontent.com/1019791/136020799-8e206e6c-fc99-45c2-ac95-94a9bf0fc8b6.png)

**Comment by robertanto** [comment] 2021-10-05 12:30
If I understand, there are context vectors representative of the word's meaning in the sentence and un-contextualized word embeddings representative of the word itself. Is it right? 

Even if it is not a bug, it may be useful to give the possibility to the user to select which embeddings to use (or eventually use both) as input to DIET.

**Comment by samsucik** [comment] 2021-10-05 12:54
> Even if it is not a bug, it may be useful to give the possibility to the user to select which embeddings to use (or eventually use both) as input to DIET.

I agree with you @robertanto. I guess the first step is to fix the issue with `sm` models so that Rasa gives users a meaningful warning or an error. The next step would be thinking about vectors vs tensors provided by Spacy and how we could use either of those or both combined... For whoever picks up this latter issue, there's some inspiration from @koaning in [this Slack thread](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1633437008322000?thread_ts=1633435652.319900&cid=C8LEHMTAM).

**Closed** 2023-01-09 09:09 UTC
Labels: type:bug :bug:, area:rasa-oss :ferris_wheel:
